//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface DdmlClusterModelSpec : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int clusterModelType; // @dynamic clusterModelType;
@property(nonatomic) int clustersCount; // @dynamic clustersCount;
@property(nonatomic) int distanceType; // @dynamic distanceType;
@property(nonatomic) double expEpsilon; // @dynamic expEpsilon;
@property(retain, nonatomic) NSMutableArray *featuresArray; // @dynamic featuresArray;
@property(readonly, nonatomic) unsigned long long featuresArray_Count; // @dynamic featuresArray_Count;
@property(nonatomic) double learningRate; // @dynamic learningRate;
@property(nonatomic) double validationFraction; // @dynamic validationFraction;

@end

