//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBDoubleArray, NSMutableArray;

@interface DdmlResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *payloadsArray; // @dynamic payloadsArray;
@property(readonly, nonatomic) unsigned long long payloadsArray_Count; // @dynamic payloadsArray_Count;
@property(retain, nonatomic) GPBDoubleArray *yhatsArray; // @dynamic yhatsArray;
@property(readonly, nonatomic) unsigned long long yhatsArray_Count; // @dynamic yhatsArray_Count;
@property(retain, nonatomic) GPBDoubleArray *ysArray; // @dynamic ysArray;
@property(readonly, nonatomic) unsigned long long ysArray_Count; // @dynamic ysArray_Count;

@end

