//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MLFeatureProvider.h"

@class MLMultiArray, NSSet;

@interface EyesSegmentationNNOutput : NSObject <MLFeatureProvider>
{
    MLMultiArray *_mask;
}

@property(retain, nonatomic) MLMultiArray *mask; // @synthesize mask=_mask;
- (void).cxx_destruct;
- (id)featureValueForName:(id)arg1;
@property(readonly, nonatomic) NSSet *featureNames;
- (id)initWithMask:(id)arg1;

@end

