//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface F2FFrameToStartPredictor : NSObject
{
    struct shared_ptr<scenario::FrameToStartPredictor> predictor;
    unsigned int begin;
    unsigned int end;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned long long)getFrameToStart;
- (void)reset:(_Bool)arg1;
- (void)frameRendered;
- (void)frameProcessingFinished:(unsigned long long)arg1;
- (void)frameProcessingStarted:(unsigned long long)arg1;
- (void)framePreloadingFinished;
- (void)framePreloadingStarted;
- (id)initWithParameters:(unsigned long long)arg1 lastFrame:(unsigned long long)arg2 requiredFirstFrames:(unsigned long long)arg3 requiredFramesAfterReset:(unsigned long long)arg4 requiredFPS:(double)arg5 fpsMultiplier:(double)arg6;
- (id)initWithParameters:(unsigned long long)arg1 requiredFirstFrames:(unsigned long long)arg2 requiredFramesAfterReset:(unsigned long long)arg3 requiredFPS:(double)arg4 fpsMultiplier:(double)arg5;

@end

