//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface F2FTargetInstanceAttributes : NSObject
{
    struct TargetInstanceAttributes _attributes;
}

@property(readonly, nonatomic) struct TargetInstanceAttributes attributes; // @synthesize attributes=_attributes;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)getSerializedAttributes;
- (id)initWithTargetInstanceAttributes:(struct TargetInstanceAttributes)arg1;

@end

