//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FSFaceSegmentationPreprocessor : NSObject
{
}

- (id)preprocessImageForSegmentationDuo:(id)arg1 landmarks:(id)arg2 error:(id *)arg3;
- (id)preprocessImageForSegmentation:(id)arg1 landmarks:(id)arg2 maxImageWidth:(double)arg3 maxImageHeight:(double)arg4 error:(id *)arg5;
- (id)init;

@end

