//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class IMPCreateAccountResponse;

@interface IMPCreatePublisherAccountResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) IMPCreateAccountResponse *createAccountResponse; // @dynamic createAccountResponse;
@property(nonatomic) _Bool hasCreateAccountResponse; // @dynamic hasCreateAccountResponse;

@end

