//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface IMPInsightsDailyStoryView : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) float avgCompletionRatio; // @dynamic avgCompletionRatio;
@property(nonatomic) float avgViewTimeSecs; // @dynamic avgViewTimeSecs;
@property(nonatomic) float pctReachAreSubscribers; // @dynamic pctReachAreSubscribers;
@property(nonatomic) long long reach; // @dynamic reach;
@property(nonatomic) long long storyViews; // @dynamic storyViews;
@property(nonatomic) long long timestampMsecs; // @dynamic timestampMsecs;
@property(nonatomic) long long totalViews; // @dynamic totalViews;

@end

