//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt32Value;

@interface IMPManagedProfileCallouts : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasSnapsPostedWeekCount; // @dynamic hasSnapsPostedWeekCount;
@property(nonatomic) _Bool hasSubscribersTodayCount; // @dynamic hasSubscribersTodayCount;
@property(nonatomic) _Bool hasViewsTodayCount; // @dynamic hasViewsTodayCount;
@property(nonatomic) int manageRolesNuxHintViewCount; // @dynamic manageRolesNuxHintViewCount;
@property(retain, nonatomic) GPBInt32Value *snapsPostedWeekCount; // @dynamic snapsPostedWeekCount;
@property(retain, nonatomic) GPBInt32Value *subscribersTodayCount; // @dynamic subscribersTodayCount;
@property(retain, nonatomic) GPBInt32Value *viewsTodayCount; // @dynamic viewsTodayCount;

@end

