//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol LSABitmojiEffectListener <NSObject>
- (void)didRequestBitmojiInfo;
- (void)didRequestBitmojiAvatarId;
- (void)didRequestMegapack:(NSString *)arg1;
- (void)didRequestBitmojiWithId:(NSString *)arg1 avatarId:(NSString *)arg2 friendAvatarId:(NSString *)arg3 stickerType:(int)arg4 scale:(long long)arg5;
- (void)didRequestBitmojiWithId:(NSString *)arg1 avatarId:(NSString *)arg2 stickerType:(int)arg3 scale:(long long)arg4;
- (void)didRequestBitmojiWithId:(NSString *)arg1 stickerType:(int)arg2 scale:(long long)arg3;
@end

