//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LSAEffectInfo, NSSet, NSString;

@protocol LSACompositeEffectManager <NSObject>
- (void)removeEffectWithEffectId:(NSString *)arg1 completion:(void (^)(NSError *))arg2;
- (void)addEffectWithEffectInfo:(LSAEffectInfo *)arg1 async:(_Bool)arg2 completion:(void (^)(NSError *))arg3;
- (void)setDestinationRect:(struct CGRect)arg1 forEffectWithId:(NSString *)arg2 completion:(void (^)(NSError *))arg3;
- (void)setSourceRect:(struct CGRect)arg1 forEffectWithId:(NSString *)arg2 completion:(void (^)(NSError *))arg3;
- (void)setEffectRectangles:(NSSet *)arg1 completion:(void (^)(NSError *))arg2;
@end

