//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LSAAudioPlayerProtocol.h"
#import "LSAScenariumAudioTrackDelegate.h"

@class LSAQueuePerformer, NSMutableDictionary, NSObject<OS_dispatch_semaphore>, NSString;

@interface LSAScenariumAudioPlayer : NSObject <LSAScenariumAudioTrackDelegate, LSAAudioPlayerProtocol>
{
    NSMutableDictionary *_audioTracks;
    LSAQueuePerformer *_performer;
    NSObject<OS_dispatch_semaphore> *_semaphore;
    _Bool _active;
    _Bool _muted;
    _Bool _suspended;
}

@property(nonatomic, getter=isSuspended) _Bool suspended; // @synthesize suspended=_suspended;
@property(nonatomic, getter=isMuted) _Bool muted; // @synthesize muted=_muted;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
- (void).cxx_destruct;
- (void)audioTrackDidRequestRestartPlayback:(id)arg1;
- (void)_setAllSoundsSuspended:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_setAllSoundsMuted:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_trackForHandle:(long long)arg1;
- (_Bool)setVolume:(float)arg1 forTrackWithHandle:(long long)arg2;
- (float)volumeForTrackWithHandle:(long long)arg1;
- (_Bool)isPlayingTrackWithHandle:(long long)arg1;
- (_Bool)setPosition:(double)arg1 forTrackWithHandle:(long long)arg2;
- (double)positionForTrackWithHandle:(long long)arg1;
- (double)durationForTrackWithHandle:(long long)arg1;
- (_Bool)stopTrackWithHandle:(long long)arg1;
- (_Bool)resumeTrackWithHandle:(long long)arg1;
- (_Bool)pauseTrackWithHandle:(long long)arg1;
- (_Bool)playTrackWithHandle:(long long)arg1 repeatCount:(long long)arg2;
- (void)closeTrackWithHandle:(long long)arg1;
- (long long)openTrackAtPath:(id)arg1 playbackFinishCallback:(CDUnknownBlockType)arg2;
- (void)deactivateWithCompletion:(CDUnknownBlockType)arg1;
- (void)activateWithCompletion:(CDUnknownBlockType)arg1;
- (void)resumeAllSoundsWithCompletion:(CDUnknownBlockType)arg1;
- (void)suspendAllSoundsWithCompletion:(CDUnknownBlockType)arg1;
- (void)unmuteAllSoundsWithCompletion:(CDUnknownBlockType)arg1;
- (void)muteAllSoundsWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

