//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LSDepthDataTextureContainer : NSObject
{
    struct TrackerData {
        CDUnknownFunctionPointerType *_vptr$ISerializable;
        _Bool _isruntime;
        struct array<LS::Tracking::Depth::TrackerData::DepthFrame, 2> depthFrames;
        struct DepthFrame newportReferenceDepthFrame;
        shared_ptr_72f2ba33 stereoDepthTexture;
    } _depthTrackingData;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct TrackerData)depthTrackingData;
- (id)initWithDepthTrackingData:(struct TrackerData)arg1;

@end

