//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGLStyleValue.h"

@interface MGLConstantStyleValue : MGLStyleValue
{
    id _rawValue;
}

+ (id)valueWithRawValue:(id)arg1;
@property(retain, nonatomic) id rawValue; // @synthesize rawValue=_rawValue;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)debugDescription;
- (id)description;
- (id)initWithRawValue:(id)arg1;

@end

