//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage;

@interface MGLMapSnapshot : NSObject
{
    function_4a3d9bf5 _pointForFn;
    UIImage *_image;
    double _scale;
}

@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CGPoint)pointForCoordinate:(struct CLLocationCoordinate2D)arg1;
- (id)initWithImage:(id)arg1 scale:(double)arg2 pointForFn:(function_4a3d9bf5)arg3;

@end

