//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLBAuthRequest, NSData;

@interface MLBAuthResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasRequestInfo; // @dynamic hasRequestInfo;
@property(nonatomic) _Bool hasResponseData; // @dynamic hasResponseData;
@property(retain, nonatomic) MLBAuthRequest *requestInfo; // @dynamic requestInfo;
@property(copy, nonatomic) NSData *responseData; // @dynamic responseData;

@end

