//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface MLBAmbaError_AmbaCpuException : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *backtrace; // @dynamic backtrace;
@property(nonatomic) _Bool hasBacktrace; // @dynamic hasBacktrace;
@property(nonatomic) _Bool hasLr; // @dynamic hasLr;
@property(nonatomic) _Bool hasPc; // @dynamic hasPc;
@property(nonatomic) _Bool hasSp; // @dynamic hasSp;
@property(nonatomic) unsigned int lr; // @dynamic lr;
@property(nonatomic) unsigned int pc; // @dynamic pc;
@property(nonatomic) unsigned int sp; // @dynamic sp;

@end

