//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValue.h"

@interface NSValue (MGLLineStyleLayerAdditions)
+ (id)valueWithMGLLineTranslationAnchor:(unsigned long long)arg1;
+ (id)valueWithMGLLineJoin:(unsigned long long)arg1;
+ (id)valueWithMGLLineCap:(unsigned long long)arg1;
@property(readonly) unsigned long long MGLLineTranslationAnchorValue;
@property(readonly) unsigned long long MGLLineJoinValue;
@property(readonly) unsigned long long MGLLineCapValue;
@end

