//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@interface SCAAddFriendPageEndEvent : SCAUserTrackedEvent
{
}

- (void)setVisibleSectionNames:(id)arg1;
- (void)setTwitterButtonClickCount:(long long)arg1;
- (void)setSnapcodeClickCount:(long long)arg1;
- (void)setSmsButtonClickCount:(long long)arg1;
- (void)setShareMySnapcodeItemSeenCount:(long long)arg1;
- (void)setSessionTimeUs:(long long)arg1;
- (void)setQuickAddFriendSeenCount:(long long)arg1;
- (void)setMoreButtonClickCount:(long long)arg1;
- (void)setLoadSectionFailure:(id)arg1;
- (void)setFirstItemLoadedLatencyUs:(long long)arg1;
- (void)setEmailButtonClickCount:(long long)arg1;
- (void)setCompleteLoadedLatencyUs:(long long)arg1;
- (void)setAddedMeFriendSeenCount:(long long)arg1;
- (double)getPerUserSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;

@end

