//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@interface SCABandwidthAccuracy : SCAUserTrackedEvent
{
}

- (void)setRequestDurationMs:(long long)arg1;
- (void)setReachability:(long long)arg1;
- (void)setIsDownloadSample:(_Bool)arg1;
- (void)setEstimationStartBitsPerSecond:(long long)arg1;
- (void)setEstimationEndBitsPerSecond:(long long)arg1;
- (void)setContentLength:(long long)arg1;
- (void)setBytesTransmitted:(long long)arg1;
- (double)getPerUserSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;

@end

