//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSObject<NSCopying>, NSString;

@interface SCActionModel : NSObject <NSCopying>
{
    NSString *_identifier;
    NSObject<NSCopying> *_actionDataModel;
}

@property(readonly, copy, nonatomic) NSObject<NSCopying> *actionDataModel; // @synthesize actionDataModel=_actionDataModel;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithIdentifier:(id)arg1 actionDataModel:(id)arg2;

@end

