//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAMapSerializable.h"

@interface SCACpuUsage : SCAMapSerializable
{
}

- (void)setMinCpuUsage:(long long)arg1;
- (void)setMedianCpuUsage:(long long)arg1;
- (void)setMaxCpuUsage:(long long)arg1;
- (void)setCpuSampleCount:(long long)arg1;
- (void)setAvgCpuUsage:(long long)arg1;
- (double)getPerEventSamplingRate;
- (double)getPerUserSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;

@end

