//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAContextMenuBase.h"

@interface SCAContextMenuAction : SCAContextMenuBase
{
}

- (void)prepareDictionary:(id)arg1;
- (void)setViewSource:(id)arg1;
- (void)setTeamsnapId:(id)arg1;
- (void)setNotificationId:(id)arg1;
- (void)setInviteMetadata:(id)arg1;
- (void)setInviteIdHash:(id)arg1;
- (void)setFilterLensId:(id)arg1;
- (void)setCardId:(id)arg1;
- (void)setActionTypeString:(id)arg1;
- (void)setActionType:(long long)arg1;
- (double)getPerUserSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;

@end

