//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCActionHandling.h"
#import "SCAddToGroupViewControllerDelegate.h"
#import "SCTraceEnabled.h"

@class NSString, SCAddToGroupViewController, SCLazy, SCNewGroupViewController, SCUserSession, UIViewController<SCPageNameLogging>;

@interface SCAddFriendToNewGroupActionHandler : NSObject <SCAddToGroupViewControllerDelegate, SCTraceEnabled, SCActionHandling>
{
    SCUserSession *_userSession;
    id <SCActionHandling> _navigateToChatActionHandler;
    SCAddToGroupViewController *_addToGroupVC;
    SCNewGroupViewController *_newGroupVC;
    id <SCNewGroupViewControllerDelegate> _newGroupViewControllerDelegate;
    SCLazy *_groupsDataCreator;
    UIViewController<SCPageNameLogging> *_presentingViewController;
}

@property(nonatomic) __weak UIViewController<SCPageNameLogging> *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
- (void).cxx_destruct;
- (void)_navigateToChatWithGroupId:(id)arg1;
- (void)navigateToChatViewWithGroupId:(id)arg1;
- (void)navigateToChatViewWithFriend:(id)arg1 deepLinkURL:(id)arg2 viewController:(id)arg3;
- (void)didPressMischiefConfirmationButton:(id)arg1 viewController:(id)arg2 groupName:(id)arg3;
- (void)dismissViewControllerAnimated:(_Bool)arg1 viewController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_presentAddToGroupViewWithUserId:(id)arg1;
- (_Bool)handleActionWithSender:(id)arg1 actionModel:(id)arg2 fromSourceView:(id)arg3;
- (id)initWithUserSession:(id)arg1 navigateToChatActionHandler:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

