//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class SCAdMediaWebView;

@interface SCAdMediaWebviewAttachment : NSObject <NSCopying, NSCoding>
{
    _Bool _blockWebviewPreloading;
    _Bool _allowAutoFill;
    SCAdMediaWebView *_webview;
}

@property(readonly, nonatomic) _Bool allowAutoFill; // @synthesize allowAutoFill=_allowAutoFill;
@property(readonly, nonatomic) _Bool blockWebviewPreloading; // @synthesize blockWebviewPreloading=_blockWebviewPreloading;
@property(readonly, copy, nonatomic) SCAdMediaWebView *webview; // @synthesize webview=_webview;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithWebview:(id)arg1 blockWebviewPreloading:(_Bool)arg2 allowAutoFill:(_Bool)arg3;
- (id)initWithCoder:(id)arg1;

@end

