//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCViewModelConfigurable.h"

@class NSString, SCShapeView, UILabel;

@interface SCAddFriendsExpandableBadgeView : UIView <SCViewModelConfigurable>
{
    UILabel *_badgeLabel;
    SCShapeView *_backgroundShapeView;
    UIView *_labelParentView;
    struct CGRect _shapeLayerPathRect;
    _Bool _animating;
    id _viewModel;
}

+ (struct CGSize)sizeWithViewModel:(id)arg1 constrainedToSize:(struct CGSize)arg2;
@property(retain, nonatomic) id viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)_updateBackgroundShapeViewPath:(struct CGRect)arg1;
- (void)_updateShadow:(id)arg1;
- (void)showTipAnimationWithNumber:(unsigned long long)arg1 toBlankBadge:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)hideBadgeWithAnimation;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

