//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCSnapAdsAdServeRequest, SCSnapAdsIdentifier, SCSnapAdsTrackRequest;

@protocol SCAdSource <NSObject>
- (void)adExpired:(SCSnapAdsIdentifier *)arg1;
- (void)track:(SCSnapAdsTrackRequest *)arg1;
- (void)request:(SCSnapAdsAdServeRequest *)arg1;
@end

