//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCADiscoverSnapViewBase.h"

@interface SCADiscoverSnapLongformView : SCADiscoverSnapViewBase
{
}

- (void)setWithCaptionOnStart:(_Bool)arg1;
- (void)setVideoPartnerId:(id)arg1;
- (void)setPageHeightTotalPixel:(long long)arg1;
- (void)setPageHeightSeenPixel:(long long)arg1;
- (void)setLongformType:(long long)arg1;
- (void)setLandscapeTimeSec:(double)arg1;
- (void)setInlineVideoViewCount:(long long)arg1;
- (void)setInlineVideoTotalCount:(long long)arg1;
- (void)setInlineVideoTimeViewed:(double)arg1;
- (void)setDurationSec:(double)arg1;
- (void)setCaptionTimeSec:(double)arg1;
- (void)setAspectRatio:(double)arg1;
- (double)getPerUserSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;

@end

