//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCOpenUnifiedProfileActionHandlerDelegate.h"
#import "SCStartChatDelegate.h"

@class NSString, SCModalChatViewController, SCUserSession, UIViewController;

@interface SCAddFriendsSnapAndChatDelegate : NSObject <SCStartChatDelegate, SCOpenUnifiedProfileActionHandlerDelegate>
{
    SCUserSession *_userSession;
    UIViewController *_presentingViewController;
    SCModalChatViewController *_chatViewController;
}

- (void).cxx_destruct;
- (void)_presentingChatPageAnimated:(_Bool)arg1;
- (void)_setConversationByChatIdentifier:(id)arg1 deepLinkURL:(id)arg2;
- (void)_navigateToChatWithUsername:(id)arg1 deepLinkURL:(id)arg2;
- (void)setConversationByChatIdentifier:(id)arg1 deepLinkURL:(id)arg2 chatPageSource:(long long)arg3 navigationAction:(long long)arg4 subpageName:(id)arg5;
- (void)navigateToChatViewAnimated:(_Bool)arg1;
- (void)navigateToChatView;
- (void)openUnifiedProfileActionHandler:(id)arg1 navigateToChatWithUsername:(id)arg2 deepLinkURL:(id)arg3;
- (id)initWithUserSession:(id)arg1 presentingViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

