//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCContentDeliveryServices, SCServicesExposer, SCStartupCompleteScope, SCUserSessionScope;

@interface SCAdServicesEntryPoint : SCEntryPoint
{
    SCStartupCompleteScope *_startupCompleteScope;
    SCUserSessionScope *_userSessionScope;
    SCContentDeliveryServices *_contentDeliveryServices;
    SCServicesExposer *_adServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *adServicesExposer; // @synthesize adServicesExposer=_adServicesExposer;
@property(nonatomic) __weak SCContentDeliveryServices *contentDeliveryServices; // @synthesize contentDeliveryServices=_contentDeliveryServices;
@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
@property(nonatomic) __weak SCStartupCompleteScope *startupCompleteScope; // @synthesize startupCompleteScope=_startupCompleteScope;
- (void).cxx_destruct;
- (id)_adContentDelivery;
- (id)end;
- (void)begin;

@end

