//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView;

@interface SCAlertContentItem : NSObject
{
    UIView *_contentView;
    struct UIEdgeInsets _edgeInsets;
}

+ (id)contentItemWithContentView:(id)arg1 edgeInsets:(struct UIEdgeInsets)arg2;
@property(nonatomic) struct UIEdgeInsets edgeInsets; // @synthesize edgeInsets=_edgeInsets;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (id)initWithContentView:(id)arg1 edgeInsets:(struct UIEdgeInsets)arg2;

@end

