//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@interface SCAProfileAddedMePageExit : SCAUserTrackedEvent
{
}

- (void)setTotalRequestCountWithDisplayPic:(long long)arg1;
- (void)setTotalRequestCount:(long long)arg1;
- (void)setRequestNameEditCount:(long long)arg1;
- (void)setRequestIgnoreCount:(long long)arg1;
- (void)setRequestBlockCount:(long long)arg1;
- (void)setRequestAcceptCountWithDisplayPic:(long long)arg1;
- (void)setRequestAcceptCount:(long long)arg1;
- (void)setNewRequestCount:(long long)arg1;
- (double)getPerUserSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;

@end

