//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCArroyoConversationDataUpdateListener.h"
#import "SCArroyoFeedDataUpdateListener.h"

@class NSMutableSet, NSObject<OS_dispatch_queue>, NSSet;

@interface SCArroyoConversationIdsManager : NSObject <SCArroyoFeedDataUpdateListener, SCArroyoConversationDataUpdateListener>
{
    id <SCNativeMessagingSessionManaging> _nativeSessionManager;
    NSMutableSet *_conversationIds;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
- (void)_updateArroyoConversationIdsForFeedEntries:(id)arg1 deletedFeedEntries:(id)arg2;
- (void)didFeedEntriesArrive:(id)arg1;
- (void)didFetchFeedCompleteFeedEntries:(id)arg1 fetchContext:(id)arg2;
- (void)didQueryFeedCompleteFeedEntries:(id)arg1 hasNoMore:(_Bool)arg2 fetchContext:(id)arg3;
- (void)didFetchAndSyncFeedCompleteUpdatedFeedEntries:(id)arg1 deletedFeedEntries:(id)arg2 fetchContext:(id)arg3;
- (void)didSyncFeedCompleteUpdatedFeedEntries:(id)arg1 deletedFeedEntries:(id)arg2 fetchContext:(id)arg3;
- (void)didUpdateFeedEntries:(id)arg1 deletedFeedEntries:(id)arg2;
- (void)didSendComplete:(id)arg1;
- (void)didRemoveConversation:(id)arg1;
- (void)didConversationUpdateForConversationId:(id)arg1 conversation:(id)arg2 updatedMessages:(id)arg3 removedMessages:(id)arg4;
- (void)didCreateConversation:(id)arg1;
- (void)_upsertArroyoConversationIds:(id)arg1 deletedConversationIds:(id)arg2;
- (id)arroyoConversationsFromConversations:(id)arg1;
- (id)arroyoConversationIdsFromConversationIds:(id)arg1;
- (_Bool)isArroyoConversationId:(id)arg1;
- (void)addNewArroyoConversationId:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSSet *arroyoConversationIds;
- (void)_loadLocalFeedEntries;
- (void)_performLoadLocalFeedEntries;
- (void)dispose;
- (id)initWithNativeSessionManager:(id)arg1;

@end

