//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCGeofilterDependencyValidation.h"

@class NSString, SCArSegmentationDownloadedSky;

@interface SCArSegmentationDownloadedInput : NSObject <SCGeofilterDependencyValidation>
{
    _Bool _shouldStillDisplayWithoutSegmentationMatch;
    SCArSegmentationDownloadedSky *_sky;
}

@property(retain, nonatomic) SCArSegmentationDownloadedSky *sky; // @synthesize sky=_sky;
@property(nonatomic) _Bool shouldStillDisplayWithoutSegmentationMatch; // @synthesize shouldStillDisplayWithoutSegmentationMatch=_shouldStillDisplayWithoutSegmentationMatch;
- (void).cxx_destruct;
- (unsigned long long)detectionType;
- (id)validationErrors;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

