//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCArroyoConversationDataUpdateAnnouncer.h"
#import "SCNMessagingConversationManagerDelegate.h"

@class SCArroyoConversationDataUpdateListenerAnnouncer;

@interface SCArroyoConversationDataUpdateAnnouncer : NSObject <SCNMessagingConversationManagerDelegate, SCArroyoConversationDataUpdateAnnouncer>
{
    SCArroyoConversationDataUpdateListenerAnnouncer *_announcer;
}

- (void).cxx_destruct;
- (void)onConversationRemoved:(id)arg1;
- (void)onSendComplete:(id)arg1;
- (void)onConversationUpdated:(id)arg1 conversation:(id)arg2 updatedMessages:(id)arg3 removedMessages:(id)arg4;
- (void)onConversationCreated:(id)arg1;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (id)init;

@end

