//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCASpectaclesTrackedEvent.h"

@interface SCASpectaclesStoryBoomboxView : SCASpectaclesTrackedEvent
{
}

- (void)setViewSource:(long long)arg1;
- (void)setOperaSessionId:(id)arg1;
- (void)setNumVideos:(long long)arg1;
- (void)setNumPhotos:(long long)arg1;
- (void)setEntryId:(id)arg1;
- (void)setDurationSec:(double)arg1;
- (double)getPerUserSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;

@end

