//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@interface SCAStickerPreview : SCAUserTrackedEvent
{
}

- (void)setViewTimeSec:(double)arg1;
- (void)setStickerSourceTab:(long long)arg1;
- (void)setStickerPickSessionId:(id)arg1;
- (void)setStickerPackId:(id)arg1;
- (void)setStickerId:(id)arg1;
- (void)setSnapSessionId:(id)arg1;
- (void)setSectionName:(long long)arg1;
- (void)setCaptureSessionId:(id)arg1;
- (double)getPerUserSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;

@end

