//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@interface SCAStickerPickerSearch : SCAUserTrackedEvent
{
}

- (void)setStickerSnapchatCount:(long long)arg1;
- (void)setStickerSessionId:(id)arg1;
- (void)setStickerResultCount:(long long)arg1;
- (void)setStickerEmojiCount:(long long)arg1;
- (void)setStickerBitmojiCount:(long long)arg1;
- (void)setSnapSessionId:(id)arg1;
- (void)setSearchTerm:(id)arg1;
- (void)setSearchSource:(long long)arg1;
- (void)setSearchSequenceId:(long long)arg1;
- (double)getPerUserSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;

@end

