//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SCAudioConfiguration;

@protocol SCAudioResolver <NSObject>
@property(retain, nonatomic) id <SCProximityStatus> proximityStatus;
- (NSString *)configurationDebugInfo;
- (SCAudioConfiguration *)relinquishConfiguration:(SCAudioConfiguration *)arg1;
- (SCAudioConfiguration *)getCurrentResolvedConfiguration;
- (SCAudioConfiguration *)resolveConfiguration:(SCAudioConfiguration *)arg1;
@end

