//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCAudioServices, SCQueuePerformer;

@interface SCAudioSessionConfiguratorEntryPoint : SCEntryPoint
{
    SCQueuePerformer *_perfomer;
    SCAudioServices *_audioServices;
}

@property(nonatomic) __weak SCAudioServices *audioServices; // @synthesize audioServices=_audioServices;
- (void).cxx_destruct;
- (void)begin;

@end

