//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SCBitmojiLinkPageLogger : NSObject
{
    unsigned long long _page;
    NSString *_profileSessionId;
}

@property(readonly, copy, nonatomic) NSString *profileSessionId; // @synthesize profileSessionId=_profileSessionId;
@property(readonly, nonatomic) unsigned long long page; // @synthesize page=_page;
- (void).cxx_destruct;
- (void)logDeepLinkingWithDeepLinkSource:(id)arg1 isUniversalLink:(_Bool)arg2;
- (void)logSelfieCancel;
- (void)logSelfieChange:(id)arg1 success:(_Bool)arg2;
- (void)logSelfieTap:(id)arg1;
- (void)logSelfieView;
- (void)logOutfitCancel:(unsigned long long)arg1;
- (void)logOutfitChange:(id)arg1 success:(_Bool)arg2 avatarBuilderType:(unsigned long long)arg3;
- (void)logOutfitTap:(id)arg1;
- (void)logOutfitView:(unsigned long long)arg1;
- (void)logLinkSuccessWithAvatarBuilderType:(unsigned long long)arg1;
- (void)logSeeLinkButton;
- (void)logUnlinkBitmoji:(unsigned long long)arg1;
- (void)logSettingBitmojiView:(_Bool)arg1;
- (void)logEditBitmojiSave:(unsigned long long)arg1 avatarBuilderType:(unsigned long long)arg2 withEditedAvatar:(_Bool)arg3;
- (void)logEditBitmoji:(unsigned long long)arg1 bitmojiInstalled:(_Bool)arg2 avatarBuilderType:(unsigned long long)arg3;
- (id)initWithPage:(unsigned long long)arg1 profileSessionId:(id)arg2;

@end

