//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCItemView.h"

@class SCAvatarContainerView;

@interface SCBitmojiInAppNotificationItemView : SCItemView
{
    SCAvatarContainerView *_avatarContainerView;
}

@property(readonly, nonatomic) SCAvatarContainerView *avatarContainerView; // @synthesize avatarContainerView=_avatarContainerView;
- (void).cxx_destruct;
- (_Bool)accessoryViewHasContent;
- (struct CGSize)disclosureSizeThatFits:(struct CGSize)arg1;
- (struct CGSize)accessorySizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

