//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface SCBloopsUpdateUserTargetResult : NSObject <NSCopying>
{
    NSString *_configUrl;
    long long _friendBloopsGender;
}

@property(readonly, nonatomic) long long friendBloopsGender; // @synthesize friendBloopsGender=_friendBloopsGender;
@property(readonly, copy, nonatomic) NSString *configUrl; // @synthesize configUrl=_configUrl;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithConfigUrl:(id)arg1 friendBloopsGender:(long long)arg2;

@end

