//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString, SOJUBloopsBloopsConfig;

@interface SCBloopsRemoteSettingsModel : NSObject <NSCopying, NSCoding>
{
    NSString *_apiVersion;
    SOJUBloopsBloopsConfig *_sojuBloopsConfig;
}

@property(readonly, copy, nonatomic) SOJUBloopsBloopsConfig *sojuBloopsConfig; // @synthesize sojuBloopsConfig=_sojuBloopsConfig;
@property(readonly, copy, nonatomic) NSString *apiVersion; // @synthesize apiVersion=_apiVersion;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithApiVersion:(id)arg1 sojuBloopsConfig:(id)arg2;

@end

