//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCAppUserLifecycleEventHandler, SCEntryPointCleanup, SCExtensionBlizzardEventProcessor, SCLoggerServices, SCSystemScope, SCUserSessionScope;

@interface SCBlizzardAppExtensionEntryPoint : SCEntryPoint
{
    SCAppUserLifecycleEventHandler *_lifecycleEventHandler;
    SCEntryPointCleanup *_cleanup;
    SCExtensionBlizzardEventProcessor *_eventProcessor;
    SCSystemScope *_systemScope;
    SCUserSessionScope *_userSessionScope;
    SCLoggerServices *_logger;
}

@property(nonatomic) __weak SCLoggerServices *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
@property(nonatomic) __weak SCSystemScope *systemScope; // @synthesize systemScope=_systemScope;
- (void).cxx_destruct;
- (id)end;
- (void)begin;

@end

