//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPRemoteSettingsProvider.h"

@class NSHashTable, NSString, SCPreferences, SCQueuePerformer;

@interface SCBloopsRemoteSettingsProvider : NSObject <SPRemoteSettingsProvider>
{
    NSString *_bloopsApiVersion;
    SCQueuePerformer *_performer;
    SCPreferences *_userPreferences;
    NSHashTable *_outputs;
    id <SCBloopsRemoteSettingsProviderChangesDelegate> _changesDelegate;
}

@property(nonatomic) __weak id <SCBloopsRemoteSettingsProviderChangesDelegate> changesDelegate; // @synthesize changesDelegate=_changesDelegate;
- (void).cxx_destruct;
- (void)_notifyOutputsWithConfigUrl:(id)arg1 aiModelsBaseUrlPath:(id)arg2;
- (id)_currentRemoteSettingsModel;
- (void)obtainSettingsForOutput:(id)arg1;
- (void)getSettingsFromCache:(CDUnknownBlockType)arg1;
- (void)updateSettings:(id)arg1;
- (void)obtainConfigUrlWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateConfigUrl:(id)arg1;
- (id)initWithBloopsApiVersion:(id)arg1 userPreferences:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

