//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCBloopsPersonsSource : NSObject
{
    id <SCBloopsTarget> _mainTarget;
    id <SCBloopsTarget> _secondTarget;
}

@property(readonly, nonatomic) id <SCBloopsTarget> secondTarget; // @synthesize secondTarget=_secondTarget;
@property(readonly, nonatomic) id <SCBloopsTarget> mainTarget; // @synthesize mainTarget=_mainTarget;
- (void).cxx_destruct;
- (id)initWithMainTarget:(id)arg1 secondTarget:(id)arg2;

@end

