//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCBloopsModel.h"

@class NSString, SPScenario;

@interface SCBloopsModelImpl : NSObject <SCBloopsModel>
{
    unsigned long long _bloopType;
    SPScenario *_scenario;
}

@property(readonly, nonatomic) SPScenario *scenario; // @synthesize scenario=_scenario;
@property(readonly, nonatomic) unsigned long long bloopType; // @synthesize bloopType=_bloopType;
- (void).cxx_destruct;
- (unsigned long long)convertBloopsTypeToSPType:(unsigned long long)arg1;
- (_Bool)_isEqualToBloopsModel:(id)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) unsigned long long personsCount;
- (id)initWithScenario:(id)arg1 bloopType:(unsigned long long)arg2 splendid:(id)arg3;
- (id)initWithScenario:(id)arg1 bloopType:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

