//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, SCMossMediaCaptureContext;

@interface SCBoltv2MediaProperties : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCMossMediaCaptureContext *captureContext; // @dynamic captureContext;
@property(nonatomic) _Bool hasCaptureContext; // @dynamic hasCaptureContext;
@property(copy, nonatomic) NSString *iv; // @dynamic iv;
@property(copy, nonatomic) NSString *key; // @dynamic key;

@end

