//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSHashTable, SCQueuePerformer;

@interface SCCapturerTokenSet : NSObject
{
    SCQueuePerformer *_performer;
    NSHashTable *_tokenSet;
}

@property(retain, nonatomic) NSHashTable *tokenSet; // @synthesize tokenSet=_tokenSet;
@property(retain, nonatomic) SCQueuePerformer *performer; // @synthesize performer=_performer;
- (void).cxx_destruct;
- (id)debugDescription;
- (_Bool)containsAnyToken;
- (void)removeToken:(id)arg1;
- (void)addToken:(id)arg1;
- (id)initWithPerformer:(id)arg1;

@end

