//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SOJUConversationMessage;

@protocol SCChatSenderDelegate <NSObject>
- (void)logSendAttempt;
- (_Bool)isSCCPSessionConnected;
- (void)writeConversationMessage:(SOJUConversationMessage *)arg1 withCompletionHandler:(void (^)(NSError *))arg2;
@end

