//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCChatMediaDownloadHandler.h"

@class NSString, SCChatV3MetadataStore, SCExperimentManager, SCLazy, SCSessionRequestManager;

@interface SCChatSearchStoryDownloadHandler : NSObject <SCChatMediaDownloadHandler>
{
    id <SCChatRequestManager> _chatRequestManager;
    SCChatV3MetadataStore *_metadataStore;
    id <SCChatLogger> _logger;
    SCExperimentManager *_experimentManager;
    SCSessionRequestManager *_requestManager;
    SCLazy *_snapTokenProvider;
}

- (void).cxx_destruct;
- (void)downloadItem:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithChatRequestManager:(id)arg1 metadataStore:(id)arg2 messageStateHandler:(id)arg3 mediaStateManager:(id)arg4 mediaReferenceManager:(id)arg5 experimentManager:(id)arg6 requestManager:(id)arg7 snapTokenProvider:(id)arg8 logger:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

