//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCChatEraseMessageControlling.h"

@class NSString;

@interface SCChatEraseMessageController : NSObject <SCChatEraseMessageControlling>
{
    id <SCChatEraseMessageControllerDelegate> _delegate;
    id <SCActionHandling> _actionHandler;
}

- (void).cxx_destruct;
- (id)_learnMoreMessageId:(id)arg1 conversationId:(id)arg2 isGroupConversation:(_Bool)arg3 confirmDeleteDataModel:(id)arg4;
- (id)_cancelAction;
- (id)_eraseActionMessageId:(id)arg1 conversationId:(id)arg2 isGroupConversation:(_Bool)arg3 confirmDeleteDataModel:(id)arg4;
- (id)_okayActionWithMessageId:(id)arg1 conversationId:(id)arg2 isGroupConversation:(_Bool)arg3;
- (void)_presentLearnMorePromptForMessageId:(id)arg1 conversationId:(id)arg2 isGroupConversation:(_Bool)arg3 isPresentedFirst:(_Bool)arg4 confirmDeleteDataModel:(id)arg5;
- (void)_presentEraseMessagePromptForMessageId:(id)arg1 conversationId:(id)arg2 isGroupConversation:(_Bool)arg3 confirmDeleteDataModel:(id)arg4;
- (void)_eraseMessageId:(id)arg1 inConversationId:(id)arg2 isGroupConversation:(_Bool)arg3 isFirstTime:(_Bool)arg4 confirmDeleteDataModel:(id)arg5;
- (void)eraseMessageId:(id)arg1 inConversationId:(id)arg2 isGroupConversation:(_Bool)arg3 isFirstTime:(_Bool)arg4;
- (void)eraseMessageId:(id)arg1 inConversationId:(id)arg2 isGroupConversation:(_Bool)arg3 confirmDeleteDataModel:(id)arg4;
- (id)initWithDelegate:(id)arg1 actionHandler:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

