//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString, UIImage;

@interface SCChatReplayAnimationData : NSObject <NSCopying>
{
    long long _replayAnimationState;
    NSString *_messageId;
    UIImage *_filledReplayIconImage;
    UIImage *_emptyReplayIconImage;
}

@property(readonly, copy, nonatomic) UIImage *emptyReplayIconImage; // @synthesize emptyReplayIconImage=_emptyReplayIconImage;
@property(readonly, copy, nonatomic) UIImage *filledReplayIconImage; // @synthesize filledReplayIconImage=_filledReplayIconImage;
@property(readonly, copy, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(readonly, nonatomic) long long replayAnimationState; // @synthesize replayAnimationState=_replayAnimationState;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithReplayAnimationState:(long long)arg1 messageId:(id)arg2 filledReplayIconImage:(id)arg3 emptyReplayIconImage:(id)arg4;

@end

