//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSMutableDictionary, UIView;

@interface SCChatSDKStackableContentCollectionViewCell : UICollectionViewCell
{
    _Bool _isUIRendered;
    id <SCChatMessageRenderer> _renderer;
    NSMutableDictionary *_subViewDic;
    UIView *_messageContentView;
}

@property(retain, nonatomic) UIView *messageContentView; // @synthesize messageContentView=_messageContentView;
@property(retain, nonatomic) NSMutableDictionary *subViewDic; // @synthesize subViewDic=_subViewDic;
@property(retain, nonatomic) id <SCChatMessageRenderer> renderer; // @synthesize renderer=_renderer;
@property(nonatomic) _Bool isUIRendered; // @synthesize isUIRendered=_isUIRendered;
- (void).cxx_destruct;
- (void)didEndDisplayingCell;
- (void)willDisplayCell;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

