//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, SCChatConversationsVersion;

@interface SCChatConversationsSyncVerificationData : NSObject <NSCopying>
{
    NSArray *_conversationIdsToSync;
    SCChatConversationsVersion *_conversationsVersion;
}

@property(readonly, copy, nonatomic) SCChatConversationsVersion *conversationsVersion; // @synthesize conversationsVersion=_conversationsVersion;
@property(readonly, copy, nonatomic) NSArray *conversationIdsToSync; // @synthesize conversationIdsToSync=_conversationIdsToSync;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithConversationIdsToSync:(id)arg1 conversationsVersion:(id)arg2;

@end

