//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCChatConversationStoreListener.h"
#import "SCChatMetadataStoreListener.h"
#import "SCConversationWithMetadataAnnouncer.h"

@class NSString, SCChatConversationMetadataUpdaterListenerAnnouncer, SCChatV3ConversationStore, SCChatV3MetadataStore;

@interface SCChatConversationMetadataUpdater : NSObject <SCChatConversationStoreListener, SCChatMetadataStoreListener, SCConversationWithMetadataAnnouncer>
{
    SCChatV3ConversationStore *_conversationStore;
    SCChatV3MetadataStore *_metadataStore;
    SCChatConversationMetadataUpdaterListenerAnnouncer *_announcer;
}

- (void).cxx_destruct;
- (void)_announceUpdateWithConversation:(id)arg1 metadata:(id)arg2;
- (void)metadataDidUpdate:(id)arg1 conversationId:(id)arg2;
- (void)diskLoadFinishedWithConversations:(id)arg1;
- (void)conversationDidUpdate:(id)arg1;
- (void)removeListener:(id)arg1;
- (_Bool)addListener:(id)arg1;
- (id)initWithConversationStore:(id)arg1 metadataStore:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

