//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SCChatBaseViewController, UIImage, UIView, UIViewController;

@protocol SCChatViewControllerParentDelegate <NSObject>
- (void)unlockScrollWithRequestId:(NSString *)arg1;
- (void)lockScrollWithRequestId:(NSString *)arg1;
- (void)setScrollEnabled:(_Bool)arg1;
- (void)rightButtonPressed;
- (void)didBecomeFullChat;
- (UIImage *)rightButtonImage;
- (_Bool)isFrameInVisibleBounds:(UIViewController *)arg1;
- (_Bool)presentedModally;
- (_Bool)isFullyVisible:(UIViewController *)arg1;
- (_Bool)isPartiallyVisibleInStack:(SCChatBaseViewController *)arg1;
- (_Bool)isPartiallyVisible:(UIViewController *)arg1;
- (struct CGRect)getViewFrame;
- (UIView *)recipientBar;
@end

