//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCNComposerCancelable.h"

@interface SCComposerCancelableRequestToken : NSObject <SCNComposerCancelable>
{
    id <SCHTTPRequestToken> _requestToken;
}

- (void).cxx_destruct;
- (void)cancel;
- (id)initWithRequestToken:(id)arg1;

@end

