//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSAttributedString, NSString, SCNetworkImage;

@interface SCCognacUpdateMessageViewModel : NSObject <NSCopying>
{
    unsigned long long _subtype;
    NSAttributedString *_text_actionText;
    NSAttributedString *_textAndAccessory_titleText;
    NSAttributedString *_textAndAccessory_actionText;
    NSString *_textAndAccessory_buttonText;
    SCNetworkImage *_textAndAccessory_iconImage;
}

+ (id)textWithActionText:(id)arg1;
+ (id)textAndAccessoryWithTitleText:(id)arg1 actionText:(id)arg2 buttonText:(id)arg3 iconImage:(id)arg4;
- (void).cxx_destruct;
- (void)matchText:(CDUnknownBlockType)arg1 textAndAccessory:(CDUnknownBlockType)arg2;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

