//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface SCContextAppListCardUpdateResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *removedAppIdsArray; // @dynamic removedAppIdsArray;
@property(readonly, nonatomic) unsigned long long removedAppIdsArray_Count; // @dynamic removedAppIdsArray_Count;
@property(retain, nonatomic) NSMutableArray *updatedAppsArray; // @dynamic updatedAppsArray;
@property(readonly, nonatomic) unsigned long long updatedAppsArray_Count; // @dynamic updatedAppsArray_Count;

@end

