//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCActionHandling.h"
#import "SCCognacChatDockLongPressGestureHandlerDelegate.h"

@class NSString, SCCognacBlizzardEventLoggingController, SCCognacChatDockLongPressGestureHandler, SCCognacDataStorage;

@interface SCCognacChatDockActionHandler : NSObject <SCCognacChatDockLongPressGestureHandlerDelegate, SCActionHandling>
{
    id <SCGroupManager> _groupManager;
    SCCognacBlizzardEventLoggingController *_eventLoggingController;
    SCCognacDataStorage *_dataStorage;
    id <SCCognacChatDockAppPresenting> _appPresenter;
    id <SCCognacChatDockAnimationBaseViewProvider> _baseViewProvider;
    SCCognacChatDockLongPressGestureHandler *_longPressGestureHandler;
}

@property(readonly, nonatomic) SCCognacChatDockLongPressGestureHandler *longPressGestureHandler; // @synthesize longPressGestureHandler=_longPressGestureHandler;
@property(readonly, nonatomic) id <SCGroupManager> groupManager; // @synthesize groupManager=_groupManager;
@property(readonly, nonatomic) SCCognacBlizzardEventLoggingController *eventLoggingController; // @synthesize eventLoggingController=_eventLoggingController;
- (void).cxx_destruct;
- (void)didTapOnCognacMessageViewButton:(id)arg1;
- (void)_openAppWithAppInstance:(id)arg1 context:(unsigned long long)arg2;
- (void)chatDockLongPressGestureHandler:(id)arg1 didHideAppInstance:(id)arg2;
- (_Bool)handleActionWithSender:(id)arg1 actionModel:(id)arg2 fromSourceView:(id)arg3;
- (id)initWithPresentingViewController:(id)arg1 appPresenter:(id)arg2 baseViewProvider:(id)arg3 dataStorage:(id)arg4 dataProvider:(id)arg5 serviceCoordinator:(id)arg6 messageHandler:(id)arg7 snapchatterService:(id)arg8 groupManager:(id)arg9 eventLoggingController:(id)arg10;
- (void)logChatDockRemoveEventWithAppInstance:(id)arg1;
- (void)_logChatDockEventWithEventName:(id)arg1 appInstance:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

