//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SCCognacTargetingGpuInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *rendererName; // @dynamic rendererName;
@property(copy, nonatomic) NSString *venderName; // @dynamic venderName;
@property(copy, nonatomic) NSString *version; // @dynamic version;

@end

