//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCCognacOperaSession.h"
#import "SCCognacSettingsListViewControllerAudioDelegate.h"
#import "SCCognacSettingsListViewControllerDismissDelegate.h"
#import "SCCognacSwipeTransitionPresenterDelegate.h"

@class NSString, SCCognacAppViewLifeCycleListenerAnnouncer, SCCognacOperaDataSource, SCCognacSettingsListViewController, SCCognacSwipeTransitionPresenter, SCOperaViewController;

@interface SCCognacOperaSettingsSession : NSObject <SCCognacSwipeTransitionPresenterDelegate, SCCognacSettingsListViewControllerAudioDelegate, SCCognacSettingsListViewControllerDismissDelegate, SCCognacOperaSession>
{
    SCCognacSettingsListViewController *_settingsVC;
    SCCognacSwipeTransitionPresenter *_presenter;
    SCOperaViewController *_operaVC;
    SCCognacOperaDataSource *_dataSource;
    SCCognacAppViewLifeCycleListenerAnnouncer *_viewLifeCycleAnnouncer;
}

+ (id)registeredEventsForOperaSession;
@property(retain, nonatomic) SCCognacAppViewLifeCycleListenerAnnouncer *viewLifeCycleAnnouncer; // @synthesize viewLifeCycleAnnouncer=_viewLifeCycleAnnouncer;
@property(retain, nonatomic) SCCognacOperaDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak SCOperaViewController *operaVC; // @synthesize operaVC=_operaVC;
- (void).cxx_destruct;
- (void)cognacSwipeTransitionPresenterDidDismiss:(id)arg1;
- (void)settingsListViewControllerDidUpdateAudio:(id)arg1;
- (void)settingsListViewControllerDidDismiss:(id)arg1;
- (id)registeredWVJBHandlerNameToHandler;
- (void)startSession;
- (void)resumeSession;
- (void)pauseSession;
- (void)endSession;
- (void)_presentSettingsPage;
- (void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3;
- (void)logInGameButtonTapEvent:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

