//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSArray, NSString, UIColor;

@interface SCCompositeNetworkImageModel : NSObject <NSCopying, NSCoding>
{
    NSString *_identifier;
    NSArray *_networkImageLayers;
    UIColor *_tintColor;
    UIColor *_replaceAlphaLayerFillColor;
    struct CGSize _originalSize;
    struct CGSize _maxOutputSize;
}

@property(readonly, copy, nonatomic) UIColor *replaceAlphaLayerFillColor; // @synthesize replaceAlphaLayerFillColor=_replaceAlphaLayerFillColor;
@property(readonly, nonatomic) struct CGSize maxOutputSize; // @synthesize maxOutputSize=_maxOutputSize;
@property(readonly, nonatomic) struct CGSize originalSize; // @synthesize originalSize=_originalSize;
@property(readonly, copy, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(readonly, copy, nonatomic) NSArray *networkImageLayers; // @synthesize networkImageLayers=_networkImageLayers;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithIdentifier:(id)arg1 networkImageLayers:(id)arg2 tintColor:(id)arg3 originalSize:(struct CGSize)arg4 maxOutputSize:(struct CGSize)arg5 replaceAlphaLayerFillColor:(id)arg6;
- (id)initWithCoder:(id)arg1;

@end

