//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCComposerActionsFactory : NSObject
{
}

+ (id)actionsWithDocumentActions:(const RepeatedPtrField_a3f87753 *)arg1 jsRuntime:(ObjCppPtrWrapper_6fbac7df)arg2 objectID:(unsigned int)arg3;

@end

