//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCCStorySummaryInfoStoring.h"
#import "SCDataCoordinatorListener.h"

@class NSString, SCLazy;

@interface SCComposerStoriesStorySummaryInfoStore : NSObject <SCDataCoordinatorListener, SCCStorySummaryInfoStoring>
{
    SCLazy *_storiesDataCoordinator;
    CDUnknownBlockType _onUpdateCallback;
}

- (void).cxx_destruct;
- (void)dataCoordinatorDidUpdateWithIdentifier:(id)arg1 dataRequest:(id)arg2;
- (CDUnknownBlockType)onStorySummaryInfosUpdatedWithCallback:(CDUnknownBlockType)arg1;
- (void)getStorySummaryInfosWithCompletion:(CDUnknownBlockType)arg1;
- (long long)pushToComposerMarshaller:(struct SCComposerMarshaller *)arg1;
- (void)dealloc;
- (id)initWithStoriesCoordinator:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

