//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface SCConversationSequenceByParticipant : NSObject <NSCopying>
{
    NSString *_participant;
    unsigned long long _sequence;
}

@property(readonly, nonatomic) unsigned long long sequence; // @synthesize sequence=_sequence;
@property(readonly, copy, nonatomic) NSString *participant; // @synthesize participant=_participant;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithParticipant:(id)arg1 sequence:(unsigned long long)arg2;

@end

