//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView;

@protocol SCCommerceUIPresentationLayer <NSObject>
@property(readonly, nonatomic) __weak UIView *presentedView;
@property(nonatomic) __weak id <SCCommerceUIPresentationLayerDismissalDelegate> delegate;
- (void)dismissAnimationWithCompletion:(void (^)(void))arg1;
- (void)presentAnimationWithCompletion:(void (^)(void))arg1;
- (void)setupToPresentView:(UIView *)arg1 inView:(UIView *)arg2;
@end

