//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCContextIZDataProvider.h"

@class NSString, SCContextIZLocalCTAGenerator, SCExperimentManager, SCLazy, SCMapSnapTokenService, SCQueuePerformer;

@interface SCContextIZDataRepository : NSObject <SCContextIZDataProvider>
{
    SCExperimentManager *_experimentManager;
    id <SCContextV2UserInfoProvider> _userInfoProvider;
    SCContextIZLocalCTAGenerator *_localCTAGenerator;
    id <SCCognacContextGameInfoProviding> _gameInfoProvider;
    SCMapSnapTokenService *_snapTokenService;
    SCQueuePerformer *_performer;
    SCLazy *_cache;
}

+ (void)assembleUserInfoWithProvider:(id)arg1 experimentManager:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
- (void)_makeRequest:(id)arg1 snapIdentity:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_userInfoWithCompletion:(CDUnknownBlockType)arg1;
- (void)_viewerContentInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_viewerCreatorInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_fromCache:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_fromNetwork:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getContextDataWithInfoProvider:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithExperimentManager:(id)arg1 userInfoProvider:(id)arg2 gameInfoProvider:(id)arg3 snapTokenService:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

