//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface SCConversationSnapCaptureInfo : NSObject <NSCopying>
{
    BOOL _cameraType;
    BOOL _orientation;
    NSString *_encryptedGeoData;
    NSString *_countryCode;
    double _captureTimestampInEpochSecs;
}

@property(readonly, nonatomic) double captureTimestampInEpochSecs; // @synthesize captureTimestampInEpochSecs=_captureTimestampInEpochSecs;
@property(readonly, copy, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(readonly, copy, nonatomic) NSString *encryptedGeoData; // @synthesize encryptedGeoData=_encryptedGeoData;
@property(readonly, nonatomic) BOOL orientation; // @synthesize orientation=_orientation;
@property(readonly, nonatomic) BOOL cameraType; // @synthesize cameraType=_cameraType;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCameraType:(BOOL)arg1 orientation:(BOOL)arg2 encryptedGeoData:(id)arg3 countryCode:(id)arg4 captureTimestampInEpochSecs:(double)arg5;

@end

