//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCActiveUserSessionScope, SCNavigationServices, SCServicesExposer, SCSnapTokenServices, SCUserNavStartupCompleteScope;

@interface SCContextUserScopedEntryPoint : SCEntryPoint
{
    SCUserNavStartupCompleteScope *_userNavStartupCompletedScope;
    SCActiveUserSessionScope *_userSessionScope;
    SCSnapTokenServices *_snapTokenServices;
    SCNavigationServices *_navigationServices;
    SCServicesExposer *_contextUserScopedServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *contextUserScopedServicesExposer; // @synthesize contextUserScopedServicesExposer=_contextUserScopedServicesExposer;
@property(nonatomic) __weak SCNavigationServices *navigationServices; // @synthesize navigationServices=_navigationServices;
@property(nonatomic) __weak SCSnapTokenServices *snapTokenServices; // @synthesize snapTokenServices=_snapTokenServices;
@property(nonatomic) __weak SCActiveUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
@property(nonatomic) __weak SCUserNavStartupCompleteScope *userNavStartupCompletedScope; // @synthesize userNavStartupCompletedScope=_userNavStartupCompletedScope;
- (void).cxx_destruct;
- (void)begin;
- (id)getLazyIZDataProvider;

@end

