//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor;

@interface SCCommerceProductColorSelectionManager : NSObject
{
    UIColor *_selectedColor;
}

@property(readonly) UIColor *selectedColor; // @synthesize selectedColor=_selectedColor;
- (void).cxx_destruct;
- (void)selectColor:(id)arg1;
- (id)initWithSelectedColor:(id)arg1;

@end

