//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SCContextV2SocialUnlockFlowDelegate <NSObject>
- (void)socialUnlockFlow:(id <SCContextV2SocialUnlockFlow>)arg1 willDismissContextCardsWithCompletion:(void (^)(void))arg2;
- (void)socialUnlockFlowDidDismissModalContent:(id <SCContextV2SocialUnlockFlow>)arg1;
- (void)socialUnlockFlowWillPresentModalContent:(id <SCContextV2SocialUnlockFlow>)arg1;
@end

