//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ScanHistoryCell.h"

@class SCCompositeNetworkImageModel;

@interface SCCommerceScanHistoryCell : ScanHistoryCell
{
    id <SCCompositeNetworkImageDownloading> _imageDownloader;
    SCCompositeNetworkImageModel *_networkImageModel;
}

- (void).cxx_destruct;
- (void)setupViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 mainLabel:(id)arg3 subLabel:(id)arg4 thirdLabel:(id)arg5 scanSnapshotData:(id)arg6 scanData:(id)arg7 userSession:(id)arg8 imageDownloader:(id)arg9 networkImageModel:(id)arg10;

@end

