//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface SCCPEvent : NSObject
{
    NSDate *_timestamp;
    NSString *_log;
}

- (void).cxx_destruct;
- (id)description;
- (id)initWithLog:(id)arg1;

@end

