//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SCObservable;

@protocol SCCurrentPageTracker <NSObject>
@property(readonly, nonatomic) SCObservable *currentPageEvent;
- (void)startPageWithoutTriggeringLegacyPageView:(NSString *)arg1;
- (void)startTransitionFromPage:(NSString *)arg1 toPage:(NSString *)arg2;
- (void)startPage:(NSString *)arg1;
@end

