//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCAuthenticatedNetworkServices, SCGroupChatStoriesSynchronizerServices, SCServicesExposer, SCStoriesMetricServices, SCUserSessionScope, SCUserStorageServices;

@interface SCCustomStoriesServicesEntryPoint : SCEntryPoint
{
    SCUserSessionScope *_userSessionScope;
    SCUserStorageServices *_userStorageServices;
    SCAuthenticatedNetworkServices *_authenticatedNetworkServices;
    SCStoriesMetricServices *_storiesMetricServices;
    SCGroupChatStoriesSynchronizerServices *_groupChatStoriesSynchronizerService;
    SCServicesExposer *_customStoriesServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *customStoriesServicesExposer; // @synthesize customStoriesServicesExposer=_customStoriesServicesExposer;
@property(nonatomic) __weak SCGroupChatStoriesSynchronizerServices *groupChatStoriesSynchronizerService; // @synthesize groupChatStoriesSynchronizerService=_groupChatStoriesSynchronizerService;
@property(nonatomic) __weak SCStoriesMetricServices *storiesMetricServices; // @synthesize storiesMetricServices=_storiesMetricServices;
@property(nonatomic) __weak SCAuthenticatedNetworkServices *authenticatedNetworkServices; // @synthesize authenticatedNetworkServices=_authenticatedNetworkServices;
@property(nonatomic) __weak SCUserStorageServices *userStorageServices; // @synthesize userStorageServices=_userStorageServices;
@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
- (void).cxx_destruct;
- (id)_createCustomStoriesDataSyncerWithNetworkRequester:(id)arg1;
- (id)_createCustomStoriesDataFetcher;
- (id)_createCustomStoriesDataMutatorWithNetworkRequester:(id)arg1;
- (id)_createCustomStoriesNetworkRequester;
- (void)begin;

@end

