//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCDiscoverFeedPivotsExperimentContext : SCExperimentContext
{
    _Bool _pivotSwipePageEnabled;
}

@property(readonly, nonatomic) _Bool pivotSwipePageEnabled; // @synthesize pivotSwipePageEnabled=_pivotSwipePageEnabled;
- (void)setupParameters;
- (id)experimentName;

@end

