//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "SCActionable.h"
#import "SCViewModelConfigurable.h"

@class NSString, SCAvatarView, SCGradientView, SCLazy, SCNetworkImageView, UIColor, UILabel, UIView;

@interface SCDiscoverFeedOnboardingPublisherTileCell : UICollectionViewCell <SCActionable, SCViewModelConfigurable>
{
    SCNetworkImageView *_backgroundImageView;
    SCNetworkImageView *_logoImageView;
    SCLazy *_selectedImageView;
    UIView *_colorOverlay;
    UILabel *_titleLabel;
    SCGradientView *_titleGradientView;
    SCAvatarView *_avatarView;
    UIColor *_overlayAnimateToColor;
    double _selectedImageViewAnimateToAlpha;
    unsigned long long _logoAnimateToPosition;
    id <SCActionHandling> _actionHandler;
    id _viewModel;
}

+ (struct CGSize)sizeWithViewModel:(id)arg1 constrainedToSize:(struct CGSize)arg2;
@property(retain, nonatomic) id viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) id <SCActionHandling> actionHandler; // @synthesize actionHandler=_actionHandler;
- (void).cxx_destruct;
- (void)_didTap:(id)arg1;
@property(retain, nonatomic) id <SCImageDownloading> imageDownloader;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

