//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "SCAdOwnerProtocol.h"
#import "SCMediaOwnerProtocol.h"
#import "SCPreloadListener.h"
#import "SCTraceEnabled.h"

@class NSArray, NSMutableDictionary, NSMutableSet, NSString, SCQueuePerformer;

@interface SCDiscoverChannels : NSObject <SCPreloadListener, SCTraceEnabled, SCAdOwnerProtocol, SCMediaOwnerProtocol, NSCoding>
{
    NSMutableSet *_unlockedChannels;
    NSMutableDictionary *_unlockedEditions;
    id <SCImageDownloading> _imageDownloader;
    NSArray *_channels;
    SCQueuePerformer *_performer;
}

@property(retain, nonatomic) SCQueuePerformer *performer; // @synthesize performer=_performer;
@property(retain, nonatomic) NSArray *channels; // @synthesize channels=_channels;
@property(nonatomic) __weak id <SCImageDownloading> imageDownloader; // @synthesize imageDownloader=_imageDownloader;
- (void).cxx_destruct;
- (id)unlockedEditionForID:(id)arg1;
- (void)didUnlockEdition:(id)arg1;
- (void)preloadControllerDidLoadFromUserSession;
- (void)preloadController:(id)arg1 preloadModeDidChange:(long long)arg2;
- (id)_allChannels;
- (id)mediaFileNames;
- (id)cacheMediaIds;
- (id)cacheAdIds;
- (id)channelForPublisherUniqueName:(id)arg1;
- (id)channelForPublisherName:(id)arg1;
- (void)_debugPrintChannels;
- (void)_debugPrintSojuChannels:(id)arg1;
- (id)currentSubscribedChannelsId;
- (id)currentChannelIds;
- (id)currentChannelHashes;
- (void)updateWithJSONDictionary:(id)arg1 experimentManager:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)addNetworkObserver;
- (void)didDecodeObject;
- (void)ensureNonNilObjects;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

