//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCDiscoverFeedSingleSubscriptionRequestProcessorDelegate.h"

@class NSMutableSet, NSString, SCLazy, SCQueuePerformer, SCSessionRequestManager;

@interface SCDiscoverFeedSubscriptionRequestsProcessor : NSObject <SCDiscoverFeedSingleSubscriptionRequestProcessorDelegate>
{
    NSString *_currentUserUserId;
    SCSessionRequestManager *_requestManager;
    SCLazy *_snapchatterMutater;
    SCLazy *_snapchatterTracker;
    NSMutableSet *_ongoingSubscriptionRequests;
    SCQueuePerformer *_performer;
}

- (void).cxx_destruct;
- (void)singleSubscriptionRequestProcessorDidFinish:(id)arg1;
- (void)_handleSubscribeAction:(_Bool)arg1 toStoryWithStoryKey:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (void)_handleSubscribeAction:(_Bool)arg1 toSnapchatter:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (void)handleSubscribeAction:(_Bool)arg1 toStoryWithStoryKey:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (void)handleSubscribeAction:(_Bool)arg1 toSnapchatter:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (id)initWithCurrentUserUserId:(id)arg1 requestManager:(id)arg2 snapchatterDataMutater:(id)arg3 snapchatterDataTracker:(id)arg4;

@end

