//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface SCDiscoverFeedQueryParameters : NSObject <NSCopying>
{
    unsigned long long _feedType;
}

@property(readonly, nonatomic) unsigned long long feedType; // @synthesize feedType=_feedType;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFeedType:(unsigned long long)arg1;

@end

