//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCDocObjectActivityMonitor.h"

@class NSString;

@interface SCDocObjectLoggingActivityMonitor : NSObject <SCDocObjectActivityMonitor>
{
    CDUnknownFunctionPointerType _errorLogger;
    id <SCGraphene> _graphene;
}

- (void).cxx_destruct;
- (void)docObjectContextTransactionCommitForChangeRequests:(id)arg1 duration:(double)arg2;
- (void)docObjectContextDidExecutePerformChangesForChangeRequests:(id)arg1 duration:(double)arg2;
- (void)docObjectContextDidDequeueChangesBlockForChangeRequests:(id)arg1 duration:(double)arg2;
- (void)docObjectContextDidFetchForClass:(id)arg1 duration:(double)arg2;
- (void)docObjectContextDidEncounterDiskFull;
- (void)docObjectContextDidEncounterError:(struct Error)arg1 contexts:(id)arg2 fatal:(_Bool)arg3;
- (id)initWithErrorLogger:(CDUnknownFunctionPointerType)arg1 graphene:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

