//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCDocObjectContext : NSObject
{
}

+ (void)setDocObjectCurrentContext:(id)arg1;
+ (id)docObjectCurrentContext;
- (void)setUpdatedObject:(id)arg1 forClass:(Class)arg2 byRowid:(long long)arg3;
- (id)objectForClass:(Class)arg1 byRowid:(long long)arg2 buffer:(const void *)arg3 bufferSize:(unsigned long long)arg4;
- (struct SQLiteConnection *)dataConnection;
- (void)shutdownAsynchronously:(CDUnknownBlockType)arg1;
- (id)observeFetchedResult:(id)arg1 callbackQueue:(id)arg2 changeHandler:(CDUnknownBlockType)arg3;
- (id)observe:(id)arg1 callbackQueue:(id)arg2 changeHandler:(CDUnknownBlockType)arg3;
- (void)performChanges:(CDUnknownBlockType)arg1 completionQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)initWithPath:(id)arg1 options:(CDStruct_69d7cc99)arg2 monitor:(id)arg3;
- (struct ObservableBuilder)fetchObservableForClass:(Class)arg1 observationQueue:(id)arg2;

@end

