//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDictionary, NSString;

@protocol SCDynamicLocaleBundle
- (void)copyLocaleFromPrefetchToCurrentBundleIfNeeded:(NSString *)arg1;
- (_Bool)persistLocaleFiles:(NSDictionary *)arg1 forLocale:(NSString *)arg2 localeURL:(NSString *)arg3;
- (_Bool)isLocaleDownloaded:(NSString *)arg1 locale:(NSString *)arg2;
@end

