//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCCaptionDataProvider.h"
#import "SCUnlockablesControllerListener.h"

@class NSArray, NSString, SCUnlockablesController, SCUserSession;

@interface SCDynamicCaptionDataProvider : NSObject <SCCaptionDataProvider, SCUnlockablesControllerListener>
{
    SCUnlockablesController *_unlockablesController;
    SCUserSession *_userSession;
    NSArray *_availableStyles;
    NSArray *_availableStylesFromMemories;
    NSArray *_availableStylesFromServer;
    double _startTime;
    id <SCCaptionDataProviderUpdateDelegate> delegate;
}

@property(nonatomic) __weak id <SCCaptionDataProviderUpdateDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (id)captionFetcher;
- (void)updateCaptionStylesFromMemories:(id)arg1;
- (long long)indexOfCaptionStyle:(id)arg1;
- (id)findAvailableCaptionStyleByStyleId:(id)arg1;
- (long long)totalNumberOfStyles;
- (id)captionStyleForIndex:(long long)arg1;
- (void)_constructAvailableStyles;
- (void)didUpdatePreviewCaptions:(id)arg1;
- (void)constructDynamicStylesFromUnlockableStyles:(id)arg1;
- (void)startUpdateCaptionDataProvider;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

