//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCDiscoverFeedOperaViewingHandling.h"
#import "SCDiscoverFeedQueryCoordinatingDelegate.h"
#import "SCDynamicLayoutDelegate.h"
#import "SCDynamicLayoutDismissAnimationControllerDelegate.h"
#import "SCEventAnnouncing.h"
#import "SCEventListener.h"
#import "SCPageNameLogging.h"
#import "SCScrollToEndDetectorDelegate.h"
#import "SCSearchQueryResultControllerDelegate.h"
#import "SCShakeToReportDelegate.h"
#import "SIGViewController.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSArray, NSData, NSNumber, NSString, SCDynamicLayoutThemeConfiguration, SCDynamicLayoutTransitionProvider, SCDynamicLayoutView, SCEventListenerAnnouncer, SCScopedAccess, SCScrollToEndDetector, SCSearchQueryResultController, SCUserSession, SIGFooterItem, SIGHeaderItem;

@interface SCDynamicLayoutViewController : UIViewController <UICollectionViewDelegate, SCSearchQueryResultControllerDelegate, SCEventListener, SCDynamicLayoutDelegate, SCScrollToEndDetectorDelegate, UIGestureRecognizerDelegate, UIViewControllerTransitioningDelegate, SCDiscoverFeedQueryCoordinatingDelegate, SCDiscoverFeedOperaViewingHandling, SCDynamicLayoutDismissAnimationControllerDelegate, SCShakeToReportDelegate, SCEventAnnouncing, SCPageNameLogging, SIGViewController>
{
    SCUserSession *_userSession;
    id <SCMainHeaderButtonProvider> _mainHeaderButtonProvider;
    SCSearchQueryResultController *_queryResultController;
    SCEventListenerAnnouncer *_eventAnnouncer;
    id <SCDiscoverFeedActionHandling> _actionHandler;
    id <SCDiscoverFeedDataFetching> _discoverFeedDataFetcher;
    id <SCDiscoverFeedDataMutating> _discoverFeedDataMutator;
    id <SCDynamicLayoutUIBuilding> _dynamicLayoutUIBuilder;
    SCDynamicLayoutTransitionProvider *_transitionProvider;
    SCScrollToEndDetector *_scrollToBottomDetector;
    double _yOffsetBeforeScrolling;
    id <SCPerforming> _performer;
    SCScopedAccess *_sectionsCoordinator;
    id <SCImageDownloading> _imageDownloader;
    id <SCLegacyItemDownloading> _videoDownloader;
    NSArray *_feedTypes;
    NSString *_channelId;
    long long _previousStatusBarStyle;
    SIGHeaderItem *_headerItem;
    SCDynamicLayoutThemeConfiguration *_themeConfiguration;
    NSString *_sectionTitle;
    NSString *_bitmojiAvatarId;
    unsigned long long _pageType;
    _Bool _isLoadingQuery;
    _Bool _isVerticalDismiss;
    _Bool _isPresenting;
    _Bool _isContentLoaded;
    _Bool _isNgsPage;
    id <SCDiscoverFeedSnapAdsSharedInstanceStud> _snapAdsSharedInstance;
    id <SCCurrentPageTracker> _currentPageTracker;
    id <SCDiscoverFeedStoriesPrefetching> _storiesPrefetcher;
    NSNumber *_swipeToShowsStartTime;
    NSData *_badgeMetadata;
    CDUnknownBlockType _leftPageTimer;
    id <SCDynamicLayoutViewControllerDelegate> _delegate;
    SCDynamicLayoutView *_dynamicLayoutView;
}

+ (id)announcerIdentifier;
@property(readonly, nonatomic) SCDynamicLayoutView *dynamicLayoutView; // @synthesize dynamicLayoutView=_dynamicLayoutView;
@property(nonatomic) __weak id <SCDynamicLayoutViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)defaultSubProjectName;
- (id)defaultProjectNameV2;
- (void)viewControllerDismissSelf;
- (_Bool)viewControllerPrefersSelfDismiss;
- (_Bool)shouldDismissViewControllerWhenEnterBackground;
- (void)didCompleteDismissal;
- (void)didCancelDismissal;
- (void)didInitiateDismissal;
- (_Bool)canBeginDismissal;
- (void)_resetScrollPosition;
- (void)_setLeftPageTimer;
- (_Bool)_handleSearchNetworkVideoLoggingEventsToGraphene:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;
- (void)_announcePageOpen;
- (void)_sendQueryWithSource:(id)arg1 queryParameters:(id)arg2;
- (void)_sendPageOpenQueryWithSource:(id)arg1;
- (void)_stopAllVideoPlayback:(id)arg1;
- (void)_restartVideoPlaybackIfNecessary:(id)arg1;
- (void)_resumeAllVideoPlaybackIfNeccesary:(id)arg1;
- (void)_pauseAllVideoPlaybackIfNeccesary:(id)arg1;
- (void)_updateImpressionItems;
- (void)_endPagination;
- (void)_startPaginationForFeedTypeIfNecessary:(unsigned long long)arg1;
- (void)_handleDidStartToDisplayStoryWithIndexPath:(id)arg1;
- (void)_scrollToTopWithAnimation:(_Bool)arg1;
- (void)_logShowsPageReadyIfNecessary;
- (void)didStartToDisplayStoryWithIndexPath:(id)arg1 actionHandler:(id)arg2;
- (void)didTearDownStory;
- (void)didDismissStory;
- (void)didStartToDismissStoryAtIndexPath:(id)arg1 actionHandler:(id)arg2;
- (void)_didDismiss:(_Bool)arg1 withGesture:(long long)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)didTap:(id)arg1;
- (long long)preferredStatusBarStyle;
- (void)didTapBackButton;
- (void)_pullToRefreshTriggered;
- (void)scrollToEndDetector:(id)arg1 scrollViewWillReachEnd:(id)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)discoverQueryCoordinator:(id)arg1 didReceiveServerResponseForQuery:(id)arg2;
- (void)discoverQueryCoordinator:(id)arg1 didFailForQuery:(id)arg2 error:(id)arg3 statusCodeToDisplay:(id)arg4;
- (id)presentingViewControllerForSearchQueryResultController:(id)arg1;
- (void)searchQueryResultController:(id)arg1 willUpdateResultForQuery:(id)arg2 fromQuery:(id)arg3;
- (void)searchQueryResultControllerDidUpdateQueryResult:(id)arg1;
- (void)didTriggerEventWithEventName:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;
- (id)pageViewName;
@property(readonly, nonatomic) SIGHeaderItem *headerItem; // @synthesize headerItem=_headerItem;
- (void)renderAndSendPrefetchQuery;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (void)viewDidLoad;
- (void)cancelStoryPresenting;
- (id)initWithUserSession:(id)arg1 mainHeaderButtonProvider:(id)arg2 discoverFeedDataFetcher:(id)arg3 discoverFeedDataMutator:(id)arg4 dynamicLayoutUIBuilder:(id)arg5 actionHandler:(id)arg6 imageDownloader:(id)arg7 videoDownloader:(id)arg8 transitionProvider:(id)arg9 feedTypes:(id)arg10 channelId:(id)arg11 pageType:(unsigned long long)arg12 sectionTitle:(id)arg13 bitmojiAvatarId:(id)arg14 snapAdsSharedInstance:(id)arg15 currentPageTracker:(id)arg16 storiesPrefetcher:(id)arg17 badgeMetadata:(id)arg18;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) SIGFooterItem *footerItem;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

