//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SCEraseRulesContainerViewModel, SCEraseStatusMessageCardView, UILabel;

@interface SCEraseRulesContainerView : UIView
{
    UILabel *_ruleChangedLabel;
    SCEraseRulesContainerViewModel *_viewModel;
    SCEraseStatusMessageCardView *_cardView;
}

@property(readonly, nonatomic) SCEraseStatusMessageCardView *cardView; // @synthesize cardView=_cardView;
@property(retain, nonatomic) SCEraseRulesContainerViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)_initializeRuleChangedLabel;
- (id)initWithFrame:(struct CGRect)arg1;

@end

