//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCArchiveManager;

@interface SCFetchCaptchaResponseParser : NSObject
{
    SCArchiveManager *_manager;
}

- (void).cxx_destruct;
- (id)_extractCaptchaPrompt:(id)arg1;
- (id)_extractCaptchaId:(id)arg1;
- (id)_extractOrderedCaptchaImages:(id)arg1;
- (void)parseSuccessResponse:(id)arg1 data:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)initWithUnarchiver:(id)arg1;

@end

