//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCLens;

@protocol SCFeatureLensSideButtonUpdateProvider <NSObject>
@property(readonly, nonatomic) _Bool newLensesAvailable;
@property(readonly, nonatomic) SCLens *firstApplicableLens;
- (void)removeListener:(id <SCFeatureLensSideButtonUpdateListener>)arg1;
- (_Bool)addListener:(id <SCFeatureLensSideButtonUpdateListener>)arg1;
@end

