//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCLens, SCLensConfiguration;

@protocol SCFeatureSpectaclesLensFilterInPreviewDelegate <NSObject>
- (void)featureSpectaclesLensFilterInPreview:(id <SCFeatureSpectaclesLensFilterInPreview>)arg1 withAppliedLens:(SCLens *)arg2 lensConfiguration:(SCLensConfiguration *)arg3;
@end

