//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCFeature.h"

#import "SCFeatureGameAttachment.h"

@class NSString;

@interface SCFeatureGameAttachmentImpl : SCFeature <SCFeatureGameAttachment>
{
    NSString *_gameId;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *gameId;
- (id)initWithGameId:(id)arg1;

@end

