//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCEventListener.h"

@class NSDate, NSString;

@interface SCFeedRankingLogger : NSObject <SCEventListener>
{
    id <SCPerforming> _performer;
    NSDate *_pageOpenTime;
    NSString *_sessionId;
    NSString *_rankingId;
    NSString *_serverRankingId;
    NSString *_rankingModelId;
    NSString *_subpageName;
}

+ (id)sharedInstance;
@property(readonly) NSString *subpageName; // @synthesize subpageName=_subpageName;
@property(readonly) NSString *rankingModelId; // @synthesize rankingModelId=_rankingModelId;
@property(readonly) NSString *serverRankingId; // @synthesize serverRankingId=_serverRankingId;
@property(readonly) NSString *rankingId; // @synthesize rankingId=_rankingId;
- (void).cxx_destruct;
- (void)didTriggerEventWithEventName:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;
- (void)didLeaveFriendFeedTowardsCameraAtTime:(id)arg1;
- (void)_logFeedPageViewForViewTime:(double)arg1;
- (void)_logFeedPageOpen;
- (void)_didOpenFeedAtTimestamp:(id)arg1;
- (void)didOpenFeedAtTimestamp:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

