//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SCFeedLogger : NSObject
{
    NSMutableDictionary *_cellViewPositions;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (long long)getCellViewPositionWithChatId:(id)arg1;
- (void)removeCellViewPositionWithChatId:(id)arg1;
- (void)logCellViewPosition:(long long)arg1 chatId:(id)arg2;
- (id)init;

@end

