//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSString, SCActionModel, SCAvatarContainerViewModel, SCCornerRadii, SCFriendsFeedComponentViewRightButtonViewModel, SCFriendsFeedFriendmojiViewModel, SCFriendsFeedIcon, UIFont;

@protocol SCFeedComponentViewModel <NSObject>
- (_Bool)isPinned;
- (_Bool)showOfficialBadge;
- (SCFriendsFeedComponentViewRightButtonViewModel *)rightButtonViewModel;
- (unsigned long long)typingAnimationState;
- (SCActionModel *)animationModel;
- (SCCornerRadii *)cornerRadii;
- (SCFriendsFeedFriendmojiViewModel *)sublabelFriendmojiViewModel;
- (SCFriendsFeedFriendmojiViewModel *)friendmojiViewModel;
- (SCAvatarContainerViewModel *)friendsFeedAvatarViewModel;
- (SCFriendsFeedIcon *)feedIcon;
- (UIFont *)separatorFont;
- (NSString *)substringToTruncateInSubLabel;
- (NSAttributedString *)attributedSublabelText;
- (NSAttributedString *)displayNameAttributedStringWithWidth:(double)arg1;
- (NSString *)identifier;
@end

