//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol SCFeatureWidenedFOV
@property(readonly, nonatomic) double previewVerticalOffset;
- (struct UIEdgeInsets)safeAreaInsetsWithExistingInsets:(struct UIEdgeInsets)arg1;
- (struct UIEdgeInsets)safeAreaInsets;
- (struct CGRect)maxMediaAreaFrame;
- (_Bool)isFeatureEnabledAndSupported;
@end

