//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SCFileIOErrorMetric : NSObject
{
    unsigned long long _type;
    unsigned long long _fileIOCount;
    unsigned long long _fileIOErrorCount;
    NSMutableDictionary *_fileIOErrorCountByCode;
}

@property(readonly, copy, nonatomic) NSMutableDictionary *fileIOErrorCountByCode; // @synthesize fileIOErrorCountByCode=_fileIOErrorCountByCode;
@property(readonly, nonatomic) unsigned long long fileIOErrorCount; // @synthesize fileIOErrorCount=_fileIOErrorCount;
@property(readonly, nonatomic) unsigned long long fileIOCount; // @synthesize fileIOCount=_fileIOCount;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (long long)compare:(id)arg1;
- (id)_errorDescription:(id)arg1;
- (id)topErrorCodesWithLimit:(unsigned long long)arg1;
- (void)logFileIOWithError:(id)arg1;
- (id)initWithFileIOType:(unsigned long long)arg1 fileIOCount:(unsigned long long)arg2 fileIOErrorCount:(unsigned long long)arg3;

@end

