//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SCFrameSource <NSObject>
@property(nonatomic) _Bool didProcessFirstFrame;
@property(nonatomic) long long renderOrientation;
@property(nonatomic) double rate;
@property(nonatomic) CDStruct_1b6d18a9 itemTimeStartOffset;
- (_Bool)hasNewPixelBufferForItemTime:(CDStruct_1b6d18a9)arg1;
- (struct __CVBuffer *)acquirePixelBufferForItemTime:(CDStruct_1b6d18a9)arg1 itemTimeForDisplay:(CDStruct_1b6d18a9 *)arg2;
- (CDStruct_1b6d18a9)itemTimeForHostTime:(double)arg1;
- (CDStruct_e83c9415)itemTimeRange;
- (CDStruct_1b6d18a9)duration;
- (void)cancelReading;
- (void)startReading;
- (_Bool)isSourceReady;
@end

