//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, SCQueuePerformer;

@interface SCFriendsFeedMessagingDataTypingAnimationStateManager : NSObject
{
    NSDictionary *_typingAnimationStates;
    NSDictionary *_typingParticipants;
    SCQueuePerformer *_performer;
}

- (void).cxx_destruct;
- (unsigned long long)_typingStateFromTypingParticipants:(id)arg1;
- (void)updateTypingAnimationStatesForTypingParticipants:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

@end

