//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCLazy;

@interface SCFriendsFeedUFSServices : NSObject
{
    SCLazy *_friendsFeedUFSDataCoordinator;
}

@property(readonly, nonatomic) SCLazy *friendsFeedUFSDataCoordinator; // @synthesize friendsFeedUFSDataCoordinator=_friendsFeedUFSDataCoordinator;
- (void).cxx_destruct;
- (id)initWithFriendsFeedUFSDataCoordinator:(id)arg1;

@end

