//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class SCFriendsFeedChatUpdateContent, SCFriendsFeedCognacUpdateContent, SCFriendsFeedGroupUpdateContent;

@interface SCFriendsFeedUpdateContent : NSObject <NSCopying>
{
    unsigned long long _subtype;
    SCFriendsFeedCognacUpdateContent *_cognacUpdateContent_cognacUpdateContent;
    SCFriendsFeedGroupUpdateContent *_groupUpdateContent_groupUpdateContent;
    SCFriendsFeedChatUpdateContent *_chatUpdateContent_chatUpdateContent;
}

+ (id)groupUpdateContentWithGroupUpdateContent:(id)arg1;
+ (id)cognacUpdateContentWithCognacUpdateContent:(id)arg1;
+ (id)chatUpdateContentWithChatUpdateContent:(id)arg1;
- (void).cxx_destruct;
- (void)matchCognacUpdateContent:(CDUnknownBlockType)arg1 groupUpdateContent:(CDUnknownBlockType)arg2 chatUpdateContent:(CDUnknownBlockType)arg3;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)asChatUpdateContent;
- (id)asGroupUpdateContent;
- (id)asCognacUpdateContent;
- (unsigned long long)subtype;
- (_Bool)isSameSubtype:(id)arg1;
- (id)xLogObjectInfo;

@end

