//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EGOCipherManagedKey, NSString, SCQueuePerformer;

@interface SCGalleryEGOCipherKeyProvider : NSObject
{
    EGOCipherManagedKey *_masterKeyOld;
    EGOCipherManagedKey *_masterKeyAvoidKeyDerivation;
    SCQueuePerformer *_performer;
    NSString *_userId;
    _Bool _accessKeychainSucceededAndKeysAvailable;
    _Bool _applicationObserved;
    double _backOffTime;
    id <SCGalleryEGOCipherKeyProviderDelegate> _delegate;
}

@property(nonatomic) __weak id <SCGalleryEGOCipherKeyProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_announceKeysAvailableAndUnobserve;
- (_Bool)_attemptToCreateAndPersistNewKey;
- (void)_scheduleNextRetrievalAttempt;
- (void)_searchKeysAndUpdate;
- (void)_retrieveMasterKeysFromKeychainWhenAllowed:(_Bool)arg1;
- (void)_unobserveApplication;
- (void)_observeApplication;
- (void)_applicationProtectedDataDidBecomeAvailable:(id)arg1;
- (id)initWithUserId:(id)arg1;

@end

