//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSString, UICollectionView;

@protocol SCGalleryCollectionViewCustomizing <UICollectionViewDataSource, UICollectionViewDelegate>
- (void)reloadCollectionView;
- (NSString *)cellReuseIdentifierForSection:(long long)arg1;
- (void)registerSupplementaryViewsForCollectionView:(UICollectionView *)arg1;
- (void)registerCellsForCollectionView:(UICollectionView *)arg1;
@end

