//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCChatLocationSharingControllerDataListener.h"
#import "SCSectionDataProviding.h"
#import "SCUpdateListener.h"

@class NSObject<NSCopying>, NSString, SCChatLocationSharingController, SCEmbeddedMapViewLoggingSession, SCEventListenerAnnouncer, SCGroupUnifiedProfileDataSource, SCUserSession;

@interface SCGroupProfileMapSectionV2DataProvider : NSObject <SCUpdateListener, SCChatLocationSharingControllerDataListener, SCSectionDataProviding>
{
    SCEventListenerAnnouncer *_eventAnnouncer;
    SCUserSession *_userSession;
    SCEmbeddedMapViewLoggingSession *_mapLoggingSession;
    SCGroupUnifiedProfileDataSource *_dataSource;
    SCChatLocationSharingController *_locationSharingController;
    id <SCSectionDataProvidingDelegate> _dataProviderDelegate;
    id <SCPerforming> _updateQueuePerformer;
    NSObject<NSCopying> *_sectionDataModel;
}

+ (id)announcerIdentifier;
@property(retain, nonatomic) SCChatLocationSharingController *locationSharingController; // @synthesize locationSharingController=_locationSharingController;
@property(copy, nonatomic) NSObject<NSCopying> *sectionDataModel; // @synthesize sectionDataModel=_sectionDataModel;
@property(retain, nonatomic) id <SCPerforming> updateQueuePerformer; // @synthesize updateQueuePerformer=_updateQueuePerformer;
@property(nonatomic) __weak id <SCSectionDataProvidingDelegate> dataProviderDelegate; // @synthesize dataProviderDelegate=_dataProviderDelegate;
- (void).cxx_destruct;
- (void)chatLocationSharingController:(id)arg1 didUpdateCellTypes:(id)arg2 shouldAnimate:(_Bool)arg3;
- (unsigned long long)_shareListCellType;
- (id)_getContentViewModelForIndexPath:(id)arg1;
- (void)didUpdateWithAnnouncerIdentifier:(id)arg1;
- (void)_configureMapCardCell:(id)arg1;
- (id)configurationBlocksByReuseIdentifier;
- (unsigned long long)numberOfItemsInSection:(unsigned long long)arg1;
- (id)contentCellClassesByReuseIdentifier;
- (id)containerCellViewModelsForIndexPaths:(id)arg1;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (id)initWithUserSession:(id)arg1 dataSource:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

