//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCActionHandling.h"

@class NSString, SCExperimentManager, SCMaxGroupSizeAlertView, UIViewController;

@interface SCGroupLinkCreationAndDeletionActionHandler : NSObject <SCActionHandling>
{
    id <SCGroupManager> _groupManager;
    id <SCChatGroup> _baseGroup;
    SCMaxGroupSizeAlertView *_maxGroupSizeAlertView;
    SCExperimentManager *_experimentManager;
    UIViewController *_presentingViewController;
}

@property(nonatomic) __weak UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
- (void).cxx_destruct;
- (void)_copyToClipboardWithDeepLinkPayload:(id)arg1;
- (void)_presentShareSheetWithDeepLinkPayload:(id)arg1;
- (void)_handleDeleteInviteLinksToGroup;
- (void)_handleCreateInviteLinkToGroup;
- (_Bool)handleActionWithSender:(id)arg1 actionModel:(id)arg2 fromSourceView:(id)arg3;
- (void)setBaseGroupWithGroupId:(id)arg1;
- (id)initWithGroupManager:(id)arg1 baseGroup:(id)arg2 experimentManager:(id)arg3 presentingViewController:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

