//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCGroupsDataRemoteFetching.h"

@class SCSessionRequestManager;

@interface SCGroupsDataRemoteFetcher : NSObject <SCGroupsDataRemoteFetching>
{
    id <SCGroupManager> _groupManager;
    SCSessionRequestManager *_requestManager;
}

- (void).cxx_destruct;
- (void)_handleGroupsResponse:(id)arg1;
- (void)fetchGroupsFromServer:(CDUnknownBlockType)arg1;
- (id)initWithGroupManager:(id)arg1 requestManager:(id)arg2;

@end

