//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SCGrpcServiceOptions : NSObject
{
    _Bool _setUserAgent;
    _Bool _retryEnabled;
    int _compressAlgorithm;
    int _keepaliveInterval;
    int _keepaliveTimeout;
    NSString *_serverAddress;
}

@property(nonatomic) _Bool retryEnabled; // @synthesize retryEnabled=_retryEnabled;
@property(nonatomic) int keepaliveTimeout; // @synthesize keepaliveTimeout=_keepaliveTimeout;
@property(nonatomic) int keepaliveInterval; // @synthesize keepaliveInterval=_keepaliveInterval;
@property(nonatomic) int compressAlgorithm; // @synthesize compressAlgorithm=_compressAlgorithm;
@property(nonatomic) _Bool setUserAgent; // @synthesize setUserAgent=_setUserAgent;
@property(readonly, nonatomic) NSString *serverAddress; // @synthesize serverAddress=_serverAddress;
- (void).cxx_destruct;
- (id)initWithServerAddress:(id)arg1;

@end

