//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCComposerMarshallableObject.h"

@class NSNumber, NSString;

@interface SCImpalaPublisherProfilePlayerOverlayViewModel : SCComposerMarshallableObject
{
    NSString *_episodeId;
    NSString *_logoUrl;
    NSString *_publisherDescription;
    NSString *_buttonText;
    NSString *_callToActionText;
    NSNumber *_disableGradient;
}

@property(retain, nonatomic) NSNumber *disableGradient; // @synthesize disableGradient=_disableGradient;
@property(copy, nonatomic) NSString *callToActionText; // @synthesize callToActionText=_callToActionText;
@property(copy, nonatomic) NSString *buttonText; // @synthesize buttonText=_buttonText;
@property(copy, nonatomic) NSString *publisherDescription; // @synthesize publisherDescription=_publisherDescription;
@property(copy, nonatomic) NSString *logoUrl; // @synthesize logoUrl=_logoUrl;
@property(copy, nonatomic) NSString *episodeId; // @synthesize episodeId=_episodeId;
- (void).cxx_destruct;
- (long long)pushToComposerMarshaller:(struct SCComposerMarshaller *)arg1;
- (id)initWithEpisodeId:(id)arg1 logoUrl:(id)arg2 publisherDescription:(id)arg3 buttonText:(id)arg4 callToActionText:(id)arg5;
- (id)initWithEpisodeId:(id)arg1 logoUrl:(id)arg2 publisherDescription:(id)arg3 buttonText:(id)arg4 callToActionText:(id)arg5 disableGradient:(id)arg6;

@end

