//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCJobScheduler.h"

@class SCApplicationState, SCJobExecutor, SCJobQueue, SCJobStatusTracker, SCQueuePerformer;

@interface SCJobSchedulingCoordinator : NSObject <SCJobScheduler>
{
    SCJobQueue *_jobQueue;
    SCJobExecutor *_jobExecutor;
    SCQueuePerformer *_queuePerformer;
    SCJobStatusTracker *_jobStatusTracker;
    long long _connectivity;
    SCApplicationState *_applicationState;
    long long _batteryState;
    float _batteryLevel;
    double _startTime;
    _Bool _backgroundSystemWakeUp;
    _Bool _scheduleWhenBatteryStateChange;
    _Bool _scheduleWhenAppStateChange;
    _Bool _scheduleWhenConnectivityChange;
    _Bool _scheduleWhenProvidersSet;
}

- (void).cxx_destruct;
- (void)triggerBackgroundPrefetch:(id)arg1;
- (void)_deleteJob:(id)arg1 jobConfig:(id)arg2 deletionReason:(long long)arg3 jobStateUpdate:(CDUnknownBlockType)arg4;
- (void)_onDeleteJobFinish:(id)arg1 jobConfig:(id)arg2 deletionReason:(long long)arg3 error:(id)arg4 jobStateUpdate:(CDUnknownBlockType)arg5;
- (void)_scheduleFutureJob:(id)arg1 scope:(int)arg2 delay:(double)arg3;
- (void)_onUpdateJobScheduledTimeFinish:(id)arg1 jobConfig:(id)arg2 rescheduleDelay:(double)arg3 error:(id)arg4 jobStateUpdate:(CDUnknownBlockType)arg5;
- (void)_onJobExecutionCompleteWithJobInfo:(id)arg1 jobConfig:(id)arg2 jobResult:(long long)arg3 jobStartedTime:(double)arg4 error:(id)arg5;
- (unsigned long long)_shouldExecuteJobWithJobInfo:(id)arg1 jobConfig:(id)arg2;
- (void)_scheduleSystemJobs;
- (void)_scheduleUserJobs;
- (void)_scheduleJobs;
- (void)_scheduleJobs:(id)arg1 jobScheduledCallback:(CDUnknownBlockType)arg2;
- (void)_scheduleJobs:(id)arg1;
- (void)_scheduleJob:(id)arg1 scope:(int)arg2;
- (void)_onEnqueueJobCompleteWithInfo:(id)arg1 scope:(int)arg2 error:(id)arg3 queue:(id)arg4 onComplete:(CDUnknownBlockType)arg5;
- (void)systemJobProvidersDidChange;
- (void)userJobProvidersDidChange;
- (void)batteryStateDidChange:(long long)arg1 batteryLevel:(float)arg2;
- (void)appStateDidChange;
- (void)networkConnectivityStatusDidChange:(long long)arg1;
- (void)scheduleBatchJob:(CDUnknownBlockType)arg1 batchStartedCallback:(CDUnknownBlockType)arg2 batchCompletionCallback:(CDUnknownBlockType)arg3;
- (void)jobExistsWithTypeIdentifier:(id)arg1 jobIdentifier:(id)arg2 jobScope:(int)arg3 queue:(id)arg4 onComplete:(CDUnknownBlockType)arg5;
- (void)cancelJobWithTypeIdentifier:(id)arg1 jobIdentifier:(id)arg2 jobScope:(int)arg3 queue:(id)arg4 onComplete:(CDUnknownBlockType)arg5;
- (void)submitJobWithInput:(id)arg1 jobConfig:(id)arg2 queue:(id)arg3 onComplete:(CDUnknownBlockType)arg4;
- (id)initWithJobQueue:(id)arg1 jobExecutor:(id)arg2 connectivity:(long long)arg3 applicationState:(id)arg4 batteryState:(long long)arg5 batteryLevel:(float)arg6 queuePerformer:(id)arg7 scheduleWhenBatteryStateChange:(_Bool)arg8 scheduleWhenAppStateChange:(_Bool)arg9 scheduleWhenConnectivityChange:(_Bool)arg10 scheduleWhenProvidersSet:(_Bool)arg11;

@end

