//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCLazyLoadingProxy.h"

@interface SCLazyFeatureProxy : SCLazyLoadingProxy
{
    long long _initializationPriority;
}

@property(readonly, nonatomic) long long initializationPriority; // @synthesize initializationPriority=_initializationPriority;
- (id)initWithInitializationBlock:(CDUnknownBlockType)arg1 priority:(long long)arg2;

@end

