//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCLagunaSettingsTableViewCell.h"

@class UIImageView, UIView;

@interface SCLagunaSettingsColorIndicatorCell : SCLagunaSettingsTableViewCell
{
    UIView *_indicatorContainer;
    UIImageView *_colorIndicator;
}

+ (id)reuseIdentifier;
- (void).cxx_destruct;
- (void)setIndicatorColor:(unsigned long long)arg1 isEnabled:(_Bool)arg2;
- (void)setCellStyle:(unsigned long long)arg1 indicatorType:(unsigned long long)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

