//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, UIViewController;

@protocol SCLensLiveLensPreviewCameraPresenterProtocol <NSObject>
@property(nonatomic) __weak id <SCLensLiveLensPreviewCameraPresenterDelegate> delegate;
- (void)updateLenses:(NSArray *)arg1;
- (void)dismissCameraViewControllerAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (void)presentCameraViewControllerFromViewController:(UIViewController *)arg1 withLenses:(NSArray *)arg2 replyParameters:(id <SCLensLiveLensPreviewReplyParameters>)arg3;
@end

