//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCLens;

@protocol SCLensLiveLensPreviewCameraPresenterDelegate <NSObject>
- (void)lensCameraPresenter:(id <SCLensLiveLensPreviewCameraPresenterProtocol>)arg1 didUseLens:(SCLens *)arg2;
- (void)lensCameraPresenterDidComplete:(id <SCLensLiveLensPreviewCameraPresenterProtocol>)arg1;
@end

