//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCEventListener.h"
#import "SCLensCreatorSubscriptionProviding.h"

@class NSLock, NSString, SCCreatorSettingsDataFetcher, SCCreatorSettingsDataMutator, SCCreatorSettingsDataTracker;

@interface SCLensCreatorSubscriptionProvider : NSObject <SCEventListener, SCLensCreatorSubscriptionProviding>
{
    id <SCLensCreatorSubscriptionUpdateHandler> _updateHandler;
    NSLock *_updateHandlerLock;
    SCCreatorSettingsDataFetcher *_creatorSettingsFetcher;
    SCCreatorSettingsDataMutator *_creatorSettingsMutator;
    SCCreatorSettingsDataTracker *_creatorSettingsTracker;
}

- (void).cxx_destruct;
- (void)_updateSubscribed:(_Bool)arg1 onCreatorId:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)didTriggerEventWithEventName:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;
- (void)unsubscribeFromCreatorWithId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)subscribeToCreatorWithId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)isSubscribedToCreatorWithId:(id)arg1;
- (id)updateHandler;
- (void)setUpdateHandler:(id)arg1;
- (void)dealloc;
- (id)initWithCreatorSettingsFetcher:(id)arg1 creatorSettingsMutator:(id)arg2 creatorSettingsTracker:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

