//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCLensInfoController.h"

@class FBKVOController, NSString, SCGrowingButton, SCLensInfoPresenterV1, SCPreferences, UILabel, UIView;

@interface SCLensInfoControllerV1Impl : NSObject <SCLensInfoController>
{
    _Bool _observing;
    UIView *_view;
    UIView *_hidableContainer;
    UILabel *_dateLabel;
    SCGrowingButton *_infoButton;
    SCLensInfoPresenterV1 *_lensInfoPresenter;
    SCPreferences *_userPreferences;
    FBKVOController *_kvoController;
    id <SCLensInfoViewModelProtocol> _lensInfoViewModel;
}

@property(nonatomic) _Bool observing; // @synthesize observing=_observing;
@property(retain, nonatomic) id <SCLensInfoViewModelProtocol> lensInfoViewModel; // @synthesize lensInfoViewModel=_lensInfoViewModel;
@property(retain, nonatomic) FBKVOController *kvoController; // @synthesize kvoController=_kvoController;
@property(retain, nonatomic) SCPreferences *userPreferences; // @synthesize userPreferences=_userPreferences;
@property(retain, nonatomic) SCLensInfoPresenterV1 *lensInfoPresenter; // @synthesize lensInfoPresenter=_lensInfoPresenter;
@property(retain, nonatomic) SCGrowingButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) UIView *hidableContainer; // @synthesize hidableContainer=_hidableContainer;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
- (void).cxx_destruct;
- (void)createDataLabel;
- (void)addLensInfoCollectionView;
- (void)createHidableContainer;
- (void)createInfoButton;
- (void)unobserveAll;
- (void)observeValueChanging;
- (void)updateLensInfoVisibility:(id)arg1;
- (_Bool)isPointInsideButton:(struct CGPoint)arg1;
- (void)hide;
- (void)show;
- (void)dealloc;
- (id)initWithUserUserPreferences:(id)arg1 lensInfoViewModel:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

