//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol SCLensDataProviderRegistryUpdatable <NSObject>
@property(readonly, nonatomic) long long cameraViewType;
@property(readonly, nonatomic) id <SCLensCameraScreenDataProviderProtocol> currentLensDataProvider;
- (void)removeUpdateListener:(id <SCLensDataProviderRegistryUpdateListener>)arg1;
- (_Bool)addUpdateListener:(id <SCLensDataProviderRegistryUpdateListener>)arg1;
- (void)updateLensDataProviderWithCameraType:(long long)arg1 bitmojiLinked:(_Bool)arg2 friendBitmojiLinked:(_Bool)arg3 ownerContextDescription:(NSString *)arg4;
- (void)updateLensDataProvider:(id <SCLensCameraScreenDataProviderProtocol>)arg1;
@end

