//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCExperimentContext.h"

@class NSString;

@interface SCLensDeviceDependentRegressorExperimentContext : SCExperimentContext
{
    _Bool _useResourceManager;
    NSString *_trackingResourcesTag;
    NSString *_trackingResourcesChecksum;
}

@property(readonly, nonatomic) _Bool useResourceManager; // @synthesize useResourceManager=_useResourceManager;
@property(readonly, nonatomic) NSString *trackingResourcesChecksum; // @synthesize trackingResourcesChecksum=_trackingResourcesChecksum;
@property(readonly, nonatomic) NSString *trackingResourcesTag; // @synthesize trackingResourcesTag=_trackingResourcesTag;
- (void).cxx_destruct;
- (void)setupParameters;
- (id)experimentName;

@end

