//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCLensExplorerBaseLensCollectionViewCell.h"

@class SCLensExplorerBlurredImageView;

@interface SCLensExplorerLensWithNoPreviewCollectionViewCell : SCLensExplorerBaseLensCollectionViewCell
{
    SCLensExplorerBlurredImageView *_blurredImageView;
}

- (void).cxx_destruct;
- (struct CGRect)iconViewFrame;
- (void)_prepareBlurView;
- (void)setViewModel:(id)arg1;

@end

