//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCLeaveGroupAlertDelegate.h"

@class NSString, SCLazy;

@interface SCLeaveGroupAlertViewController : NSObject <SCLeaveGroupAlertDelegate>
{
    SCLazy *_leaveGroupAlertView;
    SCLazy *_groupsDataMutator;
    SCLazy *_groupsDataFetcher;
}

- (void).cxx_destruct;
- (void)didPressLeaveGroup:(id)arg1;
- (void)_didPressLeaveGroupButtonForGroup:(id)arg1 inAlertFlow:(id)arg2;
- (void)presentLeaveGroupAlertViewForGroupId:(id)arg1 inAlertFlow:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

