//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCAddFriendsMySnapcodeImageProviding.h"

@class NSObject<OS_dispatch_queue>, SCSnapcodeView, SCUserSession, UIImage;

@interface SCLegacyAddFriendsMySnapcodeImageProvider : NSObject <SCAddFriendsMySnapcodeImageProviding>
{
    SCUserSession *_userSession;
    UIImage *_snapcodeImage;
    SCSnapcodeView *_snapcodeView;
    NSObject<OS_dispatch_queue> *_completionQueue;
    CDUnknownBlockType _completionHandler;
}

- (void).cxx_destruct;
- (void)_cleanUp;
- (id)_generateSnapcodeImageFromView:(id)arg1;
- (void)generateMySnapcodeImageWithCompletionQueue:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)initWithUserSession:(id)arg1;

@end

