//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBundle, NSString;

@protocol SCLocaleBundleProvider <NSObject>
@property(readonly, nonatomic) id <SCLocaleBundlePlistOperator> plistOperator;
@property(readonly, nonatomic) _Bool isLocalePrefeched;
@property(readonly, nonatomic) _Bool isCurrentLocaleDownloaded;
@property(readonly, nonatomic) NSBundle *localeBundle;
@property(readonly, copy, nonatomic) NSString *currentLocaleURL;
@property(readonly, copy, nonatomic) NSString *prefetchBundlePath;
@property(readonly, copy, nonatomic) NSString *currentBundlePath;
- (void)recheckLocaleBundle;
@end

