//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCLongformShowAdIntegrationExperimentContext : SCExperimentContext
{
    long long _loadingSpinnerTimeoutInMillis;
}

@property(readonly, nonatomic) long long loadingSpinnerTimeoutInMillis; // @synthesize loadingSpinnerTimeoutInMillis=_loadingSpinnerTimeoutInMillis;
- (void)setupParameters;
- (id)experimentName;

@end

