//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCLocationStickerSubscreenDelegate.h"
#import "SCVenueFeedbackViewControllerDelegate.h"

@class NSString, SCLocationStickerSubscreenViewController, SCMapTrayInteractionController;

@interface SCLocationStickerPresenterViewController : UIViewController <SCVenueFeedbackViewControllerDelegate, SCLocationStickerSubscreenDelegate>
{
    SCMapTrayInteractionController *_trayController;
    SCLocationStickerSubscreenViewController *_subscreenVC;
}

- (void).cxx_destruct;
- (void)venueFeedbackViewControllerWantsToDismiss:(id)arg1;
- (void)subscreenWantsToDismiss;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 venueTapped:(CDUnknownBlockType)arg2 reportVenueTapped:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

