//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCLocationSharingServiceLogger : NSObject
{
}

+ (void)locationSharingPreferencesUpdated:(id)arg1 onboarded:(_Bool)arg2 ghostModeDuration:(double)arg3 updateType:(long long)arg4 previousPreferences:(id)arg5 source:(long long)arg6;
+ (void)locationSharingPreferencesFetchedWithFetchType:(unsigned long long)arg1 preferences:(id)arg2 onboarded:(_Bool)arg3 remainingGhostModeDuration:(double)arg4 source:(long long)arg5;

@end

