//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCManagedVideoDataSource.h"

@class ARFrame, AVDepthData;

@protocol SCManagedVideoARDataSource <SCManagedVideoDataSource>
@property float fieldOfView;
@property(retain) AVDepthData *lastDepthData;
@property(retain) ARFrame *currentFrame;
@end

