//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCMapChromeFooterButtonsProvider.h"

@class NSArray, NSString, SCBitmojiAvatarView, SCGroupBitmojiAvatarView, SCMapFooterActionButton, SCMapPerson;

@interface SCMapChromeFriendFinderFooterButtonsProvider : NSObject <SCMapChromeFooterButtonsProvider>
{
    id <SCImageDownloading> _imageDownloader;
    SCMapFooterActionButton *_meButton;
    SCBitmojiAvatarView *_meAvatarView;
    SCMapFooterActionButton *_friendsButton;
    SCGroupBitmojiAvatarView *_friendsAvatarView;
    SCMapPerson *_me;
    NSArray *_friends;
}

@property(copy, nonatomic) NSArray *friends; // @synthesize friends=_friends;
@property(retain, nonatomic) SCMapPerson *me; // @synthesize me=_me;
- (void).cxx_destruct;
- (id)buttonForType:(unsigned long long)arg1;
- (id)initWithImageDownloader:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

