//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, SCMapCamera;

@protocol SCMapSnapshotProvider <NSObject>
- (id <SCCanceling>)generateSnapshotForCamera:(SCMapCamera *)arg1 imageSize:(struct CGSize)arg2 completionQueue:(NSObject<OS_dispatch_queue> *)arg3 completion:(void (^)(UIImage *, NSError *))arg4;
@end

