//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCComposerMarshallableObject.h"

@class NSString;

@interface SCMapPassportBucketEntryViewModel : SCComposerMarshallableObject
{
    NSString *_bucketId;
    NSString *_countString;
    NSString *_title;
}

@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *countString; // @synthesize countString=_countString;
@property(copy, nonatomic) NSString *bucketId; // @synthesize bucketId=_bucketId;
- (void).cxx_destruct;
- (long long)pushToComposerMarshaller:(struct SCComposerMarshaller *)arg1;
- (id)initWithBucketId:(id)arg1 countString:(id)arg2 title:(id)arg3;

@end

