//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableDictionary, SCMapsAddress;

@interface SCMapsLocationAddressWithLocalizationsResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableDictionary *addresses; // @dynamic addresses;
@property(readonly, nonatomic) unsigned long long addresses_Count; // @dynamic addresses_Count;
@property(nonatomic) _Bool hasIds; // @dynamic hasIds;
@property(retain, nonatomic) SCMapsAddress *ids; // @dynamic ids;

@end

