//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError;

@protocol SCMapLoadingStateListener <NSObject>

@optional
- (void)mapLoadingStateDidFinishLoadingStyle:(id <SCMapLoadingState>)arg1;
- (void)mapLoadingStateDidFinishRenderingFrame:(id <SCMapLoadingState>)arg1 fullyRendered:(_Bool)arg2;
- (void)mapLoadingState:(id <SCMapLoadingState>)arg1 didFailLoadingWithError:(NSError *)arg2;
- (void)mapLoadingStateDidFinishLoading:(id <SCMapLoadingState>)arg1;
- (void)mapLoadingStateDidStartLoading:(id <SCMapLoadingState>)arg1;
@end

