//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface SCMapCamera : NSObject <NSCoding, NSCopying>
{
    double _heading;
    double _pitch;
    double _altitude;
    struct CLLocationCoordinate2D _centerCoordinate;
}

@property(readonly, nonatomic) double altitude; // @synthesize altitude=_altitude;
@property(readonly, nonatomic) double pitch; // @synthesize pitch=_pitch;
@property(readonly, nonatomic) double heading; // @synthesize heading=_heading;
@property(readonly, nonatomic) struct CLLocationCoordinate2D centerCoordinate; // @synthesize centerCoordinate=_centerCoordinate;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCenterCoordinate:(struct CLLocationCoordinate2D)arg1 heading:(double)arg2 pitch:(double)arg3 altitude:(double)arg4;
- (_Bool)isVisuallyEqualToCamera:(id)arg1 ignoringAltitude:(_Bool)arg2;
- (_Bool)isVisuallyEqualToCamera:(id)arg1;

@end

