//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCManagedCaptureDeviceDelegate.h"

@class NSString, SCCaptureResource;

@interface SCManagedCaptureDeviceHandler : NSObject <SCManagedCaptureDeviceDelegate>
{
    SCCaptureResource *_captureResource;
}

@property(nonatomic) __weak SCCaptureResource *captureResource; // @synthesize captureResource=_captureResource;
- (void).cxx_destruct;
- (void)managedCaptureDevice:(id)arg1 didChangeFocusPoint:(struct CGPoint)arg2;
- (void)managedCaptureDevice:(id)arg1 didChangeExposurePoint:(struct CGPoint)arg2;
- (void)managedCaptureDevice:(id)arg1 didChangeAdjustingFocus:(_Bool)arg2;
- (void)managedCaptureDevice:(id)arg1 didChangeAdjustingExposure:(_Bool)arg2;
- (id)initWithCaptureResource:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

