//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCMapActionSheetPresenter.h"
#import "SCOpenUnifiedProfileActionHandlerDelegate.h"

@class NSString, SCOpenUnifiedProfileActionHandler, SCUserSession;

@interface SCMapUnifiedProfileActionSheetPresenter : NSObject <SCOpenUnifiedProfileActionHandlerDelegate, SCMapActionSheetPresenter>
{
    id <NavigationDelegate> _navigationDelegate;
    SCUserSession *_userSession;
    id <SCMapActionSheetPresenterDelegate> _delegate;
    SCOpenUnifiedProfileActionHandler *_openUnifiedProfileActionHandler;
}

- (void).cxx_destruct;
- (void)presentActionSheetOnViewController:(id)arg1 person:(id)arg2 mapPeopleFriendsProvider:(id)arg3 delegate:(id)arg4;
- (void)openUnifiedProfileActionHandler:(id)arg1 navigateToChatWithUsername:(id)arg2 deepLinkURL:(id)arg3;
- (id)initWithNavigationDelegate:(id)arg1 userSession:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

