//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCMapTouchResponder.h"

@class NSString;

@protocol SCMapTapToPlayResponder <SCMapTouchResponder>
- (NSString *)shakeLogDescription;
- (_Bool)isActive;
- (_Bool)isPresentingStory;
- (void)dismissStory;
@end

