//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCMapboxStyleProvider.h"

@class NSString, NSURL;

@interface SCMapboxStaticStyleProvider : NSObject <SCMapboxStyleProvider>
{
    NSURL *_styleURL;
}

- (void).cxx_destruct;
- (id)loadError;
- (id)styleURL;
- (id)styleURLWithIsPlaceholder:(_Bool *)arg1;
- (id)initWithMapboxStyleId:(id)arg1;
- (id)initWithStyleURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

