//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCMapCarouselPersonRowController, UIView, UIViewController;

@protocol SCMapCarouselPersonRowControllerDelegate <NSObject>

@optional
- (UIViewController *)baseViewControllerForFocusingPersonRowController:(SCMapCarouselPersonRowController *)arg1;
- (void)personCarouselRowDidFocus:(SCMapCarouselPersonRowController *)arg1;
- (void)personCarouselRowDidTapDismissShareLocation:(SCMapCarouselPersonRowController *)arg1;
- (void)personCarouselRowDidTapShareLocation:(SCMapCarouselPersonRowController *)arg1;
- (void)personCarouselRowDidTapExplore:(SCMapCarouselPersonRowController *)arg1;
- (void)personCarouselRowDidTapUpdateStatus:(SCMapCarouselPersonRowController *)arg1;
- (void)personCarouselRowDidLongPressProfile:(SCMapCarouselPersonRowController *)arg1;
- (void)personCarouselRowDidTapProfile:(SCMapCarouselPersonRowController *)arg1;
- (void)personCarouselRowWantsToOpenChat:(SCMapCarouselPersonRowController *)arg1;
- (void)personCarouselRowDidTapStory:(SCMapCarouselPersonRowController *)arg1 sourceView:(UIView *)arg2;
@end

