//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCEntryPoint.h"

#import "SCTraceEnabled.h"

@class NSString, SCAttributionServices, SCMemoryBackgroundReporter, SCMemoryDebugViewer, SCMemoryLowWarningReporter, SCMemoryPageViewReporter, SCRealtimeMemoryMonitor, SCSystemScope;

@interface SCMemoryUsageEntryPoint : SCEntryPoint <SCTraceEnabled>
{
    SCRealtimeMemoryMonitor *_realtimeMemoryMonitor;
    SCMemoryDebugViewer *_memoryDebugViewer;
    SCMemoryLowWarningReporter *_memoryLowReporter;
    SCMemoryBackgroundReporter *_memoryBackgroundReporter;
    SCMemoryPageViewReporter *_memoryPageViewReporter;
    SCSystemScope *_systemScope;
    SCAttributionServices *_attributionServices;
}

@property(nonatomic) __weak SCAttributionServices *attributionServices; // @synthesize attributionServices=_attributionServices;
@property(nonatomic) __weak SCSystemScope *systemScope; // @synthesize systemScope=_systemScope;
- (void).cxx_destruct;
- (void)_createMemoryPageViewReporterWithGrapheneLogger:(id)arg1 blizzardLogger:(id)arg2 memorySnapshot:(id)arg3;
- (void)_createMemoryBackgroundReporterWithGrapheneLogger:(id)arg1 blizzardLogger:(id)arg2 memorySnapshot:(id)arg3;
- (void)_createMemoryLowWarningReporterWithGrapheneLogger:(id)arg1;
- (void)begin;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

