//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCMessagingUUID;

@interface SCMessagingLegacyMultisnap : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCMessagingUUID *bundleId; // @dynamic bundleId;
@property(nonatomic) _Bool hasBundleId; // @dynamic hasBundleId;
@property(nonatomic) _Bool isTrimmed; // @dynamic isTrimmed;
@property(nonatomic) unsigned int outputCount; // @dynamic outputCount;
@property(nonatomic) unsigned int outputIndex; // @dynamic outputIndex;
@property(nonatomic) unsigned int previewCount; // @dynamic previewCount;
@property(nonatomic) unsigned int previewIndex; // @dynamic previewIndex;

@end

