//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSArray, NSString, SCMediaEndpointInfo;

@interface SCMedia : NSObject <NSCopying, NSCoding>
{
    unsigned long long _subtype;
    NSString *_url_mediaUrl;
    NSString *_url_mediaIV;
    NSString *_url_mediaKey;
    NSString *_endpoint_endpoint;
    NSArray *_endpoint_queryItems;
    SCMediaEndpointInfo *_endpoint_endpointInfo;
}

+ (id)urlWithMediaUrl:(id)arg1 mediaIV:(id)arg2 mediaKey:(id)arg3;
+ (id)endpointWithEndpoint:(id)arg1 queryItems:(id)arg2 endpointInfo:(id)arg3;
- (void).cxx_destruct;
- (void)matchUrl:(CDUnknownBlockType)arg1 endpoint:(CDUnknownBlockType)arg2;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;

@end

