//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SCMediaDataPackageManager;

@interface SCMediaDataPackageHandle : NSObject
{
    SCMediaDataPackageManager *_dataPackageManager;
    NSString *_packageId;
}

@property(readonly, nonatomic) NSString *packageId; // @synthesize packageId=_packageId;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithPackageId:(id)arg1 dataPackageManager:(id)arg2;

@end

