//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface SCMessagingSnap : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *componentsArray; // @dynamic componentsArray;
@property(readonly, nonatomic) unsigned long long componentsArray_Count; // @dynamic componentsArray_Count;

@end

