//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, SCMessagingUUID;

@interface SCMessagingNameChangeStatusMessage : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasInitiatingUserId; // @dynamic hasInitiatingUserId;
@property(retain, nonatomic) SCMessagingUUID *initiatingUserId; // @dynamic initiatingUserId;
@property(copy, nonatomic) NSString *newName; // @dynamic newName;
@property(copy, nonatomic) NSString *oldName; // @dynamic oldName;

@end

