//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCMiniProfileRowController.h"

@class NSString;

@interface SCMiniProfileFooterRowController : SCMiniProfileRowController
{
    id <SCMiniProfileFooterRowControllerDelegate> _delegate;
    NSString *_text;
    long long _style;
}

- (void).cxx_destruct;
- (void)didSelectCell;
- (void)willDisplayCell:(id)arg1;
- (double)additionalSidePadding;
- (double)cellHeight;
- (Class)cellClass;
- (void)setStyle:(long long)arg1;
- (void)setText:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

