//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCMomentsOptInEventModel;

@protocol SCMomentsOptInViewDelegate <NSObject>
- (void)dismissMomentsOptIn;
- (void)didUpdateSubscription:(_Bool)arg1 optInEvent:(SCMomentsOptInEventModel *)arg2 failure:(void (^)(SCMomentsOptInEventModel *, _Bool))arg3;
@end

