//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCMomentsOptInEventCollectionViewCell;

@protocol SCMomentsOptInEventCollectionViewCellDelegate <NSObject>
- (void)optInEventCollectionViewCell:(SCMomentsOptInEventCollectionViewCell *)arg1 didUpdateSubscription:(_Bool)arg2;
@end

