//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData, SCMTToken;

@interface SCMTGetAuthTokenResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSData *encryptedToken; // @dynamic encryptedToken;
@property(nonatomic) _Bool hasToken; // @dynamic hasToken;
@property(retain, nonatomic) SCMTToken *token; // @dynamic token;

@end

