//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface SCMTPipelineCluster : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) double endTime; // @dynamic endTime;
@property(copy, nonatomic) NSString *id_p; // @dynamic id_p;
@property(nonatomic) double score; // @dynamic score;
@property(retain, nonatomic) NSMutableArray *snapIdsArray; // @dynamic snapIdsArray;
@property(readonly, nonatomic) unsigned long long snapIdsArray_Count; // @dynamic snapIdsArray_Count;
@property(copy, nonatomic) NSString *source; // @dynamic source;
@property(nonatomic) double startTime; // @dynamic startTime;
@property(nonatomic) int thumbSize; // @dynamic thumbSize;

@end

