//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCMTPointOfInterestSizeEquation;

@interface SCMTPoiTileSetInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasPoiSizeEquation; // @dynamic hasPoiSizeEquation;
@property(retain, nonatomic) SCMTPointOfInterestSizeEquation *poiSizeEquation; // @dynamic poiSizeEquation;

@end

