//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableSet;

@interface SCMultiSnapDrawingCache : NSObject
{
    NSMutableSet *_activeSegmentIds;
    NSMutableArray *_entries;
    long long _editingSegmentUniqueId;
}

@property(nonatomic) long long editingSegmentUniqueId; // @synthesize editingSegmentUniqueId=_editingSegmentUniqueId;
- (void).cxx_destruct;
- (void)_removeUnusedCacheEntries;
- (void)updateWithMultiSnapConfiguration:(id)arg1;
- (id)cachedImageForDrawingHistory:(id)arg1 historyCount:(long long)arg2 endStrokeIndexPtr:(long long *)arg3 clearUnusedEntries:(_Bool)arg4;
- (void)addCacheEntryForImage:(id)arg1 startingStrokeId:(long long)arg2 endingStrokeId:(long long)arg3 strokeCount:(long long)arg4;
- (void)receivedMemoryWarning;
- (id)init;

@end

