//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCActionHandling.h"
#import "SCBitmojiAvatarBuilderRouterDelegate.h"
#import "SCBitmojiSelfieManagerListener.h"
#import "SCTraceEnabled.h"

@class NSString, SCBitmojiAvatarBuilderRouter, SCCommerceOperaPresenter, SCUnifiedProfileBitmojiSectionLoadingStateProvider, SCUpdateListenerAnnouncer, SCUserSession, UIViewController<SCPageNameLogging>;

@interface SCMyUnifiedProfileBitmojiActionHandler : NSObject <SCBitmojiSelfieManagerListener, SCBitmojiAvatarBuilderRouterDelegate, SCTraceEnabled, SCActionHandling>
{
    SCUpdateListenerAnnouncer *_updateAnnouncer;
    SCUserSession *_userSession;
    SCCommerceOperaPresenter *_commerceOperaPresenter;
    SCBitmojiAvatarBuilderRouter *_bitmojiAvatarBuilderRouter;
    SCUnifiedProfileBitmojiSectionLoadingStateProvider *_bitmojiSectionLoadingStateProvider;
    UIViewController<SCPageNameLogging> *_presentingViewController;
}

+ (id)announcerIdentifier;
@property(nonatomic) __weak UIViewController<SCPageNameLogging> *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
- (void).cxx_destruct;
- (id)bitmojiAvatarBuilderPresentingViewController;
- (void)_openKeyboardOnboardingInBitmoji;
- (void)_presentBitmojiMerch:(id)arg1;
- (void)_presentSelfieViewController;
- (void)_selectSelfie;
- (void)_editBitmoji;
- (void)_changeOutfit;
- (void)_createBitmoji;
- (void)selfiePackDidChange;
- (_Bool)handleActionWithSender:(id)arg1 actionModel:(id)arg2 fromSourceView:(id)arg3;
- (void)removeUpdateListener:(id)arg1;
- (void)addUpdateListener:(id)arg1;
- (id)initWithUserSession:(id)arg1 bitmojiSectionLoadingStateProvider:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

