//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class SCSnapchatterThumbnailViewModel;

@interface SCMyUnifiedProfileSnapProLogoViewModel : NSObject <NSCopying>
{
    _Bool _showAddToStoryIcon;
    SCSnapchatterThumbnailViewModel *_thumbnailViewModel;
}

@property(readonly, nonatomic) _Bool showAddToStoryIcon; // @synthesize showAddToStoryIcon=_showAddToStoryIcon;
@property(readonly, copy, nonatomic) SCSnapchatterThumbnailViewModel *thumbnailViewModel; // @synthesize thumbnailViewModel=_thumbnailViewModel;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithThumbnailViewModel:(id)arg1 showAddToStoryIcon:(_Bool)arg2;

@end

