//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCNetworkConnectivityRecord : NSObject
{
    double _timeStamp;
    long long _newStatus;
}

@property(nonatomic) long long newStatus; // @synthesize newStatus=_newStatus;
@property(nonatomic) double timeStamp; // @synthesize timeStamp=_timeStamp;
- (id)initWithTS:(double)arg1 Status:(long long)arg2;

@end

