//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCAPIClientListener.h"

@class NSString, SCLazy, SCQueuePerformer;

@interface SCNetworkRequestSignalCollector : NSObject <SCAPIClientListener>
{
    SCQueuePerformer *_performer;
    SCLazy *_retrySignalAnnouncerLazy;
}

- (void).cxx_destruct;
- (void)apiClientDidFinishRequest:(id)arg1 response:(id)arg2 parameters:(id)arg3;
- (id)initWithRetrySignalAnnouncerLazy:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

