//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SCNFideliusKeyWrappingResult : NSObject
{
    _Bool _success;
    NSArray *_wrappedKeys;
    NSArray *_metrics;
}

+ (id)KeyWrappingResultWithWrappedKeys:(id)arg1 success:(_Bool)arg2 metrics:(id)arg3;
@property(readonly, nonatomic) NSArray *metrics; // @synthesize metrics=_metrics;
@property(readonly, nonatomic) _Bool success; // @synthesize success=_success;
@property(readonly, nonatomic) NSArray *wrappedKeys; // @synthesize wrappedKeys=_wrappedKeys;
- (void).cxx_destruct;
- (id)description;
- (id)initWithWrappedKeys:(id)arg1 success:(_Bool)arg2 metrics:(id)arg3;

@end

