//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SCNMessagingUserKeysResult : NSObject
{
    NSArray *_keys;
}

+ (id)UserKeysResultWithKeys:(id)arg1;
@property(readonly, nonatomic) NSArray *keys; // @synthesize keys=_keys;
- (void).cxx_destruct;
- (id)description;
- (id)initWithKeys:(id)arg1;

@end

