//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCNNetworkTypesUploadDataProvider.h"

@interface SCNNetworkTypesUploadDataProviderCppProxy : NSObject <SCNNetworkTypesUploadDataProvider>
{
    struct Handle<std::__1::shared_ptr<snap::network_types::UploadDataProvider>, std::__1::shared_ptr<snap::network_types::UploadDataProvider>> _cppRefHandle;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)data;
- (id)initWithCpp:(const shared_ptr_1a7ce957 *)arg1;

@end

