//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCNNetworkTypesHttpRequestBuilder : NSObject
{
    struct Handle<std::__1::shared_ptr<snap::network_types::HttpRequestBuilder>, std::__1::shared_ptr<snap::network_types::HttpRequestBuilder>> _cppRefHandle;
}

+ (id)create;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)build;
- (id)setDeprecatedHttpRequestInfo:(id)arg1;
- (id)addHttpHeader:(id)arg1 value:(id)arg2;
- (id)setHttpMethod:(long long)arg1;
- (id)setUrl:(id)arg1;
- (id)initWithCpp:(const shared_ptr_11f5830e *)arg1;

@end

