//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCOnDemandLensDataStoreProtocol.h"
#import "SCUserSessionScoped.h"

@class NSMutableDictionary, NSString, SCOnDemandLensAllTimeHitsTemplateDataStore, SCOnDemandLensDataStoreListenerAnnouncer, SCSessionRequestManager;

@interface SCOnDemandLensDataStore : NSObject <SCUserSessionScoped, SCOnDemandLensDataStoreProtocol>
{
    NSMutableDictionary *_onDemandCategoryToLenses;
    SCOnDemandLensDataStoreListenerAnnouncer *_announcer;
    SCSessionRequestManager *_requestManager;
    SCOnDemandLensAllTimeHitsTemplateDataStore *_allTimeHitsTemplateDataStore;
}

+ (id)encodedStateArchivePath;
+ (void)removeSavedState;
+ (id)restoreSavedState;
@property(retain, nonatomic) SCOnDemandLensAllTimeHitsTemplateDataStore *allTimeHitsTemplateDataStore; // @synthesize allTimeHitsTemplateDataStore=_allTimeHitsTemplateDataStore;
@property(retain, nonatomic) SCSessionRequestManager *requestManager; // @synthesize requestManager=_requestManager;
- (void).cxx_destruct;
- (void)saveState;
- (void)clear;
- (void)_subscribeForNotifications;
- (void)_ensureNonNilObjects;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (id)objectsForAllTimeHitsCategory;
- (void)addObjectForAllTimeHitsCategory:(id)arg1;
- (void)updateDataForOnDemandLensCategory:(id)arg1;
- (id)objectsForOnDemandLensCategory:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)invalidate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

