//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SCOperaMediaTypeConfiguration : NSObject
{
    NSString *_type;
    id <SCOperaModelProvider> _modelProvider;
    id <SCOperaModelToPagePropertiesConverter> _modelToPagePropertiesConverter;
    id <SCOperaPlaylistItemGroupResolver> _playlistItemGroupResolver;
    id <SCOperaPlaylistItemGroupDataModelResolver> _playlistItemGroupDataModelResolver;
    id <SCOperaPlaylistItemMediaPreparationController> _mediaPreparationController;
}

@property(retain, nonatomic) id <SCOperaPlaylistItemMediaPreparationController> mediaPreparationController; // @synthesize mediaPreparationController=_mediaPreparationController;
@property(readonly, nonatomic) id <SCOperaPlaylistItemGroupDataModelResolver> playlistItemGroupDataModelResolver; // @synthesize playlistItemGroupDataModelResolver=_playlistItemGroupDataModelResolver;
@property(readonly, nonatomic) id <SCOperaPlaylistItemGroupResolver> playlistItemGroupResolver; // @synthesize playlistItemGroupResolver=_playlistItemGroupResolver;
@property(readonly, nonatomic) id <SCOperaModelToPagePropertiesConverter> modelToPagePropertiesConverter; // @synthesize modelToPagePropertiesConverter=_modelToPagePropertiesConverter;
@property(readonly, nonatomic) id <SCOperaModelProvider> modelProvider; // @synthesize modelProvider=_modelProvider;
@property(readonly, copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithType:(id)arg1 modelProvider:(id)arg2 modelToPagePropertiesConverter:(id)arg3 playlistItemGroupResolver:(id)arg4 playlistItemGroupDataModelResolver:(id)arg5;

@end

