//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SCEventListenerAnnouncer, SCOperaViewController;

@protocol SCOperaShakeToReportOperator <NSObject>
@property(readonly, nonatomic) NSString *eventName;
@property(readonly, nonatomic) NSString *announcerIdentifier;
@property(readonly, nonatomic) SCEventListenerAnnouncer *eventAnnouncer;
- (void)operaDidDisappear;
- (void)operaDidAppear:(SCOperaViewController *)arg1;
@end

