//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface SCPBAirReportOption : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool createJira; // @dynamic createJira;
@property(nonatomic) _Bool fromTestAutomation; // @dynamic fromTestAutomation;
@property(nonatomic) _Bool isAutoShake; // @dynamic isAutoShake;
@property(retain, nonatomic) NSMutableArray *jiraLabelsArray; // @dynamic jiraLabelsArray;
@property(readonly, nonatomic) unsigned long long jiraLabelsArray_Count; // @dynamic jiraLabelsArray_Count;
@property(nonatomic) _Bool uploadLog; // @dynamic uploadLog;

@end

