//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString, SCPBGalleryServletQuota;

@interface SCPBGalleryServletGetSnapsResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long backoffTime; // @dynamic backoffTime;
@property(copy, nonatomic) NSString *debugInfo; // @dynamic debugInfo;
@property(nonatomic) _Bool hasQuota; // @dynamic hasQuota;
@property(retain, nonatomic) SCPBGalleryServletQuota *quota; // @dynamic quota;
@property(nonatomic) int serviceStatusCode; // @dynamic serviceStatusCode;
@property(retain, nonatomic) NSMutableArray *snapsArray; // @dynamic snapsArray;
@property(readonly, nonatomic) unsigned long long snapsArray_Count; // @dynamic snapsArray_Count;
@property(nonatomic) int totalEntryCount; // @dynamic totalEntryCount;
@property(copy, nonatomic) NSString *userString; // @dynamic userString;

@end

