//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SCPBUnlockablesRatingStickerProperties : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int initialRating; // @dynamic initialRating;
@property(nonatomic) int maxRating; // @dynamic maxRating;
@property(copy, nonatomic) NSString *selectedStateAsset; // @dynamic selectedStateAsset;
@property(copy, nonatomic) NSString *unselectedStateAsset; // @dynamic unselectedStateAsset;

@end

