//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCPNFLTinyDNNSequentialModel;

@interface SCPNFLTinyDNNModel : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(readonly, nonatomic) int modelOneOfCase; // @dynamic modelOneOfCase;
@property(retain, nonatomic) SCPNFLTinyDNNSequentialModel *sequential; // @dynamic sequential;

@end

