//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class CAGradientLayer, NSString, SCProfileCharmsCardViewCell, UILabel, UIScrollView;

@interface SCProfileCharmsCardViewCellDescriptionView : UIView <UIScrollViewDelegate>
{
    UILabel *_description;
    UIScrollView *_descriptionScrollView;
    UILabel *_gradientDescription;
    UIScrollView *_gradientDescriptionScrollView;
    CAGradientLayer *_gradient;
    double _contentOffsetYRatio;
    SCProfileCharmsCardViewCell *_cell;
}

@property(nonatomic) __weak SCProfileCharmsCardViewCell *cell; // @synthesize cell=_cell;
- (void).cxx_destruct;
- (void)_layoutDescriptionScrollView:(id)arg1 withDescription:(id)arg2;
- (void)_setText:(id)arg1 toDescription:(id)arg2;
- (id)_initializeDescriptionScrollView;
- (id)_initializeDescription;
- (void)_resetGradientView;
- (void)scrollViewDidScroll:(id)arg1;
- (struct CGSize)descriptionSizeWithHeightLimit:(double)arg1;
- (void)setText:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

