//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCPreviewTransitionDefaultAnimatorDelegate.h"
#import "SCPreviewTransitioningDelegate.h"

@class NSString, SCCameraViewController, SCFeature<SCFeatureCameraLiveDisplay>, SCHovaNavigationBar, SCHovaTabBarItem, SCHovaTabBarView, SCPreviewTransitionDefaultAnimator, UIView<SCCameraTimer>;

@interface SCPreviewTransitionController : NSObject <SCPreviewTransitionDefaultAnimatorDelegate, SCPreviewTransitioningDelegate>
{
    SCPreviewTransitionDefaultAnimator *_defaultAnimator;
    _Bool isAsync;
    _Bool isZeroAnimationDuration;
    _Bool useLightPreviewReplyCameraBehavior;
    SCCameraViewController *cameraViewController;
    SCFeature<SCFeatureCameraLiveDisplay> *liveDisplayFeature;
    unsigned long long capturedMediaType;
    id <UIViewControllerAnimatedTransitioning> customAnimatedTransitioningAnimator;
    id <UIViewControllerInteractiveTransitioning> customInteractiveTransitioningAnimator;
    UIView<SCCameraTimer> *_cameraTimer;
}

@property(readonly, nonatomic) UIView<SCCameraTimer> *cameraTimer; // @synthesize cameraTimer=_cameraTimer;
@property(nonatomic) _Bool useLightPreviewReplyCameraBehavior; // @synthesize useLightPreviewReplyCameraBehavior;
@property(nonatomic) __weak id <UIViewControllerInteractiveTransitioning> customInteractiveTransitioningAnimator; // @synthesize customInteractiveTransitioningAnimator;
@property(nonatomic) __weak id <UIViewControllerAnimatedTransitioning> customAnimatedTransitioningAnimator; // @synthesize customAnimatedTransitioningAnimator;
@property(nonatomic) unsigned long long capturedMediaType; // @synthesize capturedMediaType;
@property(nonatomic) __weak SCFeature<SCFeatureCameraLiveDisplay> *liveDisplayFeature; // @synthesize liveDisplayFeature;
@property(nonatomic) _Bool isZeroAnimationDuration; // @synthesize isZeroAnimationDuration;
@property(nonatomic) _Bool isAsync; // @synthesize isAsync;
@property(nonatomic) __weak SCCameraViewController *cameraViewController; // @synthesize cameraViewController;
- (void).cxx_destruct;
@property(readonly, nonatomic) __weak SCHovaNavigationBar *hovaNavigationBar;
@property(readonly, nonatomic) __weak SCHovaTabBarItem *hovaCameraTabBarItem;
@property(readonly, nonatomic) __weak SCHovaTabBarView *hovaTabBarView;
- (void)_setHovaTabBarYOffset:(double)arg1;
- (void)_setNavigationBarYOffset:(double)arg1;
- (void)resetCameraPreview;
- (void)startCamera;
- (id)interactionControllerForPresentation:(id)arg1;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (_Bool)animator:(id)arg1 shouldAnimate:(id)arg2;
- (void)animator:(id)arg1 setHovaTabBarAndNavigationBarHidden:(_Bool)arg2;
- (void)animator:(id)arg1 willFinishTransition:(id)arg2;
- (void)animator:(id)arg1 willStartTransition:(id)arg2;
- (_Bool)_animatorShouldUseLightTransitionReplyCameraBehavior:(id)arg1;
- (id)previewViewControllerForTransitionContext:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

