//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class SCProfileArroyoChatMediaDataModel, SCProfileLegacyChatMediaDataModel;

@interface SCProfileChatMediaDataModelADT : NSObject <NSCopying>
{
    unsigned long long _subtype;
    SCProfileLegacyChatMediaDataModel *_legacy_legacyChatMediaDataModel;
    SCProfileArroyoChatMediaDataModel *_arroyo_arroyoChatMediaDataModel;
}

+ (id)legacyWithLegacyChatMediaDataModel:(id)arg1;
+ (id)arroyoWithArroyoChatMediaDataModel:(id)arg1;
- (void).cxx_destruct;
- (void)matchLegacy:(CDUnknownBlockType)arg1 arroyo:(CDUnknownBlockType)arg2;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

