//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCLensDataProviderListener.h"
#import "SCLensUsageTrackerListener.h"
#import "SCPreviewLensesToolBarButtonItemViewModelProtocol.h"

@class NSArray, NSSet, NSString, SCExperimentManager;

@interface SCPreviewLensesToolBarButtonItemViewModel : NSObject <SCLensUsageTrackerListener, SCLensDataProviderListener, SCPreviewLensesToolBarButtonItemViewModelProtocol>
{
    id <SCLensUsageTrackerProtocol> _lensUsageTracker;
    id <SCLensCameraScreenDataProviderProtocol> _dataProvider;
    SCExperimentManager *_experimentManager;
    NSArray *_lenses;
    NSSet *_usedLensIds;
    NSString *_lensDataProviderToken;
    _Bool _newLensesBadgeHidden;
    id <SCPreviewLensesToolBarButtonItemViewModelDelegate> _delegate;
}

@property(readonly, nonatomic) _Bool newLensesBadgeHidden; // @synthesize newLensesBadgeHidden=_newLensesBadgeHidden;
@property(nonatomic) __weak id <SCPreviewLensesToolBarButtonItemViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateBadgeHiddenIfNeeded;
- (void)stopUpdatingLensData;
- (void)startUpdatingLensData;
- (void)unsubscribeListeners;
- (void)subscribeListeners;
- (void)usageTracker:(id)arg1 didUpdateUsedLensIds:(id)arg2;
- (void)lensDataProvider:(id)arg1 didUpdateLens:(id)arg2 contentUpdateType:(long long)arg3;
- (void)lensDataProvider:(id)arg1 didUpdateAllLenses:(id)arg2 requiresAnimation:(_Bool)arg3;
- (void)dealloc;
- (id)initWithDataProvider:(id)arg1 lensUsageTracker:(id)arg2 experimentManager:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

