//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCBitmojiImageParams, SCProductBitmojiSelectorViewController, UIImage;

@protocol SCProductBitmojiSelectorDelegate <NSObject>
- (void)dismissBitmojiSelectorVC:(SCProductBitmojiSelectorViewController *)arg1;
- (void)bitmojiSelectorVC:(SCProductBitmojiSelectorViewController *)arg1 didSelectBitmojiImage:(UIImage *)arg2 params:(SCBitmojiImageParams *)arg3;
@end

