//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCProductOptionPickerView, SCScanProductOption;

@protocol SCProductOptionPickerViewDelegate <NSObject>
- (void)productOptionPickerView:(SCProductOptionPickerView *)arg1 didSelectOption:(SCScanProductOption *)arg2 selectedItem:(id)arg3;
@end

