//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCLocationPermissionObserver.h"
#import "SCMapStatusFetcherListener.h"
#import "SCNetworkConnectivityListener.h"

@class NSString, SCDisposableObserver, SCEmbeddedMapView, SCFriendLocationSnapshotMapView, SCLRUCache, SCProfileEmbeddedMapViewContainer, SCProfileMapViewModel, SCUserSession;

@interface SCProfileMapView : UIView <SCLocationPermissionObserver, SCMapStatusFetcherListener, SCNetworkConnectivityListener>
{
    SCUserSession *_userSession;
    SCFriendLocationSnapshotMapView *_snapshotView;
    SCEmbeddedMapView *_embeddedMapView;
    struct CGSize _mapSize;
    UIView *_embeddedMapScreenshot;
    id <SCEmbeddedStaticMapGenerator> _embeddedStaticMapGenerator;
    _Bool _currentUserGhostModeStatus;
    long long _lastNetworkConnectivityStatus;
    SCDisposableObserver *_locationPreferencesObserver;
    SCProfileMapViewModel *_mapViewModel;
    SCLRUCache *_snapshotCache;
    SCProfileEmbeddedMapViewContainer *_embeddedMapViewContainer;
}

@property(retain, nonatomic) SCProfileEmbeddedMapViewContainer *embeddedMapViewContainer; // @synthesize embeddedMapViewContainer=_embeddedMapViewContainer;
@property(retain, nonatomic) SCLRUCache *snapshotCache; // @synthesize snapshotCache=_snapshotCache;
@property(retain, nonatomic) SCProfileMapViewModel *mapViewModel; // @synthesize mapViewModel=_mapViewModel;
- (void).cxx_destruct;
- (void)networkConnectivityStatusDidChange:(long long)arg1;
- (id)locationPermissionObserverUserId;
- (void)onLocationPermissionStatusChange:(unsigned long long)arg1;
- (void)mapStatusFetcherDidLoadMyStatus:(id)arg1;
- (void)_locationSharingPreferencesUpdated:(id)arg1;
- (id)_getOrCreateEmbeddedMapWithViewModel:(id)arg1;
- (void)_loadEmbeddedMapViewWithPersonLocation:(id)arg1 isCurrentUser:(_Bool)arg2 loggingSession:(id)arg3;
- (_Bool)_shouldUseStaticMapForSelectedUserId:(id)arg1;
- (void)_setupEmbeddedMapViewWithViewModel:(id)arg1;
- (void)_setupSnapshotViewWithViewModel:(id)arg1;
- (void)_setupViewsWithViewModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 mapSize:(struct CGSize)arg2 userSession:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

