//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCPreviewLatencyLogging.h"

@class NSMutableDictionary;

@interface SCPreviewLatencyGrapheneLogger : NSObject <SCPreviewLatencyLogging>
{
    id <SCGraphene> _grapheneLogger;
    double _previewInteractiveTime;
    NSMutableDictionary *_ttiStartTimes;
}

- (void).cxx_destruct;
- (id)_applyMetricDimensionsToMetric:(id)arg1 forToolType:(long long)arg2 action:(long long)arg3;
- (id)_grapheneMetricForToolType:(long long)arg1;
- (double)_endTTIMeasurementForToolType:(long long)arg1 action:(long long)arg2 logSuccess:(long long)arg3;
- (double)endTTIMeasurementForToolType:(long long)arg1 action:(long long)arg2 success:(_Bool)arg3;
- (double)endTTIMeasurementForToolType:(long long)arg1 action:(long long)arg2;
- (void)startTTIMeasurementForToolType:(long long)arg1 action:(long long)arg2;
- (void)previewBecameInteractive;
- (id)initWithGrapheneLogger:(id)arg1;

@end

