//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBFloatArray;

@interface SCR2FeatureVector : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPBFloatArray *valueArray; // @dynamic valueArray;
@property(readonly, nonatomic) unsigned long long valueArray_Count; // @dynamic valueArray_Count;

@end

