//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCR2Node;

@interface SCR2Pow : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCR2Node *base; // @dynamic base;
@property(nonatomic) _Bool hasBase; // @dynamic hasBase;
@property(nonatomic) _Bool hasPower; // @dynamic hasPower;
@property(retain, nonatomic) SCR2Node *power; // @dynamic power;

@end

