//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface SCRDoubleFeatureStats : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) double p25; // @dynamic p25;
@property(nonatomic) double p5; // @dynamic p5;
@property(nonatomic) double p50; // @dynamic p50;
@property(nonatomic) double p75; // @dynamic p75;
@property(nonatomic) double p95; // @dynamic p95;

@end

