//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface SCRPCCallOptions : NSObject
{
    NSString *_authToken;
    long long _rpcTimeout;
    NSDictionary *_additionalHeaders;
}

@property(readonly, nonatomic) NSDictionary *additionalHeaders; // @synthesize additionalHeaders=_additionalHeaders;
@property(readonly, nonatomic) long long rpcTimeout; // @synthesize rpcTimeout=_rpcTimeout;
@property(readonly, nonatomic) NSString *authToken; // @synthesize authToken=_authToken;
- (void).cxx_destruct;
- (id)initWithAuthToken:(id)arg1 rpcTimeout:(long long)arg2 additionalHeaders:(id)arg3;

@end

