//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableDictionary, NSString;

@interface SCSCOREABTestStudyInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *experimentId; // @dynamic experimentId;
@property(copy, nonatomic) NSString *studyId; // @dynamic studyId;
@property(retain, nonatomic) NSMutableDictionary *variableValues; // @dynamic variableValues;
@property(readonly, nonatomic) unsigned long long variableValues_Count; // @dynamic variableValues_Count;

@end

