//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCSCKFriendStoryDerivedPosterEngagementFeatures, SCSCOREUUID, SCSIDXFriendStoryPosterEngagementFeatures;

@interface SCSCKFriendStoryPosterEngagementFeatures : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCSCKFriendStoryDerivedPosterEngagementFeatures *friendStoryDerivedPosterEngagementFeatures; // @dynamic friendStoryDerivedPosterEngagementFeatures;
@property(retain, nonatomic) SCSIDXFriendStoryPosterEngagementFeatures *friendStoryPosterEngagementFeatures; // @dynamic friendStoryPosterEngagementFeatures;
@property(nonatomic) _Bool hasFriendStoryDerivedPosterEngagementFeatures; // @dynamic hasFriendStoryDerivedPosterEngagementFeatures;
@property(nonatomic) _Bool hasFriendStoryPosterEngagementFeatures; // @dynamic hasFriendStoryPosterEngagementFeatures;
@property(nonatomic) _Bool hasPosterId; // @dynamic hasPosterId;
@property(retain, nonatomic) SCSCOREUUID *posterId; // @dynamic posterId;

@end

