//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, SCEntryPointCleanup;

@interface SCScopeLifecycleSubLifecycles : NSObject
{
    NSMutableSet *_subLifecycles;
    SCEntryPointCleanup *_cleanup;
}

- (void).cxx_destruct;
- (id)debugRepresentation;
- (id)removeAll;
- (void)remove:(id)arg1;
- (void)add:(id)arg1;
- (id)init;

@end

