//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCCLensActionHandling.h"
#import "SCLensLiveLensPreviewCameraPresenterDelegate.h"

@class NSString, UIViewController;

@interface SCSearchV2LensActionHandler : NSObject <SCLensLiveLensPreviewCameraPresenterDelegate, SCCLensActionHandling>
{
    UIViewController *_viewController;
    id <SCFeatureLensFeed> _lensFeedFeature;
    id <SCLensLiveLensPreviewCameraPresenterProtocol> _liveLensPreviewCameraPresenter;
    id <SCLensUnlockerProtocol> _lensUnlocker;
}

- (void).cxx_destruct;
- (void)lensCameraPresenter:(id)arg1 didUseLens:(id)arg2;
- (void)lensCameraPresenterDidComplete:(id)arg1;
- (void)sendLensWithLens:(id)arg1;
- (void)presentLensWithLens:(id)arg1;
- (void)openLensExplorer;
- (long long)pushToComposerMarshaller:(struct SCComposerMarshaller *)arg1;
- (id)initWithPresentingViewController:(id)arg1 lensFeedFeature:(id)arg2 liveLensPreviewCameraPresenter:(id)arg3 lensUnlocker:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

