//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCSendToListPickerContext.h"

@class NSString, SCSearchQueryResultController, SCSearchView, SCSendToListEditMenuView, SCSendToListsAlertView, SCSendToListsRecipientPickerPresenter, SCSendToQuerySourceStateTracker, UIViewController;

@interface SCSendToListsPickerActionHandler : NSObject <SCSendToListPickerContext>
{
    UIViewController *_presentingViewController;
    SCSearchView *_searchView;
    SCSendToListEditMenuView *_listEditMenuView;
    SCSearchQueryResultController *_queryResultController;
    id <SCActionHandling> _actionHandler;
    SCSendToListsRecipientPickerPresenter *_recipientPickerPresenter;
    SCSendToQuerySourceStateTracker *_querySourceStateTracker;
    id <SCUserTooltipStatusProviding> _userTooltipStatusProvider;
    SCSendToListsAlertView *_firstTimeCreationAlertView;
}

- (void).cxx_destruct;
- (void)_deselectSearchInput;
- (void)_presentFirstTimeCreationAlertWithCompletion:(CDUnknownBlockType)arg1;
- (void)_showListEditMenu;
- (long long)pushToComposerMarshaller:(struct SCComposerMarshaller *)arg1;
- (void)onCreateSelected;
- (void)onEditSelected;
- (void)onButtonSelectedDoubleTapWithIdentifier:(id)arg1;
- (void)onButtonSelectedWithIdentifier:(id)arg1;
- (void)setSearchView:(id)arg1;
- (void)setActionHandler:(id)arg1;
- (void)setQueryResultController:(id)arg1;
- (void)setListEditMenuView:(id)arg1;
- (id)initWithPresentingViewController:(id)arg1 recipientPickerPresenter:(id)arg2 querySourceStateTracker:(id)arg3 userTooltipStatusProvider:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

