//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSObject<NSCopying>, NSString;

@interface SCSearchResultSectionDescriptor : NSObject <NSCopying>
{
    NSString *_type;
    NSString *_identifier;
    long long _displayPolicy;
    NSObject<NSCopying> *_configuration;
}

@property(readonly, copy, nonatomic) NSObject<NSCopying> *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) long long displayPolicy; // @synthesize displayPolicy=_displayPolicy;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithType:(id)arg1 identifier:(id)arg2 displayPolicy:(long long)arg3 configuration:(id)arg4;

@end

