//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCTermsOfUseService.h"

@class SCPreferences, SCSessionRequestManager;

@interface SCServerSyncingTermsOfUseService : NSObject <SCTermsOfUseService>
{
    SCPreferences *_preferences;
    SCSessionRequestManager *_requestManager;
}

- (void).cxx_destruct;
- (void)_updateAcceptedTermsOfUse:(id)arg1 successBlock:(CDUnknownBlockType)arg2;
- (void)_updateAcceptedTermsOfUseV8;
- (void)_updateAcceptedTermsOfUseV7;
- (void)_updateAcceptedTermsOfUseFromAllUpdatesResponse:(id)arg1;
- (void)updateTermsOfUseWithUserSessionContext:(id)arg1;
- (_Bool)hasAcceptedTermsOfUseV8;
- (void)acceptTermsOfUseV8;
- (_Bool)hasAcceptedTermsOfUseV7;
- (void)acceptTermsOfUseV7;
- (id)initWithPreferences:(id)arg1 requestManager:(id)arg2;

@end

