//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCSearchQueryCoordinating.h"

@class NSString, SCExperimentManager, SCQueuePerformer, SCSearchNavigationCoordinator, SCSearchQuery, SCSessionRequestManager, SCSettingsOptInEntityDataStore, SCUserSession;

@interface SCSettingsStoryNotificationsQueryCoordinator : NSObject <SCSearchQueryCoordinating>
{
    SCUserSession *_userSession;
    SCSettingsOptInEntityDataStore *_dataStore;
    id <SCSnapchattersDataFetching> _snapchattersDataFetcher;
    SCSessionRequestManager *_requestManager;
    SCExperimentManager *_experimentManager;
    SCQueuePerformer *_performer;
    _Bool _isLoading;
    SCSearchQuery *_currentQuery;
    SCSearchNavigationCoordinator *_navigationCoordinator;
}

+ (id)announcerIdentifier;
@property(nonatomic) __weak SCSearchNavigationCoordinator *navigationCoordinator; // @synthesize navigationCoordinator=_navigationCoordinator;
@property(copy, nonatomic) SCSearchQuery *currentQuery; // @synthesize currentQuery=_currentQuery;
@property(readonly, nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
- (void).cxx_destruct;
- (id)_loadingQueryResultWithQuery:(id)arg1;
- (void)_displaySections:(id)arg1 query:(id)arg2 updatingBlock:(CDUnknownBlockType)arg3;
- (id)_mergeMutualFriends:(id)arg1 withOptInEntities:(id)arg2;
- (void)_completeBuildingOptInEntities:(id)arg1 query:(id)arg2 updatingBlock:(CDUnknownBlockType)arg3;
- (void)_handledSubscribedCreators:(id)arg1 creatorMetadatas:(id)arg2 query:(id)arg3 updatingBlock:(CDUnknownBlockType)arg4;
- (void)_fetchOptInEntitiesWithQuery:(id)arg1 updatingBlock:(CDUnknownBlockType)arg2;
- (void)resultsForQuery:(id)arg1 updatingBlock:(CDUnknownBlockType)arg2;
- (_Bool)canPerformQuery:(id)arg1;
- (id)initWithUserSession:(id)arg1 dataStore:(id)arg2 snapchattersDataFetcher:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

