//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable, NSMutableDictionary;

@interface SCSearchSectionController : NSObject
{
    id <SCSearchSectionCreating> _sectionCreator;
    NSMutableDictionary *_mutableSectionsToReuseByReuseIdentifier;
    NSMutableDictionary *_mutableSectionSetsByDescriptor;
    NSMapTable *_mutableDescriptorsBySection;
}

- (void).cxx_destruct;
- (void)cleanUp;
- (id)_dequeueSectionWithDescriptor:(id)arg1;
- (void)recycleSections:(id)arg1;
- (id)dequeueSectionsWithDescriptors:(id)arg1;
- (id)initWithSectionCreator:(id)arg1;

@end

