//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UICollectionView, UIView;

@protocol SCSearchTransitioning <NSObject>
@property(readonly, nonatomic) UIView *containerView;
@property(readonly, nonatomic) UICollectionView *searchTransitionCollectionView;
@property(nonatomic) double contentViewAlpha;
- (UIView *)transitionSectionHeaderForSection:(long long)arg1;
@end

