//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayoutInvalidationContext.h"

@interface SCSearchStoriesTabBarInvalidationContext : UICollectionViewLayoutInvalidationContext
{
    _Bool _isSelectedIndexInvalidated;
    unsigned long long _selectedItemIndex;
    double _offsetRatio;
}

@property(nonatomic) _Bool isSelectedIndexInvalidated; // @synthesize isSelectedIndexInvalidated=_isSelectedIndexInvalidated;
@property(nonatomic) double offsetRatio; // @synthesize offsetRatio=_offsetRatio;
@property(nonatomic) unsigned long long selectedItemIndex; // @synthesize selectedItemIndex=_selectedItemIndex;

@end

