//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerTransitioningDelegate.h"

@class NSString, SCSendToDismissTransitionController, SCSendToPresentTransitionController;

@interface SCSendToTransitionProvider : NSObject <UIViewControllerTransitioningDelegate>
{
    SCSendToPresentTransitionController *_presentController;
    _Bool _isInteractive;
    SCSendToDismissTransitionController *_dismissController;
    long long _dismissalPanGestureDirection;
    id <SCModalPresentation> _modalPresentationDelegate;
}

@property(nonatomic) __weak id <SCModalPresentation> modalPresentationDelegate; // @synthesize modalPresentationDelegate=_modalPresentationDelegate;
@property(nonatomic) long long dismissalPanGestureDirection; // @synthesize dismissalPanGestureDirection=_dismissalPanGestureDirection;
@property(readonly, nonatomic) SCSendToDismissTransitionController *dismissController; // @synthesize dismissController=_dismissController;
@property(nonatomic) _Bool isInteractive; // @synthesize isInteractive=_isInteractive;
- (void).cxx_destruct;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

