//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCActionHandling.h"

@class NSString, SCLazy, SCSendToDocObjectRecipientDataSource, SCUserSession, UIViewController;

@interface SCSendToOpenMiniProfileActionHandler : NSObject <SCActionHandling>
{
    SCUserSession *_userSession;
    SCSendToDocObjectRecipientDataSource *_recipientDataSource;
    SCLazy *_snapchattersDataFetcher;
    SCLazy *_snapchattersDataMutator;
    SCLazy *_snapchattersDataTracker;
    SCLazy *_userProvider;
    SCLazy *_viewedIncomingFriendsTracker;
    SCLazy *_friendScoreCoordinator;
    UIViewController *_presentingViewController;
}

- (void).cxx_destruct;
- (void)_presentMiniProfileForGroupId:(id)arg1;
- (void)_presentMiniProfileForSnapchatter:(id)arg1;
- (_Bool)handleActionWithSender:(id)arg1 actionModel:(id)arg2 fromSourceView:(id)arg3;
- (id)initWithUserSession:(id)arg1 recipientDataSource:(id)arg2 snapchattersDataFetcher:(id)arg3 snapchattersDataMutator:(id)arg4 snapchattersDataTracker:(id)arg5 userInfoProvider:(id)arg6 viewedIncomingFriendsTracker:(id)arg7 friendScoreCoordinator:(id)arg8 presentingViewController:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

