//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCSendToDelegate.h"
#import "SCSendToNavigationDelegate.h"

@class NSArray, NSString, SCLazy, SCScopedAccess, SCSendToTransitionProvider, SCSnapchatter, SCUserSession, UIViewController, UIViewController<SCSendToScreen>;

@interface SCShareFriendActionManager : NSObject <SCSendToDelegate, SCSendToNavigationDelegate>
{
    SCUserSession *_userSession;
    NSArray *_contexts;
    SCSnapchatter *_snapchatter;
    UIViewController<SCSendToScreen> *_sendViewController;
    SCSendToTransitionProvider *_sendToTransitionProvider;
    SCLazy *_arroyoGroupFilterer;
    SCScopedAccess *_snapchatterSender;
    id <SCShareFriendActionManagerDelegate> _delegate;
    UIViewController *_presentingViewController;
}

@property(nonatomic) __weak UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
@property(nonatomic) __weak id <SCShareFriendActionManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dismissSendViewController:(id)arg1;
- (id)_newSendToConfiguration;
- (void)_sendSnapchatterMessageToArroyoConversations:(id)arg1;
- (void)sendViewController:(id)arg1 sendToRecipients:(id)arg2 storiesPostingConfig:(id)arg3 businessIds:(id)arg4 groups:(id)arg5 appStories:(id)arg6 additionalText:(id)arg7;
- (void)sendUsername;
- (void)shareUsernameURL;
- (id)initWithSnapchatter:(id)arg1 userSession:(id)arg2 contexts:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

