//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString, SCMediaMetadata;

@interface SCShazamShareDataModel : NSObject <NSCopying>
{
    id <SCChatMediaContentProvider> _media;
    SCMediaMetadata *_mediaMetadata;
    NSString *_attachedURL;
    NSString *_additionalText;
}

@property(readonly, copy, nonatomic) NSString *additionalText; // @synthesize additionalText=_additionalText;
@property(readonly, copy, nonatomic) NSString *attachedURL; // @synthesize attachedURL=_attachedURL;
@property(readonly, copy, nonatomic) SCMediaMetadata *mediaMetadata; // @synthesize mediaMetadata=_mediaMetadata;
@property(readonly, nonatomic) id <SCChatMediaContentProvider> media; // @synthesize media=_media;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithMedia:(id)arg1 mediaMetadata:(id)arg2 attachedURL:(id)arg3 additionalText:(id)arg4;

@end

