//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString, UIColor;

@interface SCSingleStrokeCanvas : NSObject
{
    NSMutableArray *_points;
    double _lineWidth;
    UIColor *_lineColor;
    NSString *_emoji;
    id <SCStrokeDrawer> _solidStrokeDrawer;
    id <SCStrokeDrawer> _emojiStrokeDrawer;
    id <SCStrokeDrawer> _currentActivateDrawer;
    long long _drawerType;
    long long _smoothingAlgorithmVersion;
}

@property(nonatomic) long long smoothingAlgorithmVersion; // @synthesize smoothingAlgorithmVersion=_smoothingAlgorithmVersion;
@property(readonly, nonatomic) long long drawerType; // @synthesize drawerType=_drawerType;
- (void).cxx_destruct;
- (void)drawStrokeToContext:(struct CGContext *)arg1 drawRect:(struct CGRect)arg2;
- (void)_updateDrawingData:(id)arg1 emoji:(id)arg2 lineWidth:(double)arg3 drawerType:(long long)arg4;
- (void)updateWithStroke:(id)arg1;
- (id)init;

@end

