//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCOperaLayerViewControllerFactory.h"

@class NSString;

@interface SCSnappablesLayerFactory : NSObject <SCOperaLayerViewControllerFactory>
{
}

+ (id)layerViewControllerWithLayer:(id)arg1 configuration:(id)arg2 eventAnnouncer:(id)arg3 sharedResourceManager:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

