//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCDocObjectChangeRequest.h"

@class NSString;

@interface SCSnapKitAppStoryMetadataChangeRequest : NSObject <SCDocObjectChangeRequest>
{
    long long _rowid;
    int _requestType;
    _Bool _turnedOn;
    NSString *_displayName;
    NSString *_iconURL;
    long long _ttlDays;
}

+ (id)deletionRequestForSnapKitAppStoryMetadata:(id)arg1;
+ (id)changeRequestForSnapKitAppStoryMetadata:(id)arg1;
+ (id)creationRequestWithSnapKitAppStoryMetadata:(id)arg1;
@property(nonatomic) _Bool turnedOn; // @synthesize turnedOn=_turnedOn;
@property(nonatomic) long long ttlDays; // @synthesize ttlDays=_ttlDays;
@property(copy, nonatomic) NSString *iconURL; // @synthesize iconURL=_iconURL;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
- (void).cxx_destruct;
- (id)transactWithSQLite:(struct SQLiteConnection *)arg1 flatbuffers:(struct FlatBufferBuilder *)arg2;
- (id)_snapKitAppStoryMetadata;
- (id)initWithRowid:(long long)arg1 displayName:(id)arg2 iconURL:(id)arg3 ttlDays:(long long)arg4 turnedOn:(_Bool)arg5;
- (void)createTableWithSQLite:(struct sqlite3 *)arg1;
- (const char *)table;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

