//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCSnapchattersFetchedResultLookup.h"

@class SCDocObjectObserver;

@interface SCSnapchatterObserver : NSObject <SCSnapchattersFetchedResultLookup>
{
    SCDocObjectObserver *_observer;
}

- (void).cxx_destruct;
- (id)snapchatterWithUsername:(id)arg1;
- (id)snapchatterWithUserId:(id)arg1;
- (id)snapchatter;
- (id)initWithDocObjectContext:(id)arg1 fetchBlock:(CDUnknownBlockType)arg2;

@end

