//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCActiveUserSessionScope, SCContextUserScopedServices, SCObservableRegistry, SCScopeExposer, SCServicesExposer;

@interface SCSnapActionsServicesEntryPoint : SCEntryPoint
{
    SCObservableRegistry *_actionProviderRegistry;
    SCActiveUserSessionScope *_activeUserSessionScope;
    SCContextUserScopedServices *_contextUserScopedServices;
    SCScopeExposer *_actionPerformerProviderScopeExposer;
    SCServicesExposer *_snapActionsServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *snapActionsServicesExposer; // @synthesize snapActionsServicesExposer=_snapActionsServicesExposer;
@property(retain, nonatomic) SCScopeExposer *actionPerformerProviderScopeExposer; // @synthesize actionPerformerProviderScopeExposer=_actionPerformerProviderScopeExposer;
@property(nonatomic) __weak SCContextUserScopedServices *contextUserScopedServices; // @synthesize contextUserScopedServices=_contextUserScopedServices;
@property(nonatomic) __weak SCActiveUserSessionScope *activeUserSessionScope; // @synthesize activeUserSessionScope=_activeUserSessionScope;
- (void).cxx_destruct;
- (id)end;
- (void)begin;

@end

