//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SCObservable;

@protocol SCSortableSnapchatterObservableRepository <NSObject>
@property(readonly, nonatomic) SCObservable *allFriendsObservable;
@property(readonly, nonatomic) SCObservable *outgoingSnapchatterObservable;
@property(readonly, nonatomic) SCObservable *recentMutualFriendsObservable;
@property(readonly, nonatomic) SCObservable *recentFriendsObservable;
@property(readonly, nonatomic) SCObservable *bestFriendsObservable;
- (void)warmUp;
- (SCObservable *)mutualFriendsObservableForLetterKey:(NSString *)arg1;
- (SCObservable *)friendsObservableForLetterKey:(NSString *)arg1;
- (SCObservable *)searchMutualFriendsObservableForQuery:(NSString *)arg1;
- (SCObservable *)searchFriendsObservableForQuery:(NSString *)arg1;
@end

