//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSNumber, NSString;

@interface SCSpectaclesLookupTableExtractionInfo : NSObject <NSCopying>
{
    NSString *_serialNumber;
    NSNumber *_contentType;
}

@property(readonly, copy, nonatomic) NSNumber *contentType; // @synthesize contentType=_contentType;
@property(readonly, copy, nonatomic) NSString *serialNumber; // @synthesize serialNumber=_serialNumber;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithSerialNumber:(id)arg1 contentType:(unsigned long long)arg2;

@end

