//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSData, NSNumber, NSString;

@interface SCSpectaclesCalibration : NSObject <NSSecureCoding, NSCopying>
{
    NSData *_data;
    NSString *_serialNumber;
    NSNumber *_majorVersion;
    NSNumber *_minorVersion;
}

+ (_Bool)supportsSecureCoding;
+ (id)calibrationWithNewportData:(id)arg1 serialNumber:(id)arg2;
@property(readonly, copy, nonatomic) NSNumber *minorVersion; // @synthesize minorVersion=_minorVersion;
@property(readonly, copy, nonatomic) NSNumber *majorVersion; // @synthesize majorVersion=_majorVersion;
@property(readonly, copy, nonatomic) NSString *serialNumber; // @synthesize serialNumber=_serialNumber;
@property(readonly, copy, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithData:(id)arg1 majorVersion:(id)arg2 minorVersion:(id)arg3 serialNumber:(id)arg4;

@end

