//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSMutableSet;

@interface SCSpectaclesContentStore : NSObject <NSCoding>
{
    NSArray *_content;
    NSMutableSet *_internalContent;
}

@property(retain, nonatomic) NSMutableSet *internalContent; // @synthesize internalContent=_internalContent;
@property(copy) NSArray *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (id)contentWithName:(id)arg1;
- (void)removeAllContent;
- (void)removeContent:(id)arg1;
- (void)addContent:(id)arg1;
- (id)undownloadedContentForComponent:(unsigned long long)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

