//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCSpectaclesECDH.h"

@interface SCSpectaclesPrime256V1ECDH : SCSpectaclesECDH
{
    struct ECDH *_ecdh;
}

@property(nonatomic) struct ECDH *ecdh; // @synthesize ecdh=_ecdh;
- (id)generateEncryptionKey:(id)arg1;
- (id)generateSharedSecret:(id)arg1;
- (id)generatePublicKey;
- (void)dealloc;
- (id)init;

@end

