//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCSpectaclesPairingBLEAuthenticator.h"

@class NSData, NSString, SCSpectaclesECDH, SCSpectaclesRequestMessage, SCSpectaclesWhiteboxAuthenticator;

@interface SCSpectaclesPairingMalibuBLEAuthenticator : NSObject <SCSpectaclesPairingBLEAuthenticator>
{
    _Bool _disableEncryption;
    _Bool _disableProdAuthentication;
    _Bool _useV3Protocol;
    _Bool _triedProdKey;
    _Bool _triedDevKey;
    id <SCSpectaclesPairingBLEAuthenticatorDelegate> _delegate;
    SCSpectaclesECDH *_ecdh;
    SCSpectaclesWhiteboxAuthenticator *_authenticator;
    NSData *_appNonce;
    NSData *_peerNonce;
    NSData *_sharedSecret;
    SCSpectaclesRequestMessage *_peerVerificationRequest;
}

@property(nonatomic) _Bool triedDevKey; // @synthesize triedDevKey=_triedDevKey;
@property(nonatomic) _Bool triedProdKey; // @synthesize triedProdKey=_triedProdKey;
@property(retain, nonatomic) SCSpectaclesRequestMessage *peerVerificationRequest; // @synthesize peerVerificationRequest=_peerVerificationRequest;
@property(retain, nonatomic) NSData *sharedSecret; // @synthesize sharedSecret=_sharedSecret;
@property(retain, nonatomic) NSData *peerNonce; // @synthesize peerNonce=_peerNonce;
@property(retain, nonatomic) NSData *appNonce; // @synthesize appNonce=_appNonce;
@property(retain, nonatomic) SCSpectaclesWhiteboxAuthenticator *authenticator; // @synthesize authenticator=_authenticator;
@property(retain, nonatomic) SCSpectaclesECDH *ecdh; // @synthesize ecdh=_ecdh;
@property(nonatomic) __weak id <SCSpectaclesPairingBLEAuthenticatorDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool useV3Protocol; // @synthesize useV3Protocol=_useV3Protocol;
@property(nonatomic) _Bool disableProdAuthentication; // @synthesize disableProdAuthentication=_disableProdAuthentication;
@property(nonatomic) _Bool disableEncryption; // @synthesize disableEncryption=_disableEncryption;
- (void).cxx_destruct;
- (void)handleResponse:(id)arg1;
- (void)_tryPeerVerification;
- (void)startConnecting;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

