//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData, NSString;

@interface SCSSMCardDebugInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *debugHtml; // @dynamic debugHtml;
@property(copy, nonatomic) NSData *debugPb; // @dynamic debugPb;
@property(nonatomic) unsigned long long numImpressions; // @dynamic numImpressions;
@property(nonatomic) unsigned long long numLongImpressions; // @dynamic numLongImpressions;
@property(nonatomic) unsigned long long numRawWatches; // @dynamic numRawWatches;
@property(copy, nonatomic) NSString *onDemandDebugKey; // @dynamic onDemandDebugKey;
@property(nonatomic) int visualElement; // @dynamic visualElement;

@end

