//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface SCSSMSectionConfig : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) unsigned long long cacheTtlMsecs; // @dynamic cacheTtlMsecs;
@property(nonatomic) _Bool shouldRefreshIfAllRead; // @dynamic shouldRefreshIfAllRead;

@end

