//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt32Int32Dictionary;

@interface SCSSMPivotPrefetchMetadata : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPBInt32Int32Dictionary *numPrefetchedStories; // @dynamic numPrefetchedStories;
@property(readonly, nonatomic) unsigned long long numPrefetchedStories_Count; // @dynamic numPrefetchedStories_Count;

@end

