//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SOJUStickerPack, SOJUStickerPackMetadata;

@interface SCStickerPack : NSObject
{
    SOJUStickerPack *_pack;
    SOJUStickerPackMetadata *_metadata;
}

@property(readonly, nonatomic) SOJUStickerPackMetadata *metadata; // @synthesize metadata=_metadata;
@property(readonly, nonatomic) SOJUStickerPack *pack; // @synthesize pack=_pack;
- (void).cxx_destruct;
- (id)initWithPack:(id)arg1 metadata:(id)arg2;

@end

