//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface SCStickerPackTrackingToken : NSObject
{
    NSString *_packID;
    NSDate *_startDate;
}

@property(copy, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property(copy, nonatomic) NSString *packID; // @synthesize packID=_packID;
- (void).cxx_destruct;
- (long long)millisecondsSinceStart;

@end

