//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCStickerStoryReplyExperimentContext : SCExperimentContext
{
    _Bool _shouldShowStickerStoryReplyViewInSnap;
    _Bool _shouldShowStickerStoryReplyViewInStory;
}

@property(readonly, nonatomic) _Bool shouldShowStickerStoryReplyViewInStory; // @synthesize shouldShowStickerStoryReplyViewInStory=_shouldShowStickerStoryReplyViewInStory;
@property(readonly, nonatomic) _Bool shouldShowStickerStoryReplyViewInSnap; // @synthesize shouldShowStickerStoryReplyViewInSnap=_shouldShowStickerStoryReplyViewInSnap;
- (void)setupParameters;
- (id)experimentName;

@end

