//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCCircumstanceEngineServices, SCServicesExposer;

@interface SCStoriesCircumstanceEngineServicesEntryPoint : SCEntryPoint
{
    SCCircumstanceEngineServices *_circumstanceEngineServices;
    SCServicesExposer *_storiesCircumstanceEngineServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *storiesCircumstanceEngineServicesExposer; // @synthesize storiesCircumstanceEngineServicesExposer=_storiesCircumstanceEngineServicesExposer;
@property(nonatomic) __weak SCCircumstanceEngineServices *circumstanceEngineServices; // @synthesize circumstanceEngineServices=_circumstanceEngineServices;
- (void).cxx_destruct;
- (void)begin;

@end

