//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet, SCStartupCommand;

@protocol SCStartupCommandDependencyProtocol <NSObject>
- (void)upgradeCommandPriority:(SCStartupCommand *)arg1 priority:(unsigned long long)arg2;
- (NSSet *)dependencySetForCommand:(SCStartupCommand *)arg1;
- (void)markCommandHasNoDependency:(SCStartupCommand *)arg1;
- (void)markCommand:(SCStartupCommand *)arg1 dependUpon:(SCStartupCommand *)arg2;
@end

