//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCUserToolTipStatus;

@interface SCStoryUserProperties : NSObject
{
    SCUserToolTipStatus *_toolTipStatus;
}

- (void).cxx_destruct;
- (void)_updateToolTipStatus;
- (void)setSeenOnboardingOverlay;
- (_Bool)hasSeenOnboardingOverlay;
- (void)setHasSeenStoryLeftTapOnboarding;
- (_Bool)hasSeenStoryLeftTapOnboarding;
- (void)setHasSeenAutoAdvanceOverlay;
- (_Bool)hasSeenAutoAdvanceTooltip;
- (id)initWithUserToolTipStatus:(id)arg1;

@end

