//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue_attr>;

@interface SCStreamingKeyedPerformer : NSObject
{
    NSObject<OS_dispatch_queue_attr> *_queueType;
    unsigned int _qos;
    id <SCPerforming> _performer;
    NSMutableDictionary *_performersByKey;
    NSMutableDictionary *_performerReferenceCountsByKey;
}

- (void).cxx_destruct;
- (void)_releasePerformerForKey:(id)arg1;
- (id)_acquirePerformerForKey:(id)arg1;
- (void)performWithBarrierForKey:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)performForKey:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)initWithQueueType:(id)arg1 qos:(unsigned int)arg2;

@end

