//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDate, SCStoriesThumbnailInfo;

@protocol SCStoriesThumbnailCaching <NSObject>
- (void)addThumbnail:(SCStoriesThumbnailInfo *)arg1 thumbnailMedia:(NSData *)arg2 expirationDate:(NSDate *)arg3 completionBlock:(void (^)(void))arg4;
@end

