//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCStickerFileSystemUtils : NSObject
{
}

+ (long long)compareVersion:(id)arg1 toVersion:(id)arg2;
+ (id)_appVersion;
+ (void)clearDirectoryIfNecessary:(id)arg1;
+ (id)_rootPath;
+ (id)absolutePathForPath:(id)arg1;
+ (_Bool)unzipData:(id)arg1 destination:(id)arg2;
+ (_Bool)saveData:(id)arg1 destination:(id)arg2;
+ (_Bool)removeFile:(id)arg1;
+ (_Bool)createFolder:(id)arg1;

@end

