//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCLogger;

@interface SCStoryInviteLogger : NSObject
{
    SCLogger *_logger;
}

- (void).cxx_destruct;
- (void)logStoryInviteAcceptForStoryId:(id)arg1 inviteId:(id)arg2;
- (void)logStoryInviteCreationForStoryId:(id)arg1 inviteId:(id)arg2;
- (id)initWithLogger:(id)arg1;

@end

