//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SCSUPSalientTermScore : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *canonicalName; // @dynamic canonicalName;
@property(copy, nonatomic) NSString *displayName; // @dynamic displayName;
@property(nonatomic) unsigned int id_p; // @dynamic id_p;
@property(nonatomic) float score; // @dynamic score;

@end

