//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface SCSUPLensEngagementStats_ActionCounts : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) unsigned int numScans; // @dynamic numScans;
@property(nonatomic) unsigned int numShares; // @dynamic numShares;
@property(nonatomic) unsigned int numSnapRecipients; // @dynamic numSnapRecipients;
@property(nonatomic) unsigned int numSnapSaves; // @dynamic numSnapSaves;
@property(nonatomic) unsigned int numSnapViews; // @dynamic numSnapViews;
@property(nonatomic) unsigned int numSnapsSend; // @dynamic numSnapsSend;
@property(nonatomic) unsigned int numStoryPosts; // @dynamic numStoryPosts;
@property(nonatomic) unsigned int numStoryViews; // @dynamic numStoryViews;
@property(nonatomic) unsigned int numUnlocks; // @dynamic numUnlocks;
@property(nonatomic) unsigned int snapViewInSecs; // @dynamic snapViewInSecs;
@property(nonatomic) unsigned int storyViewInSecs; // @dynamic storyViewInSecs;

@end

