//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SCSUPABExperimentsRequest_AppInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *appBuild; // @dynamic appBuild;
@property(copy, nonatomic) NSString *appVariant; // @dynamic appVariant;
@property(copy, nonatomic) NSString *appVersion; // @dynamic appVersion;
@property(copy, nonatomic) NSString *osType; // @dynamic osType;
@property(copy, nonatomic) NSString *osVersion; // @dynamic osVersion;

@end

