//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt64ObjectDictionary;

@interface SCSUPLensEngagement : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPBInt64ObjectDictionary *lensStats; // @dynamic lensStats;
@property(readonly, nonatomic) unsigned long long lensStats_Count; // @dynamic lensStats_Count;

@end

