//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCInteractiveSwipeTransitionControllerDataSource.h"
#import "SCInteractiveSwipeTransitionControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSString, SCInteractiveSwipeTransitionController, SCSwipeTransitionController, UIViewController;

@interface SCSwipeTransitionCoordinator : NSObject <SCInteractiveSwipeTransitionControllerDataSource, UIViewControllerTransitioningDelegate, UINavigationControllerDelegate, SCInteractiveSwipeTransitionControllerDelegate>
{
    unsigned long long _transitionMode;
    long long _navigationOperation;
    UIViewController *_presentedViewController;
    SCSwipeTransitionController *_animationController;
    id <SCSwipeTransitionCoordinatorDelegate> _delegate;
    id <SCSwipeTransitionCoordinatorDataSource> _dataSource;
    unsigned long long _presentationDirection;
    unsigned long long _dismissDirection;
    SCInteractiveSwipeTransitionController *_interactivePresentationController;
    SCInteractiveSwipeTransitionController *_interactiveDismissController;
}

@property(readonly, nonatomic) SCInteractiveSwipeTransitionController *interactiveDismissController; // @synthesize interactiveDismissController=_interactiveDismissController;
@property(readonly, nonatomic) SCInteractiveSwipeTransitionController *interactivePresentationController; // @synthesize interactivePresentationController=_interactivePresentationController;
@property(readonly, nonatomic) unsigned long long dismissDirection; // @synthesize dismissDirection=_dismissDirection;
@property(readonly, nonatomic) unsigned long long presentationDirection; // @synthesize presentationDirection=_presentationDirection;
@property(nonatomic) __weak id <SCSwipeTransitionCoordinatorDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <SCSwipeTransitionCoordinatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_setupPresentedViewControllerForTransition;
- (id)presentingViewController;
- (id)presentationControllerForPresentedViewController:(id)arg1 presentingViewController:(id)arg2 sourceViewController:(id)arg3;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
- (void)performModalTransitionWithViewController:(id)arg1 withTransitionType:(unsigned long long)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (id)passthroughViews;
- (void)_didFinishTransitionWithTransitionType:(unsigned long long)arg1 interactive:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)performTransitionWithViewController:(id)arg1 withTransitionType:(unsigned long long)arg2 direction:(unsigned long long)arg3 animationDuration:(double)arg4 interactive:(_Bool)arg5 completion:(CDUnknownBlockType)arg6;
- (_Bool)shouldTransitionWithTransitionType:(unsigned long long)arg1 gestureRecognizer:(id)arg2 interactive:(_Bool)arg3;
- (void)swipeTransitionController:(id)arg1 transitionViewController:(id)arg2 withTransitionType:(unsigned long long)arg3 direction:(unsigned long long)arg4 completion:(CDUnknownBlockType)arg5;
- (_Bool)shouldBeginTransitionWithSwipeTransitionController:(id)arg1 gestureRecognizer:(id)arg2;
- (id)presentingViewControllerWithSwipeTransitionController:(id)arg1;
- (id)presentedViewControllerWithSwipeTransitionController:(id)arg1;
- (_Bool)transitionController:(id)arg1 transitionType:(unsigned long long)arg2 shouldAllowGesture:(id)arg3 toRecognizeSimultaneouslyWith:(id)arg4;
- (void)swipeTransitionController:(id)arg1 willFailWithTransitionType:(unsigned long long)arg2;
- (void)swipeTransitionController:(id)arg1 didFinishWithTransitionType:(unsigned long long)arg2;
- (void)swipeTransitionController:(id)arg1 didBeginWithTransitionType:(unsigned long long)arg2;
- (void)swipeTransitionController:(id)arg1 willBeginWithTransitionType:(unsigned long long)arg2;
- (void)_completeDismissViewControllerWithCompletion:(CDUnknownBlockType)arg1;
- (void)dismissViewControllerAnimationDuration:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentViewController:(id)arg1 animationDuration:(double)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) _Bool isTransitioning;
@property(readonly, nonatomic) _Bool isPresenting;
@property(readonly, nonatomic) double percentPresented;
- (id)initWithDirection:(unsigned long long)arg1 transitionMode:(unsigned long long)arg2;
- (id)initWithPresentationDirection:(unsigned long long)arg1 dismissalDirection:(unsigned long long)arg2 transitionMode:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

