//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCTermsOfUsePageRouter.h"

@class NSString, SCLogger, SCPrivacyPolicyViewController, SCTermsOfUseViewController, SCUserSession, UINavigationController;

@interface SCTermsOfUseNavigationPageRouter : NSObject <SCTermsOfUsePageRouter>
{
    SCUserSession *_userSession;
    UINavigationController *_navigationController;
    SCLogger *_logger;
    id <SCOnboardingResourceDownloader> _resourceDownloader;
    SCTermsOfUseViewController *_termsOfUseViewController;
    SCPrivacyPolicyViewController *_privacyPolicyViewController;
}

- (void).cxx_destruct;
- (void)dismissPrivacyPolicyPage;
- (void)showPrivacyPolicyWithUserActionDelegate:(id)arg1;
- (void)dismissTermsOfUsePage;
- (void)showTermsOfUseV7WithUserActionDelegate:(id)arg1;
- (void)showTermsOfUseV8WithUserActionDelegate:(id)arg1;
- (id)initWithUserSession:(id)arg1 navigationController:(id)arg2 logger:(id)arg3 resourceDownloader:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

