//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCThrottleTimer;

@interface SCThrottleTarget : NSObject
{
    id _target;
    SEL _selector;
    SCThrottleTimer *_throttleTimer;
}

@property(nonatomic) __weak SCThrottleTimer *throttleTimer; // @synthesize throttleTimer=_throttleTimer;
@property(nonatomic) SEL selector; // @synthesize selector=_selector;
@property(nonatomic) __weak id target; // @synthesize target=_target;
- (void).cxx_destruct;
- (void)fire;
- (void)onTimer:(id)arg1;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 throttleTimer:(id)arg3;

@end

