//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCTLocalMediaView, UIView;

@protocol SCTLocalMediaViewListener <NSObject>
- (void)localMediaView:(SCTLocalMediaView *)arg1 didMoveToSuperview:(UIView *)arg2;
- (void)localMediaView:(SCTLocalMediaView *)arg1 willMoveToSuperview:(UIView *)arg2;
- (void)mediaChangedInLocalMediaView:(SCTLocalMediaView *)arg1;
@end

