//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage;

@protocol SCTPresenceBitmoji <NSObject>
@property(readonly, nonatomic) double actualBodyWidth;
@property(readonly, nonatomic) UIImage *typingArmImage;
@property(readonly, nonatomic) UIImage *typingBodyImage;
@property(readonly, nonatomic) UIImage *rightHandImage;
@property(readonly, nonatomic) UIImage *leftHandImage;
@property(readonly, nonatomic) UIImage *upperBodyImage;
@end

