//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, SCTV3SessionWrapper, TCV3SessionState;

@protocol SCTV3SessionWrapperListener <NSObject>
- (void)sessionWrapper:(SCTV3SessionWrapper *)arg1 changedState:(TCV3SessionState *)arg2 reason:(long long)arg3;

@optional
- (void)sessionWrapper:(SCTV3SessionWrapper *)arg1 updatedSpeechActivity:(NSArray *)arg2;
- (void)callIncompatible:(NSArray *)arg1;
- (void)sessionWrapperDisposed:(SCTV3SessionWrapper *)arg1;
@end

