//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSNumber, NSString, SOJUGeofilterResponse;

@interface SCUnlockableBuilder : NSObject
{
    long long _source;
    NSDate *_creationDate;
    SOJUGeofilterResponse *_raw;
    NSNumber *_overrideAssetTtl;
    long long _eligibility;
    NSString *_unlockableId;
    _Bool _isSponsored;
}

+ (id)withUnlockable:(id)arg1;
- (void).cxx_destruct;
- (id)setIsSponsored:(_Bool)arg1;
- (id)setUnlockableId:(id)arg1;
- (id)setEligibility:(long long)arg1;
- (id)setOverrideAssetTtl:(id)arg1;
- (id)setRaw:(id)arg1;
- (id)setCreationDate:(id)arg1;
- (id)setSource:(long long)arg1;
- (id)build;

@end

