//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCUnifiedProfileViewLayoutConfiguration : NSObject
{
    double _contentCollectionViewBottomContentInset;
    double _profileViewCardHeight;
}

@property(readonly, nonatomic) double profileViewCardHeight; // @synthesize profileViewCardHeight=_profileViewCardHeight;
@property(readonly, nonatomic) struct UIEdgeInsets contentCollectionViewContentInset;
@property(readonly, nonatomic) double contentCollectionViewTopPadding;
@property(readonly, nonatomic) double headerHeight;
- (id)initWithProfileViewCardHeight:(double)arg1 contentCollectionViewBottomContentInset:(double)arg2;

@end

