//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCSnapAdsNetworkUserAgent, SCSnapAdsSerializingNetworkManager, SCSnapAdsUser;

@interface SCUnlockableAdTracker : NSObject
{
    SCSnapAdsUser *_adUser;
    SCSnapAdsNetworkUserAgent *_userAgent;
    SCSnapAdsSerializingNetworkManager *_networkManager;
    id <SCSnapAdsOperationMetricsAdapter> _metricsManager;
}

- (void).cxx_destruct;
- (void)_submitTrackRequest:(id)arg1 debugViewParams:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (void)trackUnlockableAd:(id)arg1;
- (id)initWithAdUser:(id)arg1 userAgent:(id)arg2 networkManager:(id)arg3 metricsManager:(id)arg4;

@end

