//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCActionable.h"

@class NSString, SCUnifiedActionMenuContextualItemAccessoryViewModel;

@interface SCUnifiedActionMenuContextualMenuItemAccessoryView : UIView <SCActionable>
{
    UIView *_accessoryView;
    SCUnifiedActionMenuContextualItemAccessoryViewModel *_viewModel;
    id <SCActionHandling> _actionHandler;
}

@property(retain, nonatomic) id <SCActionHandling> actionHandler; // @synthesize actionHandler=_actionHandler;
- (void).cxx_destruct;
- (void)_handleTapActionWithActionModel:(id)arg1;
- (void)_handleTapAction;
- (void)_updateAccessoryViewWithImageViewModel:(id)arg1;
- (void)_updateAccessoryViewWithActionButonViewModel:(id)arg1;
- (void)setViewModel:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

