//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class SCSearchActionButtonViewModel, SCUnifiedActionMenuContextualItemAccessoryImageViewModel;

@interface SCUnifiedActionMenuContextualItemAccessoryViewModel : NSObject <NSCopying>
{
    unsigned long long _subtype;
    SCSearchActionButtonViewModel *_button_buttonAccessoryViewModel;
    SCUnifiedActionMenuContextualItemAccessoryImageViewModel *_image_imageAccessoryViewModel;
}

+ (id)imageWithImageAccessoryViewModel:(id)arg1;
+ (id)buttonWithButtonAccessoryViewModel:(id)arg1;
- (void).cxx_destruct;
- (void)matchButton:(CDUnknownBlockType)arg1 image:(CDUnknownBlockType)arg2;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

