//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCOurStoriesAttributionListener.h"
#import "SCUnifiedActionMenuDataProvider.h"
#import "SCUpdateListener.h"

@class NSString, SCExperimentManager, SCLazy, SCUnifiedProfileMyStoriesDataSourceManager;

@interface SCUnifiedProfileMyStoriesActionMenuDataProvider : NSObject <SCUpdateListener, SCOurStoriesAttributionListener, SCUnifiedActionMenuDataProvider>
{
    SCUnifiedProfileMyStoriesDataSourceManager *_storiesDataSourceManager;
    long long _storyType;
    NSString *_storyIdentifier;
    unsigned long long _unifiedProfileType;
    SCExperimentManager *_experimentManager;
    SCLazy *_ourStoriesAttributionManager;
    id <SCUnifiedActionMenuDataProviderDelegate> _delegate;
}

@property(nonatomic) __weak id <SCUnifiedActionMenuDataProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didUpdateOurStoriesAttributionEnabled:(_Bool)arg1;
- (void)didUpdateWithAnnouncerIdentifier:(id)arg1;
- (void)updateViewModelWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)initWithStoriesDataSourceManager:(id)arg1 storyType:(long long)arg2 storyIdentifier:(id)arg3 unifiedProfileType:(unsigned long long)arg4 experimentManager:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

