//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface SCUnifiedProfileStoriesListCellCountsViewModel : NSObject <NSCopying>
{
    unsigned long long _viewCount;
    unsigned long long _screenshotCount;
}

@property(readonly, nonatomic) unsigned long long screenshotCount; // @synthesize screenshotCount=_screenshotCount;
@property(readonly, nonatomic) unsigned long long viewCount; // @synthesize viewCount=_viewCount;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithViewCount:(unsigned long long)arg1 screenshotCount:(unsigned long long)arg2;

@end

