//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCLogger, SCQueuePerformer;

@interface SCUpNextBlizzardEventLogger : NSObject
{
    SCLogger *_logger;
    SCQueuePerformer *_performer;
}

- (void).cxx_destruct;
- (void)upNextDidSendEvent:(id)arg1 properties:(id)arg2;
- (void)upNextDidUpdateItemsWithOrderedVisibleItemIds:(id)arg1;
- (void)upNextDidAwakeWithAction:(long long)arg1;
- (void)upNextDidNavigateToItemWithItemId:(id)arg1 orderedVisibleItemIds:(id)arg2 action:(long long)arg3;
- (id)initWithPerformer:(id)arg1;
- (id)initWithLogger:(id)arg1 performer:(id)arg2;

@end

