//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCCheckInOption, UIViewController<SCVenueFeedbackViewControllerDelegate>;

@protocol SCVenueReporter <NSObject>
- (void)presentReportVenueViewWithViewController:(UIViewController<SCVenueFeedbackViewControllerDelegate> *)arg1 venue:(SCCheckInOption *)arg2;
- (void)reportVenue:(SCCheckInOption *)arg1;
@end

