//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class AVAsset, NSDate, NSURL, SCImageProcessVideoExportStaticFrameConfig, UIImage;

@protocol SCVideoTranscodingInputMediaProvider <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) AVAsset *inputImageAudioAsset;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) unsigned long long frameRate;
@property(readonly, copy, nonatomic) UIImage *inputImage;
@property(readonly, copy, nonatomic) SCImageProcessVideoExportStaticFrameConfig *staticFrameConfig;
@property(readonly, copy, nonatomic) NSDate *videoCreateTimeUtc;
@property(readonly, nonatomic) double videoPlaybackRate;
@property(readonly, nonatomic) struct CGAffineTransform videoTransform;
@property(readonly, nonatomic) long long videoOrientation;
@property(readonly, copy, nonatomic) NSURL *rawVideoDataURL;
@property(readonly, copy, nonatomic) AVAsset *inputVideoAsset;
@end

