//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCVSClientUpdate;

@interface SCVSClientUpdateRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasUpdate; // @dynamic hasUpdate;
@property(retain, nonatomic) SCVSClientUpdate *update; // @dynamic update;

@end

