//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCDownloadableContent.h"

@class NSString;

@interface SCWeatherFilterDownloadableImageAssets : SCDownloadableContent
{
    long long _scale;
    NSString *_folderName;
}

+ (id)shared;
- (void).cxx_destruct;
- (id)pathForImageName:(id)arg1;
- (id)eventUniqueId;
- (id)resourceName;
- (id)fileNames;
- (id)directoryName;
- (id)init;

@end

