//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, SCWebImageScraperClient, UIImage;

@protocol SCWebImageScraperClientDelegate <NSObject>
- (void)webImageScraperClient:(SCWebImageScraperClient *)arg1 receivedTitle:(NSString *)arg2 forPageUrl:(NSURL *)arg3;
- (void)webImageScraperClientDidNotReceiveImageLinks:(SCWebImageScraperClient *)arg1;
- (void)webImageScraperClientDidReceive:(SCWebImageScraperClient *)arg1 image:(UIImage *)arg2 imageIdentifier:(NSString *)arg3 pageIdentifier:(NSString *)arg4;
@end

