//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDictionary, SCWebProxyRequest, SCWebProxyResponseHeadersTransformLayer;

@protocol SCWebProxyResponseHeadersTransformLayerDelegate
- (NSDictionary *)proxyResponseHeadersTransformLayer:(SCWebProxyResponseHeadersTransformLayer *)arg1 transformResponseHeaders:(NSDictionary *)arg2 forProxyRequest:(SCWebProxyRequest *)arg3;
- (_Bool)proxyResponseHeadersTransformLayer:(SCWebProxyResponseHeadersTransformLayer *)arg1 shouldTransformResponseHeadersForProxyRequest:(SCWebProxyRequest *)arg2;
@end

