//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCPageNameLogging.h"

@class NSString;

@interface SCWrapperPageNameViewController : UIViewController <SCPageNameLogging>
{
    NSString *_pageViewName;
    _Bool _shouldAutorotate;
    unsigned long long _supportedInterfaceOrientations;
}

- (void).cxx_destruct;
- (id)pageViewName;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (id)initWithPageViewName:(id)arg1 shouldAutorotate:(_Bool)arg2 supportedInterfaceOrientations:(unsigned long long)arg3;
- (id)initWithPageViewName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

