//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SDMPackaging_Overlay : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int docking; // @dynamic docking;
@property(copy, nonatomic) NSString *filename; // @dynamic filename;
@property(nonatomic) int zIndex; // @dynamic zIndex;

@end

