//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSOrderedSet, SCDisposableObserverLifecycle, SCScriptIndexer;

@interface SIGSectionFastIndexer : NSObject
{
    NSOrderedSet *_alphabeticalIndexes;
    NSOrderedSet *_predefinedSections;
    CDUnknownBlockType _indexKeyToSectionMapper;
    NSObject<OS_dispatch_queue> *_lock;
    SCScriptIndexer *_scriptIndexer;
    SCDisposableObserverLifecycle *_subscription;
}

- (void).cxx_destruct;
- (void)_onNextSortedEntities:(id)arg1;
- (id)rowBasedIndexPathForKey:(id)arg1;
- (id)sectionBasedIndexPathForKey:(id)arg1;
- (id)initWithIndexEntityObservableRepository:(id)arg1 alphabeticalIndexes:(id)arg2 predefinedSections:(id)arg3 indexKeyToSectionMapper:(CDUnknownBlockType)arg4;

@end

