//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SIGIndexViewDelegate.h"

@class NSString, SIGIndexViewProvider, SIGRecipientCollectionViewCellIndexer, SIGSectionFastIndexer, UICollectionView;

@interface SIGSectionIndexViewSynchronizer : NSObject <SIGIndexViewDelegate>
{
    UICollectionView *_collectionView;
    SIGIndexViewProvider *_indexViewProvider;
    SIGSectionFastIndexer *_fastIndexer;
    double _verticalOffset;
    SIGRecipientCollectionViewCellIndexer *_cellIndexer;
    long long _lastIndex;
    _Bool _aggregated;
}

@property(nonatomic, getter=isAggregated) _Bool aggregated; // @synthesize aggregated=_aggregated;
- (void).cxx_destruct;
- (void)indexView:(id)arg1 userDidSelectTitleAtIndex:(long long)arg2;
- (void)scrollViewDidScroll;
- (id)initWithCollectionView:(id)arg1 indexViewProvider:(id)arg2 fastIndexer:(id)arg3 verticalOffset:(double)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

