//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSNumber, NSString;

@protocol SOJUAstSignal <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSNumber *identifier;
@property(readonly, copy, nonatomic) NSNumber *value;
@property(readonly, copy, nonatomic) NSString *version;
@property(readonly, copy, nonatomic) NSString *type;
@property(readonly, copy, nonatomic) NSString *descriptionValue;
@property(readonly, copy, nonatomic) NSString *name;
@end

