//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSNumber;

@protocol SOJUCommerceCustomImageFrame <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSNumber *frameWidth;
@property(readonly, copy, nonatomic) NSNumber *frameHeight;
@property(readonly, copy, nonatomic) NSNumber *topLeftY;
@property(readonly, copy, nonatomic) NSNumber *topLeftX;
@end

