//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@interface SOJUGalleryPointBuilder : NSObject
{
    NSNumber *_x;
    NSNumber *_y;
}

+ (id)withJUGalleryPoint:(id)arg1;
- (void).cxx_destruct;
- (id)setY:(id)arg1;
- (id)setX:(id)arg1;
- (id)build;
- (id)setYValue:(double)arg1;
- (id)setXValue:(double)arg1;

@end

