//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSDictionary, NSString;

@protocol SOJUTalkAuthContext <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSDictionary *userIdToTalkParticipantId;
@property(readonly, copy, nonatomic) NSString *sessionId;
@property(readonly, copy, nonatomic) NSString *sessionType;
@property(readonly, copy, nonatomic) NSDictionary *usernameToUserId;
@property(readonly, copy, nonatomic) NSString *token;
@property(readonly, copy, nonatomic) NSString *mac;
@property(readonly, copy, nonatomic) NSString *scopeId;
@property(readonly, copy, nonatomic) NSString *conversationId;
@end

