//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSArray;

@protocol SOJUAirPreferenceInfo <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSArray *featureSetting;
@property(readonly, copy, nonatomic) NSArray *serverSetting;
@property(readonly, copy, nonatomic) NSArray *tweak;
@property(readonly, copy, nonatomic) NSArray *setting;
@property(readonly, copy, nonatomic) NSArray *experiment;
@end

