//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSNumber, NSString;

@protocol SOJUSnapCreatorAttribution <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSString *attachment;
@property(readonly, copy, nonatomic) NSString *editionId;
@property(readonly, copy, nonatomic) NSString *creatorUsername;
@property(readonly, copy, nonatomic) NSString *logoUrl;
@property(readonly, copy, nonatomic) NSNumber *visibility;
@property(readonly, copy, nonatomic) NSNumber *originalTimestamp;
@property(readonly, copy, nonatomic) NSString *originalStoryId;
@property(readonly, copy, nonatomic) NSString *creatorDisplayName;
@property(readonly, copy, nonatomic) NSNumber *creatorType;
@property(readonly, copy, nonatomic) NSString *creatorId;
@end

