//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"
#import "SOJUDeviceTokenAuthPayload.h"

@class NSArray, NSNumber, NSString;

@protocol SOJUIdentityFindFriendsRequest <NSObject, NSCoding, NSCopying, SOJUDeviceTokenAuthPayload>
@property(readonly, copy, nonatomic) NSNumber *signUpTapTimeStamp;
@property(readonly, copy, nonatomic) NSString *source;
@property(readonly, copy, nonatomic) NSNumber *isFullSync;
@property(readonly, copy, nonatomic) NSNumber *shouldRecommend;
@property(readonly, copy, nonatomic) NSArray *contactsWithMetaData;
@property(readonly, copy, nonatomic) NSString *countryCode;
@property(readonly, copy, nonatomic) NSString *numbers;
@property(readonly, copy, nonatomic) NSString *username;
@property(readonly, copy, nonatomic) NSString *reqToken;
@property(readonly, copy, nonatomic) NSString *timestamp;
@property(readonly, copy, nonatomic) NSString *dsig;
@property(readonly, copy, nonatomic) NSString *dtoken1i;
@end

