//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SOJUBroadcastMobsApiGetMobStoriesRequestBuilder : NSObject
{
    NSArray *_ids;
}

+ (id)withJUBroadcastMobsApiGetMobStoriesRequest:(id)arg1;
- (void).cxx_destruct;
- (id)setIds:(id)arg1;
- (id)build;

@end

