//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SOJUGalleryMentionStickerStyleBuilder : NSObject
{
    NSString *_userId;
    NSString *_username;
    NSString *_type;
}

+ (id)withJUGalleryMentionStickerStyle:(id)arg1;
- (void).cxx_destruct;
- (id)setType:(id)arg1;
- (id)setUsername:(id)arg1;
- (id)setUserId:(id)arg1;
- (id)build;
- (id)setTypeEnum:(long long)arg1;

@end

