//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSArray, NSNumber, NSString;

@protocol SOJUGalleryServletGalleryEntry <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSNumber *entrySource;
@property(readonly, copy, nonatomic) NSString *externalId;
@property(readonly, copy, nonatomic) NSNumber *lastAutosaveTime;
@property(readonly, copy, nonatomic) NSNumber *isPrivate;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, copy, nonatomic) NSNumber *status;
@property(readonly, copy, nonatomic) NSNumber *createTime;
@property(readonly, copy, nonatomic) NSArray *highlightedSnapIds;
@property(readonly, copy, nonatomic) NSArray *snaps;
@property(readonly, copy, nonatomic) NSNumber *entryType;
@property(readonly, copy, nonatomic) NSNumber *seqNum;
@property(readonly, copy, nonatomic) NSString *entryId;
@end

