//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSNumber, NSString;

@protocol SOJULastMischiefContent <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSString *firstMediaType;
@property(readonly, copy, nonatomic) NSNumber *viewedTimestamp;
@property(readonly, copy, nonatomic) NSString *messageBodyType;
@property(readonly, copy, nonatomic) NSNumber *senderMessageSeqNum;
@property(readonly, copy, nonatomic) NSNumber *sentTimestamp;
@property(readonly, copy, nonatomic) NSString *senderUsername;
@end

