//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableString;

@interface SPMutableString : NSObject
{
    NSMutableString *_internalString;
}

@property(retain, nonatomic) NSMutableString *internalString; // @synthesize internalString=_internalString;
- (void).cxx_destruct;
- (id)let_dot;
- (id)let_underscore;
- (id)let_greater_than;
- (id)let_less_than;
- (id)let_bar;
- (id)let_bracket_right;
- (id)let_bracket_left;
- (id)let_curly_right;
- (id)let_curly_left;
- (id)let_forward_slash;
- (id)let_back_slash;
- (id)let_question_mark;
- (id)let_exclamation;
- (id)let_at;
- (id)let_pound;
- (id)let_$;
- (id)let_percent;
- (id)let_caret;
- (id)let_ampersand;
- (id)let_asterisk;
- (id)let_paren_right;
- (id)let_paren_left;
- (id)let_equals;
- (id)let_plus;
- (id)let_quotation;
- (id)let_apostrophe;
- (id)let_colon;
- (id)let_semicolon;
- (id)let_comma;
- (id)let_dash;
- (id)let_point;
- (id)let_space;
- (id)let_0;
- (id)let_9;
- (id)let_8;
- (id)let_7;
- (id)let_6;
- (id)let_5;
- (id)let_4;
- (id)let_3;
- (id)let_2;
- (id)let_1;
- (id)let_Z;
- (id)let_Y;
- (id)let_X;
- (id)let_W;
- (id)let_V;
- (id)let_U;
- (id)let_T;
- (id)let_S;
- (id)let_R;
- (id)let_Q;
- (id)let_P;
- (id)let_O;
- (id)let_N;
- (id)let_M;
- (id)let_L;
- (id)let_K;
- (id)let_J;
- (id)let_I;
- (id)let_H;
- (id)let_G;
- (id)let_F;
- (id)let_E;
- (id)let_D;
- (id)let_C;
- (id)let_B;
- (id)let_A;
- (id)let_z;
- (id)let_y;
- (id)let_x;
- (id)let_w;
- (id)let_v;
- (id)let_u;
- (id)let_t;
- (id)let_s;
- (id)let_r;
- (id)let_q;
- (id)let_p;
- (id)let_o;
- (id)let_n;
- (id)let_m;
- (id)let_l;
- (id)let_k;
- (id)let_j;
- (id)let_i;
- (id)let_h;
- (id)let_g;
- (id)let_f;
- (id)let_e;
- (id)let_d;
- (id)let_c;
- (id)let_b;
- (id)let_a;
- (id)stringValue;
- (void)appendString:(id)arg1;
- (id)init;

@end

