//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPRecentScenariosService.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface SPRecentScenariosServiceImpl : NSObject <SPRecentScenariosService>
{
    id <SPKeyValueStorage> _storage;
    id <SPSettings> _settings;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_scenarios;
}

@property(retain, nonatomic) NSMutableArray *scenarios; // @synthesize scenarios=_scenarios;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) id <SPSettings> settings; // @synthesize settings=_settings;
@property(readonly, nonatomic) id <SPKeyValueStorage> storage; // @synthesize storage=_storage;
- (void).cxx_destruct;
- (void)clearAll;
- (void)addScenario:(id)arg1;
- (id)initWithStorage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

