//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSTimer, SPCacheControllerImplementation;

@interface SPVideosCache : NSObject
{
    id <SPFileManager> _fileManager;
    SPCacheControllerImplementation *_fileCache;
    NSTimer *_garbageCollectorTimer;
    NSObject<OS_dispatch_queue> *_thumbnailQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *thumbnailQueue; // @synthesize thumbnailQueue=_thumbnailQueue;
@property(retain, nonatomic) NSTimer *garbageCollectorTimer; // @synthesize garbageCollectorTimer=_garbageCollectorTimer;
@property(retain, nonatomic) SPCacheControllerImplementation *fileCache; // @synthesize fileCache=_fileCache;
@property(retain, nonatomic) id <SPFileManager> fileManager; // @synthesize fileManager=_fileManager;
- (void).cxx_destruct;
- (id)generateThumbnailFileNameForKey:(id)arg1;
- (id)thumbnailFilePathForKey:(id)arg1;
- (id)generateVideoFileNameForKey:(id)arg1;
- (_Bool)fullScreenVideoExistsForKey:(id)arg1;
- (void)clearAll;
- (void)collectGarbage;
- (void)loadThumbnailImageForKey:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)saveThumbnailImage:(id)arg1 forKey:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)commitStagingFullScreenVideo:(id)arg1;
- (id)getFullScreenVideoCachePath:(id)arg1;
- (id)getStagingFullScreenVideoCachePath:(id)arg1;
- (id)generateKeyForScenario:(id)arg1 personsGroup:(id)arg2 shouldBePersonsSwapped:(_Bool)arg3 text:(id)arg4;
- (id)initWithSettings:(id)arg1;

@end

