//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SubscribedUserScore : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) float friendScore; // @dynamic friendScore;
@property(nonatomic) long long relationshipTimestampMsecs; // @dynamic relationshipTimestampMsecs;
@property(copy, nonatomic) NSString *userId; // @dynamic userId;

@end

