//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SwipeView <NSObject>

@optional
- (void)viewDidFullyAppearWithModalPresentedAbove;
- (void)tabBarTriggeredWithAction:(long long)arg1;
- (void)viewDidPartiallyDisappear;
- (void)viewDidAppearAtOffset:(double)arg1;
- (void)viewDidPartiallyAppear;
- (void)viewDidSwipeOut;
- (void)viewDidSwipeIn;
- (void)viewDidFullyDisappear;
- (void)viewDidFullyAppear;
@end

