//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TargetSegmentationResultHolder : NSObject
{
    shared_ptr_2af1def1 _targetSegmentationResult;
}

@property(nonatomic) shared_ptr_2af1def1 targetSegmentationResult; // @synthesize targetSegmentationResult=_targetSegmentationResult;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithTargetSegmentationResult:(shared_ptr_2af1def1)arg1;

@end

