//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TCV3PresenceService : NSObject
{
    struct Handle<std::__1::shared_ptr<talkcorev3::PresenceService>, std::__1::shared_ptr<talkcorev3::PresenceService>> _cppRefHandle;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)getActiveConversations;
- (void)processChatConnectivityStatusChange:(_Bool)arg1;
- (void)processChatMessage:(id)arg1;
- (void)setDelegate:(id)arg1;
- (id)initWithCpp:(const shared_ptr_a98b9edb *)arg1;

@end

