//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScreen.h"

@interface UIScreen (SCSafeAreaInsets)
+ (double)sc_ngsFooterHeight;
+ (double)sc_ngsHeaderHeight;
+ (double)sc_headerHeight;
+ (double)sc_safeHeaderButtonInset;
+ (double)sc_safeFooterButtonInset;
+ (struct UIEdgeInsets)sc_filterSafeInsets;
+ (struct UIEdgeInsets)sc_visualSafeInsets;
+ (struct UIEdgeInsets)sc_headerSafeInsets;
+ (struct UIEdgeInsets)sc_safeAreaInsetsForInterfaceOrientation:(long long)arg1;
+ (struct UIEdgeInsets)sc_safeAreaInsets;
@end

